/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.ac;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.ac.AcFuncMapper;
import org.tis.tools.model.po.ac.AcFunc;


/**
 * 功能(AC_FUNC)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class AcFuncService {

	@Autowired
	AcFuncMapper acFuncMapper;
	
    public void insert(AcFunc t){
    	acFuncMapper.insert(t);
    }
    
    public void update(AcFunc t){
    	acFuncMapper.update(t); 
    }
   
    public void updateForce(AcFunc t){
    	acFuncMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	acFuncMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	acFuncMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,AcFunc t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	acFuncMapper.updateByCondition(map); 
    }

    public List<AcFunc> query(WhereCondition wc){
    	return acFuncMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return acFuncMapper.count(wc);
    }
   
    public AcFunc loadByGuid(String guid){
    	return acFuncMapper.loadByGuid(guid);
    }
}
