/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.ac;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.mapper.ac.AcPartyRoleMapper;
import org.tis.tools.model.po.ac.AcPartyRole;


/**
 * 组织对象与角色对应关系(AC_PARTY_ROLE)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class AcPartyRoleService {

	@Autowired
	AcPartyRoleMapper acPartyRoleMapper;
	
    public void insert(AcPartyRole t){
    	acPartyRoleMapper.insert(t);
    }
    
    public void update(AcPartyRole t){
    	acPartyRoleMapper.update(t); 
    }
   
    public void updateForce(AcPartyRole t){
    	acPartyRoleMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	acPartyRoleMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	acPartyRoleMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,AcPartyRole t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	acPartyRoleMapper.updateByCondition(map); 
    }

    public List<AcPartyRole> query(WhereCondition wc){
    	return acPartyRoleMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return acPartyRoleMapper.count(wc);
    }
   
    public AcPartyRole loadByGuid(String guid){
    	return acPartyRoleMapper.loadByGuid(guid);
    }
}
