package org.tis.tools;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 实体.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AcEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 应用系统. */
	private AcApp appacApp;

	/** 实体名称. */
	private String entityName;

	/** 数据库表名. */
	private String tableName;

	/** 实体描述. */
	private String entityDesc;

	/** 顺序. */
	private Integer displayOrder;

	/** 实体类型. */
	private String entityType;

	/** 是否可增加. */
	private String isadd;

	/** 是否可删除. */
	private String isdel;

	/** 可修改. */
	private String ismodify;

	/** 可查看. */
	private String isview;

	/** 是否需要分页显示. */
	private String ispage;

	/** 每页记录数. */
	private Integer pageLen;

	/** 删除记录检查引用关系. */
	private String checkRef;

	/** The set of 数据范围权限. */
	private Set<AcDatascope> acDatascopeSet;

	/** The set of 实体属性. */
	private Set<AcEntityfield> acEntityfieldSet;

	/** The set of 角色实体关系. */
	private Set<AcRoleEntity> acRoleEntitySet;

	/**
	 * Constructor.
	 */
	public AcEntity() {
		this.acDatascopeSet = new HashSet<AcDatascope>();
		this.acEntityfieldSet = new HashSet<AcEntityfield>();
		this.acRoleEntitySet = new HashSet<AcRoleEntity>();
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 应用系统.
	 * 
	 * @param appacApp
	 *            应用系统
	 */
	public void setappacApp(AcApp appacApp) {
		this.appacApp = appacApp;
	}

	/**
	 * Get the 应用系统.
	 * 
	 * @return 应用系统
	 */
	public AcApp getappacApp() {
		return this.appacApp;
	}

	/**
	 * Set the 实体名称.
	 * 
	 * @param entityName
	 *            实体名称
	 */
	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	/**
	 * Get the 实体名称.
	 * 
	 * @return 实体名称
	 */
	public String getEntityName() {
		return this.entityName;
	}

	/**
	 * Set the 数据库表名.
	 * 
	 * @param tableName
	 *            数据库表名
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * Get the 数据库表名.
	 * 
	 * @return 数据库表名
	 */
	public String getTableName() {
		return this.tableName;
	}

	/**
	 * Set the 实体描述.
	 * 
	 * @param entityDesc
	 *            实体描述
	 */
	public void setEntityDesc(String entityDesc) {
		this.entityDesc = entityDesc;
	}

	/**
	 * Get the 实体描述.
	 * 
	 * @return 实体描述
	 */
	public String getEntityDesc() {
		return this.entityDesc;
	}

	/**
	 * Set the 顺序.
	 * 
	 * @param displayOrder
	 *            顺序
	 */
	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * Get the 顺序.
	 * 
	 * @return 顺序
	 */
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	/**
	 * Set the 实体类型.
	 * 
	 * @param entityType
	 *            实体类型
	 */
	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	/**
	 * Get the 实体类型.
	 * 
	 * @return 实体类型
	 */
	public String getEntityType() {
		return this.entityType;
	}

	/**
	 * Set the 是否可增加.
	 * 
	 * @param isadd
	 *            是否可增加
	 */
	public void setIsadd(String isadd) {
		this.isadd = isadd;
	}

	/**
	 * Get the 是否可增加.
	 * 
	 * @return 是否可增加
	 */
	public String getIsadd() {
		return this.isadd;
	}

	/**
	 * Set the 是否可删除.
	 * 
	 * @param isdel
	 *            是否可删除
	 */
	public void setIsdel(String isdel) {
		this.isdel = isdel;
	}

	/**
	 * Get the 是否可删除.
	 * 
	 * @return 是否可删除
	 */
	public String getIsdel() {
		return this.isdel;
	}

	/**
	 * Set the 可修改.
	 * 
	 * @param ismodify
	 *            可修改
	 */
	public void setIsmodify(String ismodify) {
		this.ismodify = ismodify;
	}

	/**
	 * Get the 可修改.
	 * 
	 * @return 可修改
	 */
	public String getIsmodify() {
		return this.ismodify;
	}

	/**
	 * Set the 可查看.
	 * 
	 * @param isview
	 *            可查看
	 */
	public void setIsview(String isview) {
		this.isview = isview;
	}

	/**
	 * Get the 可查看.
	 * 
	 * @return 可查看
	 */
	public String getIsview() {
		return this.isview;
	}

	/**
	 * Set the 是否需要分页显示.
	 * 
	 * @param ispage
	 *            是否需要分页显示
	 */
	public void setIspage(String ispage) {
		this.ispage = ispage;
	}

	/**
	 * Get the 是否需要分页显示.
	 * 
	 * @return 是否需要分页显示
	 */
	public String getIspage() {
		return this.ispage;
	}

	/**
	 * Set the 每页记录数.
	 * 
	 * @param pageLen
	 *            每页记录数
	 */
	public void setPageLen(Integer pageLen) {
		this.pageLen = pageLen;
	}

	/**
	 * Get the 每页记录数.
	 * 
	 * @return 每页记录数
	 */
	public Integer getPageLen() {
		return this.pageLen;
	}

	/**
	 * Set the 删除记录检查引用关系.
	 * 
	 * @param checkRef
	 *            删除记录检查引用关系
	 */
	public void setCheckRef(String checkRef) {
		this.checkRef = checkRef;
	}

	/**
	 * Get the 删除记录检查引用关系.
	 * 
	 * @return 删除记录检查引用关系
	 */
	public String getCheckRef() {
		return this.checkRef;
	}

	/**
	 * Set the set of the 数据范围权限.
	 * 
	 * @param acDatascopeSet
	 *            The set of 数据范围权限
	 */
	public void setAcDatascopeSet(Set<AcDatascope> acDatascopeSet) {
		this.acDatascopeSet = acDatascopeSet;
	}

	/**
	 * Add the 数据范围权限.
	 * 
	 * @param acDatascope
	 *            数据范围权限
	 */
	public void addAcDatascope(AcDatascope acDatascope) {
		this.acDatascopeSet.add(acDatascope);
	}

	/**
	 * Get the set of the 数据范围权限.
	 * 
	 * @return The set of 数据范围权限
	 */
	public Set<AcDatascope> getAcDatascopeSet() {
		return this.acDatascopeSet;
	}

	/**
	 * Set the set of the 实体属性.
	 * 
	 * @param acEntityfieldSet
	 *            The set of 实体属性
	 */
	public void setAcEntityfieldSet(Set<AcEntityfield> acEntityfieldSet) {
		this.acEntityfieldSet = acEntityfieldSet;
	}

	/**
	 * Add the 实体属性.
	 * 
	 * @param acEntityfield
	 *            实体属性
	 */
	public void addAcEntityfield(AcEntityfield acEntityfield) {
		this.acEntityfieldSet.add(acEntityfield);
	}

	/**
	 * Get the set of the 实体属性.
	 * 
	 * @return The set of 实体属性
	 */
	public Set<AcEntityfield> getAcEntityfieldSet() {
		return this.acEntityfieldSet;
	}

	/**
	 * Set the set of the 角色实体关系.
	 * 
	 * @param acRoleEntitySet
	 *            The set of 角色实体关系
	 */
	public void setAcRoleEntitySet(Set<AcRoleEntity> acRoleEntitySet) {
		this.acRoleEntitySet = acRoleEntitySet;
	}

	/**
	 * Add the 角色实体关系.
	 * 
	 * @param acRoleEntity
	 *            角色实体关系
	 */
	public void addAcRoleEntity(AcRoleEntity acRoleEntity) {
		this.acRoleEntitySet.add(acRoleEntity);
	}

	/**
	 * Get the set of the 角色实体关系.
	 * 
	 * @return The set of 角色实体关系
	 */
	public Set<AcRoleEntity> getAcRoleEntitySet() {
		return this.acRoleEntitySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AcEntity other = (AcEntity) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
