package org.tis.tools;

import java.io.Serializable;

/**
 * Model class of 功能资源对应.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AcFuncResource implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 功能. */
	private AcFunc funcacFunc;

	/** 资源类型. */
	private String resType;

	/** 资源路径. */
	private String resPath;

	/** 构件包名. */
	private String compackName;

	/** 资源显示名称. */
	private String resShowName;

	/**
	 * Constructor.
	 */
	public AcFuncResource() {
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 功能.
	 * 
	 * @param funcacFunc
	 *            功能
	 */
	public void setfuncacFunc(AcFunc funcacFunc) {
		this.funcacFunc = funcacFunc;
	}

	/**
	 * Get the 功能.
	 * 
	 * @return 功能
	 */
	public AcFunc getfuncacFunc() {
		return this.funcacFunc;
	}

	/**
	 * Set the 资源类型.
	 * 
	 * @param resType
	 *            资源类型
	 */
	public void setResType(String resType) {
		this.resType = resType;
	}

	/**
	 * Get the 资源类型.
	 * 
	 * @return 资源类型
	 */
	public String getResType() {
		return this.resType;
	}

	/**
	 * Set the 资源路径.
	 * 
	 * @param resPath
	 *            资源路径
	 */
	public void setResPath(String resPath) {
		this.resPath = resPath;
	}

	/**
	 * Get the 资源路径.
	 * 
	 * @return 资源路径
	 */
	public String getResPath() {
		return this.resPath;
	}

	/**
	 * Set the 构件包名.
	 * 
	 * @param compackName
	 *            构件包名
	 */
	public void setCompackName(String compackName) {
		this.compackName = compackName;
	}

	/**
	 * Get the 构件包名.
	 * 
	 * @return 构件包名
	 */
	public String getCompackName() {
		return this.compackName;
	}

	/**
	 * Set the 资源显示名称.
	 * 
	 * @param resShowName
	 *            资源显示名称
	 */
	public void setResShowName(String resShowName) {
		this.resShowName = resShowName;
	}

	/**
	 * Get the 资源显示名称.
	 * 
	 * @return 资源显示名称
	 */
	public String getResShowName() {
		return this.resShowName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AcFuncResource other = (AcFuncResource) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
