package org.tis.tools;

import java.io.Serializable;

/**
 * Model class of 工作组岗位列表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OmGroupPosition implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 工作组. */
	private OmGroup groupomGroup;

	/** 岗位. */
	private OmPosition positionomPosition;

	/**
	 * Constructor.
	 */
	public OmGroupPosition() {
	}

	/**
	 * Set the 工作组.
	 * 
	 * @param groupomGroup
	 *            工作组
	 */
	public void setgroupomGroup(OmGroup groupomGroup) {
		this.groupomGroup = groupomGroup;
	}

	/**
	 * Get the 工作组.
	 * 
	 * @return 工作组
	 */
	public OmGroup getgroupomGroup() {
		return this.groupomGroup;
	}

	/**
	 * Set the 岗位.
	 * 
	 * @param positionomPosition
	 *            岗位
	 */
	public void setpositionomPosition(OmPosition positionomPosition) {
		this.positionomPosition = positionomPosition;
	}

	/**
	 * Get the 岗位.
	 * 
	 * @return 岗位
	 */
	public OmPosition getpositionomPosition() {
		return this.positionomPosition;
	}


}
