package org.tis.tools;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 岗位.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OmPosition implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 机构信息表. */
	private OmOrg orgomOrg;

	/** 岗位代码. */
	private String positionCode;

	/** 岗位名称. */
	private String positionName;

	/** 岗位类别. */
	private String positionType;

	/** 岗位状态. */
	private String positionStatus;

	/** 是否叶子岗位. */
	private String isleaf;

	/** 子节点数. */
	private Integer subCount;

	/** 岗位层次. */
	private Integer positionLevel;

	/** 岗位序列. */
	private String positionSeq;

	/** 岗位. */
	private OmPosition parentsomPosition;

	/** 职务定义表. */
	private OmDuty dutyomDuty;

	/** 岗位有效开始日期. */
	private Date startDate;

	/** 岗位有效截止日期. */
	private Date endDate;

	/** 创建时间. */
	private Date createtime;

	/** 最近更新时间. */
	private Date lastupdate;

	/** 最近更新人员. */
	private String updator;

	/** The set of 应用岗位列表. */
	private Set<OmAppPosition> omAppPositionSet;

	/** The set of 员工岗位对应关系. */
	private Set<OmEmpPosition> omEmpPositionSet;

	/** The set of 工作组岗位列表. */
	private Set<OmGroupPosition> omGroupPositionSet;

	/** The set of 岗位. */
	private Set<OmPosition> omPositionSet;

	/**
	 * Constructor.
	 */
	public OmPosition() {
		this.omAppPositionSet = new HashSet<OmAppPosition>();
		this.omEmpPositionSet = new HashSet<OmEmpPosition>();
		this.omGroupPositionSet = new HashSet<OmGroupPosition>();
		this.omPositionSet = new HashSet<OmPosition>();
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 机构信息表.
	 * 
	 * @param orgomOrg
	 *            机构信息表
	 */
	public void setorgomOrg(OmOrg orgomOrg) {
		this.orgomOrg = orgomOrg;
	}

	/**
	 * Get the 机构信息表.
	 * 
	 * @return 机构信息表
	 */
	public OmOrg getorgomOrg() {
		return this.orgomOrg;
	}

	/**
	 * Set the 岗位代码.
	 * 
	 * @param positionCode
	 *            岗位代码
	 */
	public void setPositionCode(String positionCode) {
		this.positionCode = positionCode;
	}

	/**
	 * Get the 岗位代码.
	 * 
	 * @return 岗位代码
	 */
	public String getPositionCode() {
		return this.positionCode;
	}

	/**
	 * Set the 岗位名称.
	 * 
	 * @param positionName
	 *            岗位名称
	 */
	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	/**
	 * Get the 岗位名称.
	 * 
	 * @return 岗位名称
	 */
	public String getPositionName() {
		return this.positionName;
	}

	/**
	 * Set the 岗位类别.
	 * 
	 * @param positionType
	 *            岗位类别
	 */
	public void setPositionType(String positionType) {
		this.positionType = positionType;
	}

	/**
	 * Get the 岗位类别.
	 * 
	 * @return 岗位类别
	 */
	public String getPositionType() {
		return this.positionType;
	}

	/**
	 * Set the 岗位状态.
	 * 
	 * @param positionStatus
	 *            岗位状态
	 */
	public void setPositionStatus(String positionStatus) {
		this.positionStatus = positionStatus;
	}

	/**
	 * Get the 岗位状态.
	 * 
	 * @return 岗位状态
	 */
	public String getPositionStatus() {
		return this.positionStatus;
	}

	/**
	 * Set the 是否叶子岗位.
	 * 
	 * @param isleaf
	 *            是否叶子岗位
	 */
	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	/**
	 * Get the 是否叶子岗位.
	 * 
	 * @return 是否叶子岗位
	 */
	public String getIsleaf() {
		return this.isleaf;
	}

	/**
	 * Set the 子节点数.
	 * 
	 * @param subCount
	 *            子节点数
	 */
	public void setSubCount(Integer subCount) {
		this.subCount = subCount;
	}

	/**
	 * Get the 子节点数.
	 * 
	 * @return 子节点数
	 */
	public Integer getSubCount() {
		return this.subCount;
	}

	/**
	 * Set the 岗位层次.
	 * 
	 * @param positionLevel
	 *            岗位层次
	 */
	public void setPositionLevel(Integer positionLevel) {
		this.positionLevel = positionLevel;
	}

	/**
	 * Get the 岗位层次.
	 * 
	 * @return 岗位层次
	 */
	public Integer getPositionLevel() {
		return this.positionLevel;
	}

	/**
	 * Set the 岗位序列.
	 * 
	 * @param positionSeq
	 *            岗位序列
	 */
	public void setPositionSeq(String positionSeq) {
		this.positionSeq = positionSeq;
	}

	/**
	 * Get the 岗位序列.
	 * 
	 * @return 岗位序列
	 */
	public String getPositionSeq() {
		return this.positionSeq;
	}

	/**
	 * Set the 岗位.
	 * 
	 * @param parentsomPosition
	 *            岗位
	 */
	public void setparentsomPosition(OmPosition parentsomPosition) {
		this.parentsomPosition = parentsomPosition;
	}

	/**
	 * Get the 岗位.
	 * 
	 * @return 岗位
	 */
	public OmPosition getparentsomPosition() {
		return this.parentsomPosition;
	}

	/**
	 * Set the 职务定义表.
	 * 
	 * @param dutyomDuty
	 *            职务定义表
	 */
	public void setdutyomDuty(OmDuty dutyomDuty) {
		this.dutyomDuty = dutyomDuty;
	}

	/**
	 * Get the 职务定义表.
	 * 
	 * @return 职务定义表
	 */
	public OmDuty getdutyomDuty() {
		return this.dutyomDuty;
	}

	/**
	 * Set the 岗位有效开始日期.
	 * 
	 * @param startDate
	 *            岗位有效开始日期
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * Get the 岗位有效开始日期.
	 * 
	 * @return 岗位有效开始日期
	 */
	public Date getStartDate() {
		return this.startDate;
	}

	/**
	 * Set the 岗位有效截止日期.
	 * 
	 * @param endDate
	 *            岗位有效截止日期
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * Get the 岗位有效截止日期.
	 * 
	 * @return 岗位有效截止日期
	 */
	public Date getEndDate() {
		return this.endDate;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 最近更新时间.
	 * 
	 * @param lastupdate
	 *            最近更新时间
	 */
	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	/**
	 * Get the 最近更新时间.
	 * 
	 * @return 最近更新时间
	 */
	public Date getLastupdate() {
		return this.lastupdate;
	}

	/**
	 * Set the 最近更新人员.
	 * 
	 * @param updator
	 *            最近更新人员
	 */
	public void setUpdator(String updator) {
		this.updator = updator;
	}

	/**
	 * Get the 最近更新人员.
	 * 
	 * @return 最近更新人员
	 */
	public String getUpdator() {
		return this.updator;
	}

	/**
	 * Set the set of the 应用岗位列表.
	 * 
	 * @param omAppPositionSet
	 *            The set of 应用岗位列表
	 */
	public void setOmAppPositionSet(Set<OmAppPosition> omAppPositionSet) {
		this.omAppPositionSet = omAppPositionSet;
	}

	/**
	 * Add the 应用岗位列表.
	 * 
	 * @param omAppPosition
	 *            应用岗位列表
	 */
	public void addOmAppPosition(OmAppPosition omAppPosition) {
		this.omAppPositionSet.add(omAppPosition);
	}

	/**
	 * Get the set of the 应用岗位列表.
	 * 
	 * @return The set of 应用岗位列表
	 */
	public Set<OmAppPosition> getOmAppPositionSet() {
		return this.omAppPositionSet;
	}

	/**
	 * Set the set of the 员工岗位对应关系.
	 * 
	 * @param omEmpPositionSet
	 *            The set of 员工岗位对应关系
	 */
	public void setOmEmpPositionSet(Set<OmEmpPosition> omEmpPositionSet) {
		this.omEmpPositionSet = omEmpPositionSet;
	}

	/**
	 * Add the 员工岗位对应关系.
	 * 
	 * @param omEmpPosition
	 *            员工岗位对应关系
	 */
	public void addOmEmpPosition(OmEmpPosition omEmpPosition) {
		this.omEmpPositionSet.add(omEmpPosition);
	}

	/**
	 * Get the set of the 员工岗位对应关系.
	 * 
	 * @return The set of 员工岗位对应关系
	 */
	public Set<OmEmpPosition> getOmEmpPositionSet() {
		return this.omEmpPositionSet;
	}

	/**
	 * Set the set of the 工作组岗位列表.
	 * 
	 * @param omGroupPositionSet
	 *            The set of 工作组岗位列表
	 */
	public void setOmGroupPositionSet(Set<OmGroupPosition> omGroupPositionSet) {
		this.omGroupPositionSet = omGroupPositionSet;
	}

	/**
	 * Add the 工作组岗位列表.
	 * 
	 * @param omGroupPosition
	 *            工作组岗位列表
	 */
	public void addOmGroupPosition(OmGroupPosition omGroupPosition) {
		this.omGroupPositionSet.add(omGroupPosition);
	}

	/**
	 * Get the set of the 工作组岗位列表.
	 * 
	 * @return The set of 工作组岗位列表
	 */
	public Set<OmGroupPosition> getOmGroupPositionSet() {
		return this.omGroupPositionSet;
	}

	/**
	 * Set the set of the 岗位.
	 * 
	 * @param omPositionSet
	 *            The set of 岗位
	 */
	public void setOmPositionSet(Set<OmPosition> omPositionSet) {
		this.omPositionSet = omPositionSet;
	}

	/**
	 * Add the 岗位.
	 * 
	 * @param omPosition
	 *            岗位
	 */
	public void addOmPosition(OmPosition omPosition) {
		this.omPositionSet.add(omPosition);
	}

	/**
	 * Get the set of the 岗位.
	 * 
	 * @return The set of 岗位
	 */
	public Set<OmPosition> getOmPositionSet() {
		return this.omPositionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		OmPosition other = (OmPosition) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
