package org.tis.tools;

import java.io.Serializable;

/**
 * Model class of 业务字典项.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SysDictItem implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 业务字典. */
	private SysDict dictsysDict;

	/** 字典项名称. */
	private String itemName;

	/** 字典项. */
	private String itemValue;

	/** 实际值. */
	private String sendValue;

	/** 顺序号. */
	private Integer seqno;

	/**
	 * Constructor.
	 */
	public SysDictItem() {
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 业务字典.
	 * 
	 * @param dictsysDict
	 *            业务字典
	 */
	public void setdictsysDict(SysDict dictsysDict) {
		this.dictsysDict = dictsysDict;
	}

	/**
	 * Get the 业务字典.
	 * 
	 * @return 业务字典
	 */
	public SysDict getdictsysDict() {
		return this.dictsysDict;
	}

	/**
	 * Set the 字典项名称.
	 * 
	 * @param itemName
	 *            字典项名称
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**
	 * Get the 字典项名称.
	 * 
	 * @return 字典项名称
	 */
	public String getItemName() {
		return this.itemName;
	}

	/**
	 * Set the 字典项.
	 * 
	 * @param itemValue
	 *            字典项
	 */
	public void setItemValue(String itemValue) {
		this.itemValue = itemValue;
	}

	/**
	 * Get the 字典项.
	 * 
	 * @return 字典项
	 */
	public String getItemValue() {
		return this.itemValue;
	}

	/**
	 * Set the 实际值.
	 * 
	 * @param sendValue
	 *            实际值
	 */
	public void setSendValue(String sendValue) {
		this.sendValue = sendValue;
	}

	/**
	 * Get the 实际值.
	 * 
	 * @return 实际值
	 */
	public String getSendValue() {
		return this.sendValue;
	}

	/**
	 * Set the 顺序号.
	 * 
	 * @param seqno
	 *            顺序号
	 */
	public void setSeqno(Integer seqno) {
		this.seqno = seqno;
	}

	/**
	 * Get the 顺序号.
	 * 
	 * @return 顺序号
	 */
	public Integer getSeqno() {
		return this.seqno;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SysDictItem other = (SysDictItem) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
