package org.tis.tools;

import java.io.Serializable;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

/**
 * Model class of 测试.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SysTest implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 测试BIGINT. */
	private Long testBigint;

	/** 测试GIBINT(8). */
	private Long testGibintn;

	/** 测试CHAR. */
	private String testChar;

	/** 测试CHAR(16). */
	private String testCharn;

	/** 测试DATE. */
	private Date testDate;

	/** 测试DATETIME. */
	private Date testDatetime;

	/** 测试DECIMAL. */
	private Integer testDecimal;

	/** 测试DECIMAL(12). */
	private Integer testDecimalp;

	/** 测试DECIMAL(12,4). */
	private Double testDecimalps;

	/** 测试DOUBLE. */
	private Double testDouble;

	/** 测试DOUBLE(10,4). */
	private Double testDoublemd;

	/** 测试FLOAT. */
	private Float testFloat;

	/** 测试FLOAT(10). */
	private Float testFloatp;

	/** 测试FLOAT(10,4). */
	private Float testFloatmd;

	/** 测试INT. */
	private Integer testInt;

	/** 测试INT(12). */
	private Integer testIntn;

	/** 测试TIME. */
	private Time testTime;

	/** 测试TIMESTAMP. */
	private Date testTimestamp;

	/** 测试VARCHAR(32). */
	private String testVarcharn;

	/** 测试TEXT. */
	private String tsetText;

	/** 测试BLOB. */
	private Blob testBlob;

	/**
	 * Constructor.
	 */
	public SysTest() {
	}

	/**
	 * Set the 测试BIGINT.
	 * 
	 * @param testBigint
	 *            测试BIGINT
	 */
	public void setTestBigint(Long testBigint) {
		this.testBigint = testBigint;
	}

	/**
	 * Get the 测试BIGINT.
	 * 
	 * @return 测试BIGINT
	 */
	public Long getTestBigint() {
		return this.testBigint;
	}

	/**
	 * Set the 测试GIBINT(8).
	 * 
	 * @param testGibintn
	 *            测试GIBINT(8)
	 */
	public void setTestGibintn(Long testGibintn) {
		this.testGibintn = testGibintn;
	}

	/**
	 * Get the 测试GIBINT(8).
	 * 
	 * @return 测试GIBINT(8)
	 */
	public Long getTestGibintn() {
		return this.testGibintn;
	}

	/**
	 * Set the 测试CHAR.
	 * 
	 * @param testChar
	 *            测试CHAR
	 */
	public void setTestChar(String testChar) {
		this.testChar = testChar;
	}

	/**
	 * Get the 测试CHAR.
	 * 
	 * @return 测试CHAR
	 */
	public String getTestChar() {
		return this.testChar;
	}

	/**
	 * Set the 测试CHAR(16).
	 * 
	 * @param testCharn
	 *            测试CHAR(16)
	 */
	public void setTestCharn(String testCharn) {
		this.testCharn = testCharn;
	}

	/**
	 * Get the 测试CHAR(16).
	 * 
	 * @return 测试CHAR(16)
	 */
	public String getTestCharn() {
		return this.testCharn;
	}

	/**
	 * Set the 测试DATE.
	 * 
	 * @param testDate
	 *            测试DATE
	 */
	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	/**
	 * Get the 测试DATE.
	 * 
	 * @return 测试DATE
	 */
	public Date getTestDate() {
		return this.testDate;
	}

	/**
	 * Set the 测试DATETIME.
	 * 
	 * @param testDatetime
	 *            测试DATETIME
	 */
	public void setTestDatetime(Date testDatetime) {
		this.testDatetime = testDatetime;
	}

	/**
	 * Get the 测试DATETIME.
	 * 
	 * @return 测试DATETIME
	 */
	public Date getTestDatetime() {
		return this.testDatetime;
	}

	/**
	 * Set the 测试DECIMAL.
	 * 
	 * @param testDecimal
	 *            测试DECIMAL
	 */
	public void setTestDecimal(Integer testDecimal) {
		this.testDecimal = testDecimal;
	}

	/**
	 * Get the 测试DECIMAL.
	 * 
	 * @return 测试DECIMAL
	 */
	public Integer getTestDecimal() {
		return this.testDecimal;
	}

	/**
	 * Set the 测试DECIMAL(12).
	 * 
	 * @param testDecimalp
	 *            测试DECIMAL(12)
	 */
	public void setTestDecimalp(Integer testDecimalp) {
		this.testDecimalp = testDecimalp;
	}

	/**
	 * Get the 测试DECIMAL(12).
	 * 
	 * @return 测试DECIMAL(12)
	 */
	public Integer getTestDecimalp() {
		return this.testDecimalp;
	}

	/**
	 * Set the 测试DECIMAL(12,4).
	 * 
	 * @param testDecimalps
	 *            测试DECIMAL(12,4)
	 */
	public void setTestDecimalps(Double testDecimalps) {
		this.testDecimalps = testDecimalps;
	}

	/**
	 * Get the 测试DECIMAL(12,4).
	 * 
	 * @return 测试DECIMAL(12,4)
	 */
	public Double getTestDecimalps() {
		return this.testDecimalps;
	}

	/**
	 * Set the 测试DOUBLE.
	 * 
	 * @param testDouble
	 *            测试DOUBLE
	 */
	public void setTestDouble(Double testDouble) {
		this.testDouble = testDouble;
	}

	/**
	 * Get the 测试DOUBLE.
	 * 
	 * @return 测试DOUBLE
	 */
	public Double getTestDouble() {
		return this.testDouble;
	}

	/**
	 * Set the 测试DOUBLE(10,4).
	 * 
	 * @param testDoublemd
	 *            测试DOUBLE(10,4)
	 */
	public void setTestDoublemd(Double testDoublemd) {
		this.testDoublemd = testDoublemd;
	}

	/**
	 * Get the 测试DOUBLE(10,4).
	 * 
	 * @return 测试DOUBLE(10,4)
	 */
	public Double getTestDoublemd() {
		return this.testDoublemd;
	}

	/**
	 * Set the 测试FLOAT.
	 * 
	 * @param testFloat
	 *            测试FLOAT
	 */
	public void setTestFloat(Float testFloat) {
		this.testFloat = testFloat;
	}

	/**
	 * Get the 测试FLOAT.
	 * 
	 * @return 测试FLOAT
	 */
	public Float getTestFloat() {
		return this.testFloat;
	}

	/**
	 * Set the 测试FLOAT(10).
	 * 
	 * @param testFloatp
	 *            测试FLOAT(10)
	 */
	public void setTestFloatp(Float testFloatp) {
		this.testFloatp = testFloatp;
	}

	/**
	 * Get the 测试FLOAT(10).
	 * 
	 * @return 测试FLOAT(10)
	 */
	public Float getTestFloatp() {
		return this.testFloatp;
	}

	/**
	 * Set the 测试FLOAT(10,4).
	 * 
	 * @param testFloatmd
	 *            测试FLOAT(10,4)
	 */
	public void setTestFloatmd(Float testFloatmd) {
		this.testFloatmd = testFloatmd;
	}

	/**
	 * Get the 测试FLOAT(10,4).
	 * 
	 * @return 测试FLOAT(10,4)
	 */
	public Float getTestFloatmd() {
		return this.testFloatmd;
	}

	/**
	 * Set the 测试INT.
	 * 
	 * @param testInt
	 *            测试INT
	 */
	public void setTestInt(Integer testInt) {
		this.testInt = testInt;
	}

	/**
	 * Get the 测试INT.
	 * 
	 * @return 测试INT
	 */
	public Integer getTestInt() {
		return this.testInt;
	}

	/**
	 * Set the 测试INT(12).
	 * 
	 * @param testIntn
	 *            测试INT(12)
	 */
	public void setTestIntn(Integer testIntn) {
		this.testIntn = testIntn;
	}

	/**
	 * Get the 测试INT(12).
	 * 
	 * @return 测试INT(12)
	 */
	public Integer getTestIntn() {
		return this.testIntn;
	}

	/**
	 * Set the 测试TIME.
	 * 
	 * @param testTime
	 *            测试TIME
	 */
	public void setTestTime(Time testTime) {
		this.testTime = testTime;
	}

	/**
	 * Get the 测试TIME.
	 * 
	 * @return 测试TIME
	 */
	public Time getTestTime() {
		return this.testTime;
	}

	/**
	 * Set the 测试TIMESTAMP.
	 * 
	 * @param testTimestamp
	 *            测试TIMESTAMP
	 */
	public void setTestTimestamp(Date testTimestamp) {
		this.testTimestamp = testTimestamp;
	}

	/**
	 * Get the 测试TIMESTAMP.
	 * 
	 * @return 测试TIMESTAMP
	 */
	public Date getTestTimestamp() {
		return this.testTimestamp;
	}

	/**
	 * Set the 测试VARCHAR(32).
	 * 
	 * @param testVarcharn
	 *            测试VARCHAR(32)
	 */
	public void setTestVarcharn(String testVarcharn) {
		this.testVarcharn = testVarcharn;
	}

	/**
	 * Get the 测试VARCHAR(32).
	 * 
	 * @return 测试VARCHAR(32)
	 */
	public String getTestVarcharn() {
		return this.testVarcharn;
	}

	/**
	 * Set the 测试TEXT.
	 * 
	 * @param tsetText
	 *            测试TEXT
	 */
	public void setTsetText(String tsetText) {
		this.tsetText = tsetText;
	}

	/**
	 * Get the 测试TEXT.
	 * 
	 * @return 测试TEXT
	 */
	public String getTsetText() {
		return this.tsetText;
	}

	/**
	 * Set the 测试BLOB.
	 * 
	 * @param testBlob
	 *            测试BLOB
	 */
	public void setTestBlob(Blob testBlob) {
		this.testBlob = testBlob;
	}

	/**
	 * Get the 测试BLOB.
	 * 
	 * @return 测试BLOB
	 */
	public Blob getTestBlob() {
		return this.testBlob;
	}


}
