/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.om;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.om.OmGroupMapper;
import org.tis.tools.model.po.om.OmGroup;


/**
 * 工作组(OM_GROUP)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class OmGroupService {

	@Autowired
	OmGroupMapper omGroupMapper;
	
    public void insert(OmGroup t){
    	omGroupMapper.insert(t);
    }
    
    public void update(OmGroup t){
    	omGroupMapper.update(t); 
    }
   
    public void updateForce(OmGroup t){
    	omGroupMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	omGroupMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	omGroupMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,OmGroup t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	omGroupMapper.updateByCondition(map); 
    }

    public List<OmGroup> query(WhereCondition wc){
    	return omGroupMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return omGroupMapper.count(wc);
    }
   
    public OmGroup loadByGuid(String guid){
    	return omGroupMapper.loadByGuid(guid);
    }
}
