
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmAppGroup;
import org.tis.tools.rservice.om.basic.IOmAppGroupRService;
import org.tis.tools.service.om.OmAppGroupService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 应用工作组列表(OM_APP_GROUP) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "om", version = "1.0", interfaceClass = IOmAppGroupRService.class, timeout = 2000, document = "应用工作组列表的基础远程服务")
public class OmAppGroupRServiceImpl implements IOmAppGroupRService {

	@Autowired
	OmAppGroupService omAppGroupService;

	@Override
	public void insert(OmAppGroup t) {
		omAppGroupService.insert(t);
	}

	@Override
	public void update(OmAppGroup t) {
		omAppGroupService.update(t);
	}

	@Override
	public void updateForce(OmAppGroup t) {
		omAppGroupService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		omAppGroupService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omAppGroupService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmAppGroup t) {
		omAppGroupService.updateByCondition(wc,t);
	}

	@Override
	public List<OmAppGroup> query(WhereCondition wc) {
		return omAppGroupService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omAppGroupService.count(wc);
	}

	@Override
	public OmAppGroup loadByGuid(String guid) {
		return omAppGroupService.loadByGuid(guid);
	}

}
