
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmEmpPosition;
import org.tis.tools.rservice.om.basic.IOmEmpPositionRService;
import org.tis.tools.service.om.OmEmpPositionService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 员工岗位对应关系(OM_EMP_POSITION) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "om", version = "1.0", interfaceClass = IOmEmpPositionRService.class, timeout = 2000, document = "员工岗位对应关系的基础远程服务")
public class OmEmpPositionRServiceImpl implements IOmEmpPositionRService {

	@Autowired
	OmEmpPositionService omEmpPositionService;

	@Override
	public void insert(OmEmpPosition t) {
		omEmpPositionService.insert(t);
	}

	@Override
	public void update(OmEmpPosition t) {
		omEmpPositionService.update(t);
	}

	@Override
	public void updateForce(OmEmpPosition t) {
		omEmpPositionService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		omEmpPositionService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omEmpPositionService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmEmpPosition t) {
		omEmpPositionService.updateByCondition(wc,t);
	}

	@Override
	public List<OmEmpPosition> query(WhereCondition wc) {
		return omEmpPositionService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omEmpPositionService.count(wc);
	}

	@Override
	public OmEmpPosition loadByGuid(String guid) {
		return omEmpPositionService.loadByGuid(guid);
	}

}
