
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmGroupApp;
import org.tis.tools.rservice.om.basic.IOmGroupAppRService;
import org.tis.tools.service.om.OmGroupAppService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 工作组应用列表(OM_GROUP_APP) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "om", version = "1.0", interfaceClass = IOmGroupAppRService.class, timeout = 2000, document = "工作组应用列表的基础远程服务")
public class OmGroupAppRServiceImpl implements IOmGroupAppRService {

	@Autowired
	OmGroupAppService omGroupAppService;

	@Override
	public void insert(OmGroupApp t) {
		omGroupAppService.insert(t);
	}

	@Override
	public void update(OmGroupApp t) {
		omGroupAppService.update(t);
	}

	@Override
	public void updateForce(OmGroupApp t) {
		omGroupAppService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		omGroupAppService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omGroupAppService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmGroupApp t) {
		omGroupAppService.updateByCondition(wc,t);
	}

	@Override
	public List<OmGroupApp> query(WhereCondition wc) {
		return omGroupAppService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omGroupAppService.count(wc);
	}

	@Override
	public OmGroupApp loadByGuid(String guid) {
		return omGroupAppService.loadByGuid(guid);
	}

}
