
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmPositionApp;
import org.tis.tools.rservice.om.basic.IOmPositionAppRService;
import org.tis.tools.service.om.OmPositionAppService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 岗位应用列表(OM_POSITION_APP) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "om", version = "1.0", interfaceClass = IOmPositionAppRService.class, timeout = 2000, document = "岗位应用列表的基础远程服务")
public class OmPositionAppRServiceImpl implements IOmPositionAppRService {

	@Autowired
	OmPositionAppService omPositionAppService;

	@Override
	public void insert(OmPositionApp t) {
		omPositionAppService.insert(t);
	}

	@Override
	public void update(OmPositionApp t) {
		omPositionAppService.update(t);
	}

	@Override
	public void updateForce(OmPositionApp t) {
		omPositionAppService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		omPositionAppService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omPositionAppService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmPositionApp t) {
		omPositionAppService.updateByCondition(wc,t);
	}

	@Override
	public List<OmPositionApp> query(WhereCondition wc) {
		return omPositionAppService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omPositionAppService.count(wc);
	}

	@Override
	public OmPositionApp loadByGuid(String guid) {
		return omPositionAppService.loadByGuid(guid);
	}

}
