/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.om;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtil;

/**
 * 
 * <pre>
 * 人员工作组对应关系
 * 模型文件 ： /Users/megapro/Develop/tis/tools/tools-core/model/ABF-mysql.erm
 * 业务域：om
 * 模型：OM_EMP_GROUP 人员工作组对应关系
 *
 * 定义工作组包含的人员（工作组中有哪些人员）
如：某个项目组有哪些人员
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class OmEmpGroup implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/* OM_EMP_GROUP table's columns definition */
	/** GUID_EMP ：员工GUID<br/><br/> */
	public static final String GUID_EMP = "guid_emp" ; 
	/** GUID_GROUP ：隶属工作组GUID<br/><br/> */
	public static final String GUID_GROUP = "guid_group" ; 
	
	
	/** 字段类型：varchar<br/>字段名：员工GUID<br/>描述： */
	private String guidEmp ;
	
	/** 字段类型：varchar<br/>字段名：隶属工作组GUID<br/>描述： */
	private String guidGroup ;
	
	
	/**
	 * Set the 员工GUID.
	 * 
	 * @param guidEmp
	 *            员工GUID
	 */
	public void setGuidEmp(String guidEmp) {
 		this.guidEmp = guidEmp == null ? null : guidEmp.trim() ;
    }
    
    /**
	 * Get the 员工GUID.
	 * 
	 * @return 员工GUID
	 */
	public String getGuidEmp(){
		return this.guidEmp ;
    }
	
	/**
	 * Set the 隶属工作组GUID.
	 * 
	 * @param guidGroup
	 *            隶属工作组GUID
	 */
	public void setGuidGroup(String guidGroup) {
 		this.guidGroup = guidGroup == null ? null : guidGroup.trim() ;
    }
    
    /**
	 * Get the 隶属工作组GUID.
	 * 
	 * @return 隶属工作组GUID
	 */
	public String getGuidGroup(){
		return this.guidGroup ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ; 
	}
}