/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.log;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.log.LogAbfChangeMapper;
import org.tis.tools.model.po.log.LogAbfChange;


/**
 * 记录日志差异值(LOG_ABF_CHANGE)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class LogAbfChangeService {

	@Autowired
	LogAbfChangeMapper logAbfChangeMapper;
	
    public void insert(LogAbfChange t){
    	logAbfChangeMapper.insert(t);
    }
    
    public void update(LogAbfChange t){
    	logAbfChangeMapper.update(t); 
    }
   
    public void updateForce(LogAbfChange t){
    	logAbfChangeMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	logAbfChangeMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	logAbfChangeMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,LogAbfChange t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	logAbfChangeMapper.updateByCondition(map); 
    }

    public List<LogAbfChange> query(WhereCondition wc){
    	return logAbfChangeMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return logAbfChangeMapper.count(wc);
    }
   
    public LogAbfChange loadByGuid(String guid){
    	return logAbfChangeMapper.loadByGuid(guid);
    }
}
