/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.log;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.log.LogCustomerContactMapper;
import org.tis.tools.model.po.log.LogCustomerContact;


/**
 * 客户接触日志(LOG_CUSTOMER_CONTACT)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class LogCustomerContactService {

	@Autowired
	LogCustomerContactMapper logCustomerContactMapper;
	
    public void insert(LogCustomerContact t){
    	logCustomerContactMapper.insert(t);
    }
    
    public void update(LogCustomerContact t){
    	logCustomerContactMapper.update(t); 
    }
   
    public void updateForce(LogCustomerContact t){
    	logCustomerContactMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	logCustomerContactMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	logCustomerContactMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,LogCustomerContact t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	logCustomerContactMapper.updateByCondition(map); 
    }

    public List<LogCustomerContact> query(WhereCondition wc){
    	return logCustomerContactMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return logCustomerContactMapper.count(wc);
    }
   
    public LogCustomerContact loadByGuid(String guid){
    	return logCustomerContactMapper.loadByGuid(guid);
    }
}
