/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.log;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.log.LogTxTraceMapper;
import org.tis.tools.model.po.log.LogTxTrace;


/**
 * 交易操作日志(LOG_TX_TRACE)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class LogTxTraceService {

	@Autowired
	LogTxTraceMapper logTxTraceMapper;
	
    public void insert(LogTxTrace t){
    	logTxTraceMapper.insert(t);
    }
    
    public void update(LogTxTrace t){
    	logTxTraceMapper.update(t); 
    }
   
    public void updateForce(LogTxTrace t){
    	logTxTraceMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	logTxTraceMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	logTxTraceMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,LogTxTrace t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	logTxTraceMapper.updateByCondition(map); 
    }

    public List<LogTxTrace> query(WhereCondition wc){
    	return logTxTraceMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return logTxTraceMapper.count(wc);
    }
   
    public LogTxTrace loadByGuid(String guid){
    	return logTxTraceMapper.loadByGuid(guid);
    }
}
