/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.sys;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * 
 * <pre>
 * 渠道参数控制表
 * 模型文件 ： /Users/megapro/Develop/tis/tools/tools-core/model/ABF-oracle.erm
 * 业务域：sys
 * 模型：SYS_CHANNEL_CTL 渠道参数控制表
 *
 * 渠道参数控制表
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class SysChannelCtl implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：全局唯一标识符（GUID，Globally Unique Identifier） */
	private String guid ;
	
	/** 字段类型：varchar<br/>字段名：渠道代码<br/>描述：记录接触系统对应的渠道代码 */
	private String chnCode ;
	
	/** 字段类型：varchar<br/>字段名：渠道名称<br/>描述： */
	private String chnName ;
	
	/** 字段类型：varchar<br/>字段名：渠道备注信息<br/>描述： */
	private String chnRemark ;
	
	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
 		this.guid = guid == null ? null : guid.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid(){
		return this.guid ;
    }
	
	/**
	 * Set the 渠道代码.
	 * 
	 * @param chnCode
	 *            渠道代码
	 */
	public void setChnCode(String chnCode) {
 		this.chnCode = chnCode == null ? null : chnCode.trim() ;
    }
    
    /**
	 * Get the 渠道代码.
	 * 
	 * @return 渠道代码
	 */
	public String getChnCode(){
		return this.chnCode ;
    }
	
	/**
	 * Set the 渠道名称.
	 * 
	 * @param chnName
	 *            渠道名称
	 */
	public void setChnName(String chnName) {
 		this.chnName = chnName == null ? null : chnName.trim() ;
    }
    
    /**
	 * Get the 渠道名称.
	 * 
	 * @return 渠道名称
	 */
	public String getChnName(){
		return this.chnName ;
    }
	
	/**
	 * Set the 渠道备注信息.
	 * 
	 * @param chnRemark
	 *            渠道备注信息
	 */
	public void setChnRemark(String chnRemark) {
 		this.chnRemark = chnRemark == null ? null : chnRemark.trim() ;
    }
    
    /**
	 * Get the 渠道备注信息.
	 * 
	 * @return 渠道备注信息
	 */
	public String getChnRemark(){
		return this.chnRemark ;
    }
	
	public String toString(){
		return ToStringBuilder.reflectionToString(this) ; 
	}
}