/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.sys;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.sys.SysTest;

/**
 * 
 * 测试(SYS_TEST)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface SysTestMapper extends BaseMapper<SysTest>{

}
