/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.mapper.ac;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.ac.AcOperatorRole;

/**
 * 
 * 操作员与权限集（角色）对应关系(AC_OPERATOR_ROLE)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface AcOperatorRoleMapper extends BaseMapper<AcOperatorRole>{

}
