
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmAppGroup;

 
/**
 * <pre>
 * 应用工作组列表(OM_APP_GROUP)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IOmAppGroupRService {
	
	/**
	 * 新增应用工作组列表(OM_APP_GROUP)
	 * @param t 新记录
	 */
	public void insert(OmAppGroup t);

	/**
	 * 更新应用工作组列表(OM_APP_GROUP),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(OmAppGroup t);

	/**
	 * 强制更新应用工作组列表(OM_APP_GROUP)
	 * @param t 新值
	 */
	public void updateForce(OmAppGroup t);

	/**
	 * 删除应用工作组列表(OM_APP_GROUP)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除应用工作组列表(OM_APP_GROUP)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新应用工作组列表(OM_APP_GROUP)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, OmAppGroup t);

	/**
	 * 根据条件查询应用工作组列表(OM_APP_GROUP)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<OmAppGroup> query(WhereCondition wc);

	/**
	 * 根据条件统计应用工作组列表(OM_APP_GROUP)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询应用工作组列表(OM_APP_GROUP)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public OmAppGroup loadByGuid(String guid);
}
