
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmAppPosition;

 
/**
 * <pre>
 * 应用岗位列表(OM_APP_POSITION)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IOmAppPositionRService {
	
	/**
	 * 新增应用岗位列表(OM_APP_POSITION)
	 * @param t 新记录
	 */
	public void insert(OmAppPosition t);

	/**
	 * 更新应用岗位列表(OM_APP_POSITION),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(OmAppPosition t);

	/**
	 * 强制更新应用岗位列表(OM_APP_POSITION)
	 * @param t 新值
	 */
	public void updateForce(OmAppPosition t);

	/**
	 * 删除应用岗位列表(OM_APP_POSITION)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除应用岗位列表(OM_APP_POSITION)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新应用岗位列表(OM_APP_POSITION)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, OmAppPosition t);

	/**
	 * 根据条件查询应用岗位列表(OM_APP_POSITION)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<OmAppPosition> query(WhereCondition wc);

	/**
	 * 根据条件统计应用岗位列表(OM_APP_POSITION)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询应用岗位列表(OM_APP_POSITION)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public OmAppPosition loadByGuid(String guid);
}
