
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmEmpGroup;

 
/**
 * <pre>
 * 人员工作组对应关系(OM_EMP_GROUP)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IOmEmpGroupRService {
	
	/**
	 * 新增人员工作组对应关系(OM_EMP_GROUP)
	 * @param t 新记录
	 */
	public void insert(OmEmpGroup t);

	/**
	 * 更新人员工作组对应关系(OM_EMP_GROUP),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(OmEmpGroup t);

	/**
	 * 强制更新人员工作组对应关系(OM_EMP_GROUP)
	 * @param t 新值
	 */
	public void updateForce(OmEmpGroup t);

	/**
	 * 删除人员工作组对应关系(OM_EMP_GROUP)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除人员工作组对应关系(OM_EMP_GROUP)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新人员工作组对应关系(OM_EMP_GROUP)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, OmEmpGroup t);

	/**
	 * 根据条件查询人员工作组对应关系(OM_EMP_GROUP)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<OmEmpGroup> query(WhereCondition wc);

	/**
	 * 根据条件统计人员工作组对应关系(OM_EMP_GROUP)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询人员工作组对应关系(OM_EMP_GROUP)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public OmEmpGroup loadByGuid(String guid);
}
