
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmEmpOrg;

 
/**
 * <pre>
 * 人员隶属机构关系表(OM_EMP_ORG)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IOmEmpOrgRService {
	
	/**
	 * 新增人员隶属机构关系表(OM_EMP_ORG)
	 * @param t 新记录
	 */
	public void insert(OmEmpOrg t);

	/**
	 * 更新人员隶属机构关系表(OM_EMP_ORG),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(OmEmpOrg t);

	/**
	 * 强制更新人员隶属机构关系表(OM_EMP_ORG)
	 * @param t 新值
	 */
	public void updateForce(OmEmpOrg t);

	/**
	 * 删除人员隶属机构关系表(OM_EMP_ORG)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除人员隶属机构关系表(OM_EMP_ORG)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新人员隶属机构关系表(OM_EMP_ORG)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, OmEmpOrg t);

	/**
	 * 根据条件查询人员隶属机构关系表(OM_EMP_ORG)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<OmEmpOrg> query(WhereCondition wc);

	/**
	 * 根据条件统计人员隶属机构关系表(OM_EMP_ORG)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询人员隶属机构关系表(OM_EMP_ORG)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public OmEmpOrg loadByGuid(String guid);
}
