
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmPosition;

 
/**
 * <pre>
 * 岗位/职位(OM_POSITION)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IOmPositionRService {
	
	/**
	 * 新增岗位/职位(OM_POSITION)
	 * @param t 新记录
	 */
	public void insert(OmPosition t);

	/**
	 * 更新岗位/职位(OM_POSITION),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(OmPosition t);

	/**
	 * 强制更新岗位/职位(OM_POSITION)
	 * @param t 新值
	 */
	public void updateForce(OmPosition t);

	/**
	 * 删除岗位/职位(OM_POSITION)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除岗位/职位(OM_POSITION)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新岗位/职位(OM_POSITION)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, OmPosition t);

	/**
	 * 根据条件查询岗位/职位(OM_POSITION)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<OmPosition> query(WhereCondition wc);

	/**
	 * 根据条件统计岗位/职位(OM_POSITION)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询岗位/职位(OM_POSITION)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public OmPosition loadByGuid(String guid);
}
