/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.mapper.om;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.om.OmAppGroup;

/**
 * 
 * 应用工作组列表(OM_APP_GROUP)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface OmAppGroupMapper extends BaseMapper<OmAppGroup>{

}
