/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.mapper.om;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.om.OmEmployee;

/**
 * 
 * 人员(OM_EMPLOYEE)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface OmEmployeeMapper extends BaseMapper<OmEmployee>{

}
