/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.mapper.jnl;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.jnl.JnlTransFeature;

/**
 * 
 * 交易业务要素(JNL_TRANS_FEATURE)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface JnlTransFeatureMapper extends BaseMapper<JnlTransFeature>{

}
