/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.mapper.jnl;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.jnl.JnlTransPrinted;

/**
 * 
 * 交易输出凭证流水(JNL_TRANS_PRINTED)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface JnlTransPrintedMapper extends BaseMapper<JnlTransPrinted>{

}
