/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.mapper.jnl;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.jnl.TbJnlReservation;

 /**
 * <pre>
 * auto generated by mvn bronsp:gen-dao , don't change</br>
 * 预约流水的DAO
 * 模型：预约流水 tb_jnl_reservation
 * 描述：预约流水表
 * 业务域：jnl
 * 定义文件：/Users/megapro/Develop/tis/tools/tools-core/model/model-jnl.xml
 * </pre>
 */
public interface TbJnlReservationMapper extends BaseMapper<TbJnlReservation>{

}
