SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS SYS_CHANNEL_CTL;
DROP TABLE IF EXISTS SYS_ERR_CODE;
DROP TABLE IF EXISTS SYS_TEST;
DROP TABLE IF EXISTS SYS_UNIQUE;




/* Create Tables */

CREATE TABLE SYS_CHANNEL_CTL
(
	-- 全局唯一标识符（GUID，Globally Unique Identifier）
	GUID VARCHAR(128) NOT NULL COMMENT '全局唯一标识符（GUID，Globally Unique Identifier）',
	-- 记录接触系统对应的渠道代码
	CHN_CODE VARCHAR(128) NOT NULL COMMENT '记录接触系统对应的渠道代码',
	CHN_NAME VARCHAR(256) NOT NULL,
	CHN_REMARK VARCHAR(1024),
	PRIMARY KEY (GUID),
	UNIQUE (GUID),
	UNIQUE (CHN_CODE)
);


-- 记录系统中的各种错误代码信息，如系统抛出的错误信息，交易执行时的错误码等
CREATE TABLE SYS_ERR_CODE
(
	-- 全局唯一标识符（GUID，Globally Unique Identifier）
	GUID VARCHAR(128) NOT NULL COMMENT '全局唯一标识符（GUID，Globally Unique Identifier）',
	-- 见业务字典： DICT_ERRCODE_KIND
	-- SYS 系统错误码
	-- TRANS 交易错误码
	-- 
	ERRCODE_KIND CHAR(8) COMMENT '见业务字典： DICT_ERRCODE_KIND
SYS 系统错误码
TRANS 交易错误码
',
	ERR_CODE VARCHAR(32),
	ERR_MSG VARCHAR(256),
	PRIMARY KEY (GUID),
	UNIQUE (GUID)
) COMMENT = '记录系统中的各种错误代码信息，如系统抛出的错误信息，交易执行时的错误码等';


CREATE TABLE SYS_TEST
(
	TEST_BIGINT BIGINT,
	TEST_GIBINTN BIGINT(8),
	TEST_CHAR CHAR,
	TEST_CHARN CHAR(16),
	TEST_DATE DATE,
	TEST_DATETIME DATETIME,
	TEST_DECIMAL DECIMAL,
	TEST_DECIMALP DECIMAL(12),
	TEST_DECIMALPS DECIMAL(12,4),
	TEST_DOUBLE DOUBLE,
	TEST_DOUBLEMD DOUBLE(10,4),
	TEST_FLOAT FLOAT,
	TEST_FLOATP FLOAT(10),
	TEST_FLOATMD FLOAT(10,4),
	TEST_INT INT,
	TEST_INTN INT(12),
	TEST_TIME TIME,
	TEST_TIMESTAMP TIMESTAMP,
	TEST_VARCHARN VARCHAR(32),
	TSET_TEXT TEXT,
	TEST_BLOB BLOB
);


CREATE TABLE SYS_UNIQUE
(
	-- 全局唯一标识符（GUID，Globally Unique Identifier）
	GUID VARCHAR(128) NOT NULL COMMENT '全局唯一标识符（GUID，Globally Unique Identifier）',
	UNIQUE_KEY VARCHAR(128) NOT NULL,
	-- 顺序增加的数字
	SEQ_NO BIGINT NOT NULL COMMENT '顺序增加的数字',
	PRIMARY KEY (GUID),
	UNIQUE (GUID),
	UNIQUE (UNIQUE_KEY)
);



