
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcApp;
import org.tis.tools.rservice.ac.basic.IAcAppRService;
import org.tis.tools.service.ac.AcAppService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 应用系统(AC_APP) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcAppRService.class, timeout = 2000, document = "应用系统的基础远程服务")
public class AcAppRServiceImpl implements IAcAppRService {

	@Autowired
	AcAppService acAppService;

	@Override
	public void insert(AcApp t) {
		acAppService.insert(t);
	}

	@Override
	public void update(AcApp t) {
		acAppService.update(t);
	}

	@Override
	public void updateForce(AcApp t) {
		acAppService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acAppService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acAppService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcApp t) {
		acAppService.updateByCondition(wc,t);
	}

	@Override
	public List<AcApp> query(WhereCondition wc) {
		return acAppService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acAppService.count(wc);
	}

	@Override
	public AcApp loadByGuid(String guid) {
		return acAppService.loadByGuid(guid);
	}

}
