
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcBhvDef;
import org.tis.tools.rservice.ac.basic.IAcBhvDefRService;
import org.tis.tools.service.ac.AcBhvDefService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 功能操作行为定义(AC_BHV_DEF) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcBhvDefRService.class, timeout = 2000, document = "功能操作行为定义的基础远程服务")
public class AcBhvDefRServiceImpl implements IAcBhvDefRService {

	@Autowired
	AcBhvDefService acBhvDefService;

	@Override
	public void insert(AcBhvDef t) {
		acBhvDefService.insert(t);
	}

	@Override
	public void update(AcBhvDef t) {
		acBhvDefService.update(t);
	}

	@Override
	public void updateForce(AcBhvDef t) {
		acBhvDefService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acBhvDefService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acBhvDefService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcBhvDef t) {
		acBhvDefService.updateByCondition(wc,t);
	}

	@Override
	public List<AcBhvDef> query(WhereCondition wc) {
		return acBhvDefService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acBhvDefService.count(wc);
	}

	@Override
	public AcBhvDef loadByGuid(String guid) {
		return acBhvDefService.loadByGuid(guid);
	}

}
