
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcEntity;
import org.tis.tools.rservice.ac.basic.IAcEntityRService;
import org.tis.tools.service.ac.AcEntityService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 实体(AC_ENTITY) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcEntityRService.class, timeout = 2000, document = "实体的基础远程服务")
public class AcEntityRServiceImpl implements IAcEntityRService {

	@Autowired
	AcEntityService acEntityService;

	@Override
	public void insert(AcEntity t) {
		acEntityService.insert(t);
	}

	@Override
	public void update(AcEntity t) {
		acEntityService.update(t);
	}

	@Override
	public void updateForce(AcEntity t) {
		acEntityService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acEntityService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acEntityService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcEntity t) {
		acEntityService.updateByCondition(wc,t);
	}

	@Override
	public List<AcEntity> query(WhereCondition wc) {
		return acEntityService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acEntityService.count(wc);
	}

	@Override
	public AcEntity loadByGuid(String guid) {
		return acEntityService.loadByGuid(guid);
	}

}
