
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcFuncBehavior;
import org.tis.tools.rservice.ac.basic.IAcFuncBehaviorRService;
import org.tis.tools.service.ac.AcFuncBehaviorService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 功能操作行为(AC_FUNC_BEHAVIOR) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcFuncBehaviorRService.class, timeout = 2000, document = "功能操作行为的基础远程服务")
public class AcFuncBehaviorRServiceImpl implements IAcFuncBehaviorRService {

	@Autowired
	AcFuncBehaviorService acFuncBehaviorService;

	@Override
	public void insert(AcFuncBehavior t) {
		acFuncBehaviorService.insert(t);
	}

	@Override
	public void update(AcFuncBehavior t) {
		acFuncBehaviorService.update(t);
	}

	@Override
	public void updateForce(AcFuncBehavior t) {
		acFuncBehaviorService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acFuncBehaviorService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acFuncBehaviorService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcFuncBehavior t) {
		acFuncBehaviorService.updateByCondition(wc,t);
	}

	@Override
	public List<AcFuncBehavior> query(WhereCondition wc) {
		return acFuncBehaviorService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acFuncBehaviorService.count(wc);
	}

	@Override
	public AcFuncBehavior loadByGuid(String guid) {
		return acFuncBehaviorService.loadByGuid(guid);
	}

}
