
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcFuncBhvtype;
import org.tis.tools.rservice.ac.basic.IAcFuncBhvtypeRService;
import org.tis.tools.service.ac.AcFuncBhvtypeService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 功能行为类型表(AC_FUNC_BHVTYPE) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcFuncBhvtypeRService.class, timeout = 2000, document = "功能行为类型表的基础远程服务")
public class AcFuncBhvtypeRServiceImpl implements IAcFuncBhvtypeRService {

	@Autowired
	AcFuncBhvtypeService acFuncBhvtypeService;

	@Override
	public void insert(AcFuncBhvtype t) {
		acFuncBhvtypeService.insert(t);
	}

	@Override
	public void update(AcFuncBhvtype t) {
		acFuncBhvtypeService.update(t);
	}

	@Override
	public void updateForce(AcFuncBhvtype t) {
		acFuncBhvtypeService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acFuncBhvtypeService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acFuncBhvtypeService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcFuncBhvtype t) {
		acFuncBhvtypeService.updateByCondition(wc,t);
	}

	@Override
	public List<AcFuncBhvtype> query(WhereCondition wc) {
		return acFuncBhvtypeService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acFuncBhvtypeService.count(wc);
	}

	@Override
	public AcFuncBhvtype loadByGuid(String guid) {
		return acFuncBhvtypeService.loadByGuid(guid);
	}

}
