
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcFuncBhv;
import org.tis.tools.rservice.ac.basic.IAcFuncBhvRService;
import org.tis.tools.service.ac.AcFuncBhvService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 功能操作行为(AC_FUNC_BHV) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcFuncBhvRService.class, timeout = 2000, document = "功能操作行为的基础远程服务")
public class AcFuncBhvRServiceImpl implements IAcFuncBhvRService {

	@Autowired
	AcFuncBhvService acFuncBhvService;

	@Override
	public void insert(AcFuncBhv t) {
		acFuncBhvService.insert(t);
	}

	@Override
	public void update(AcFuncBhv t) {
		acFuncBhvService.update(t);
	}

	@Override
	public void updateForce(AcFuncBhv t) {
		acFuncBhvService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acFuncBhvService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acFuncBhvService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcFuncBhv t) {
		acFuncBhvService.updateByCondition(wc,t);
	}

	@Override
	public List<AcFuncBhv> query(WhereCondition wc) {
		return acFuncBhvService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acFuncBhvService.count(wc);
	}

	@Override
	public AcFuncBhv loadByGuid(String guid) {
		return acFuncBhvService.loadByGuid(guid);
	}

}
