
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcMenu;
import org.tis.tools.rservice.ac.basic.IAcMenuRService;
import org.tis.tools.service.ac.AcMenuService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 菜单(AC_MENU) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcMenuRService.class, timeout = 2000, document = "菜单的基础远程服务")
public class AcMenuRServiceImpl implements IAcMenuRService {

	@Autowired
	AcMenuService acMenuService;

	@Override
	public void insert(AcMenu t) {
		acMenuService.insert(t);
	}

	@Override
	public void update(AcMenu t) {
		acMenuService.update(t);
	}

	@Override
	public void updateForce(AcMenu t) {
		acMenuService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acMenuService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acMenuService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcMenu t) {
		acMenuService.updateByCondition(wc,t);
	}

	@Override
	public List<AcMenu> query(WhereCondition wc) {
		return acMenuService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acMenuService.count(wc);
	}

	@Override
	public AcMenu loadByGuid(String guid) {
		return acMenuService.loadByGuid(guid);
	}

}
