
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcOperatorBhv;
import org.tis.tools.rservice.ac.basic.IAcOperatorBhvRService;
import org.tis.tools.service.ac.AcOperatorBhvService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 操作员特殊功能行为配置(AC_OPERATOR_BHV) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcOperatorBhvRService.class, timeout = 2000, document = "操作员特殊功能行为配置的基础远程服务")
public class AcOperatorBhvRServiceImpl implements IAcOperatorBhvRService {

	@Autowired
	AcOperatorBhvService acOperatorBhvService;

	@Override
	public void insert(AcOperatorBhv t) {
		acOperatorBhvService.insert(t);
	}

	@Override
	public void update(AcOperatorBhv t) {
		acOperatorBhvService.update(t);
	}

	@Override
	public void updateForce(AcOperatorBhv t) {
		acOperatorBhvService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acOperatorBhvService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acOperatorBhvService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcOperatorBhv t) {
		acOperatorBhvService.updateByCondition(wc,t);
	}

	@Override
	public List<AcOperatorBhv> query(WhereCondition wc) {
		return acOperatorBhvService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acOperatorBhvService.count(wc);
	}

	@Override
	public AcOperatorBhv loadByGuid(String guid) {
		return acOperatorBhvService.loadByGuid(guid);
	}

}
