
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcRoleBhv;
import org.tis.tools.rservice.ac.basic.IAcRoleBhvRService;
import org.tis.tools.service.ac.AcRoleBhvService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 权限集(角色)功能行为对应关系(AC_ROLE_BHV) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcRoleBhvRService.class, timeout = 2000, document = "权限集(角色)功能行为对应关系的基础远程服务")
public class AcRoleBhvRServiceImpl implements IAcRoleBhvRService {

	@Autowired
	AcRoleBhvService acRoleBhvService;

	@Override
	public void insert(AcRoleBhv t) {
		acRoleBhvService.insert(t);
	}

	@Override
	public void update(AcRoleBhv t) {
		acRoleBhvService.update(t);
	}

	@Override
	public void updateForce(AcRoleBhv t) {
		acRoleBhvService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acRoleBhvService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acRoleBhvService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcRoleBhv t) {
		acRoleBhvService.updateByCondition(wc,t);
	}

	@Override
	public List<AcRoleBhv> query(WhereCondition wc) {
		return acRoleBhvService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acRoleBhvService.count(wc);
	}

	@Override
	public AcRoleBhv loadByGuid(String guid) {
		return acRoleBhvService.loadByGuid(guid);
	}

}
