/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.jnl;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * 
 * <pre>
 * 营销流水
 * 模型文件 ： /Users/megapro/Develop/tis/tools/tools-core/model/JNLoracle.erm
 * 业务域：jnl
 * 模型：JNL_PROMOTING 营销流水
 *
 * 营销流水
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class JnlPromoting implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：全局唯一标识符（GUID，Globally Unique Identifier） */
	private String guid ;
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：关联服务流水 */
	private String guidCustService ;
	
	/** 字段类型：varchar<br/>字段名：服务流水号<br/>描述： */
	private String serviceSno ;
	
	/** 字段类型：varchar<br/>字段名：营销信息来源<br/>描述：标识本营销信息来自何处（可能是应用系统、或自动程序等等...），见业务字典： DICT_PROMOTING_ORIGIN */
	private String promotingOrigin ;
	
	/** 字段类型：varchar<br/>字段名：营销业务类型<br/>描述：见业务字典： DICT_PROMOTING_BIZ_TYPE */
	private String promotingBizType ;
	
	/** 字段类型：varchar<br/>字段名：营销标题<br/>描述：本营销内容的标题信息，有字数限制200个汉字以内 */
	private String promotingTitle ;
	
	/** 字段类型：text<br/>字段名：营销信息<br/>描述： */
	private String promotingInfo ;
	
	/** 字段类型：varchar<br/>字段名：营销行为<br/>描述：本次营销的行为，通常是按钮事件，系统根据本字段进行营销按钮呈现 */
	private String promotingAction ;
	
	/** 字段类型：varchar<br/>字段名：柜员代码<br/>描述：本次接触活动的柜员 */
	private String tellerNo ;
	
	/** 字段类型：varchar<br/>字段名：机构编码<br/>描述： */
	private String instno ;
	
	/** 字段类型：char<br/>字段名：营销日期<br/>描述： */
	private String promotingDate ;
	
	/** 字段类型：varchar<br/>字段名：营销时间<br/>描述：yyyyMMddHHmmSSsss */
	private String promotingTime ;
	
	/** 字段类型：varchar<br/>字段名：营销反馈<br/>描述：见业务字典：DICT_PROMOTING_FEEDBACK */
	private String promotingFeedback ;
	
	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
 		this.guid = guid == null ? null : guid.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid(){
		return this.guid ;
    }
	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guidCustService
	 *            数据主键
	 */
	public void setGuidCustService(String guidCustService) {
 		this.guidCustService = guidCustService == null ? null : guidCustService.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuidCustService(){
		return this.guidCustService ;
    }
	
	/**
	 * Set the 服务流水号.
	 * 
	 * @param serviceSno
	 *            服务流水号
	 */
	public void setServiceSno(String serviceSno) {
 		this.serviceSno = serviceSno == null ? null : serviceSno.trim() ;
    }
    
    /**
	 * Get the 服务流水号.
	 * 
	 * @return 服务流水号
	 */
	public String getServiceSno(){
		return this.serviceSno ;
    }
	
	/**
	 * Set the 营销信息来源.
	 * 
	 * @param promotingOrigin
	 *            营销信息来源
	 */
	public void setPromotingOrigin(String promotingOrigin) {
 		this.promotingOrigin = promotingOrigin == null ? null : promotingOrigin.trim() ;
    }
    
    /**
	 * Get the 营销信息来源.
	 * 
	 * @return 营销信息来源
	 */
	public String getPromotingOrigin(){
		return this.promotingOrigin ;
    }
	
	/**
	 * Set the 营销业务类型.
	 * 
	 * @param promotingBizType
	 *            营销业务类型
	 */
	public void setPromotingBizType(String promotingBizType) {
 		this.promotingBizType = promotingBizType == null ? null : promotingBizType.trim() ;
    }
    
    /**
	 * Get the 营销业务类型.
	 * 
	 * @return 营销业务类型
	 */
	public String getPromotingBizType(){
		return this.promotingBizType ;
    }
	
	/**
	 * Set the 营销标题.
	 * 
	 * @param promotingTitle
	 *            营销标题
	 */
	public void setPromotingTitle(String promotingTitle) {
 		this.promotingTitle = promotingTitle == null ? null : promotingTitle.trim() ;
    }
    
    /**
	 * Get the 营销标题.
	 * 
	 * @return 营销标题
	 */
	public String getPromotingTitle(){
		return this.promotingTitle ;
    }
	
	/**
	 * Set the 营销信息.
	 * 
	 * @param promotingInfo
	 *            营销信息
	 */
	public void setPromotingInfo(String promotingInfo) {
 		this.promotingInfo = promotingInfo == null ? null : promotingInfo.trim() ;
    }
    
    /**
	 * Get the 营销信息.
	 * 
	 * @return 营销信息
	 */
	public String getPromotingInfo(){
		return this.promotingInfo ;
    }
	
	/**
	 * Set the 营销行为.
	 * 
	 * @param promotingAction
	 *            营销行为
	 */
	public void setPromotingAction(String promotingAction) {
 		this.promotingAction = promotingAction == null ? null : promotingAction.trim() ;
    }
    
    /**
	 * Get the 营销行为.
	 * 
	 * @return 营销行为
	 */
	public String getPromotingAction(){
		return this.promotingAction ;
    }
	
	/**
	 * Set the 柜员代码.
	 * 
	 * @param tellerNo
	 *            柜员代码
	 */
	public void setTellerNo(String tellerNo) {
 		this.tellerNo = tellerNo == null ? null : tellerNo.trim() ;
    }
    
    /**
	 * Get the 柜员代码.
	 * 
	 * @return 柜员代码
	 */
	public String getTellerNo(){
		return this.tellerNo ;
    }
	
	/**
	 * Set the 机构编码.
	 * 
	 * @param instno
	 *            机构编码
	 */
	public void setInstno(String instno) {
 		this.instno = instno == null ? null : instno.trim() ;
    }
    
    /**
	 * Get the 机构编码.
	 * 
	 * @return 机构编码
	 */
	public String getInstno(){
		return this.instno ;
    }
	
	/**
	 * Set the 营销日期.
	 * 
	 * @param promotingDate
	 *            营销日期
	 */
	public void setPromotingDate(String promotingDate) {
 		this.promotingDate = promotingDate == null ? null : promotingDate.trim() ;
    }
    
    /**
	 * Get the 营销日期.
	 * 
	 * @return 营销日期
	 */
	public String getPromotingDate(){
		return this.promotingDate ;
    }
	
	/**
	 * Set the 营销时间.
	 * 
	 * @param promotingTime
	 *            营销时间
	 */
	public void setPromotingTime(String promotingTime) {
 		this.promotingTime = promotingTime == null ? null : promotingTime.trim() ;
    }
    
    /**
	 * Get the 营销时间.
	 * 
	 * @return 营销时间
	 */
	public String getPromotingTime(){
		return this.promotingTime ;
    }
	
	/**
	 * Set the 营销反馈.
	 * 
	 * @param promotingFeedback
	 *            营销反馈
	 */
	public void setPromotingFeedback(String promotingFeedback) {
 		this.promotingFeedback = promotingFeedback == null ? null : promotingFeedback.trim() ;
    }
    
    /**
	 * Get the 营销反馈.
	 * 
	 * @return 营销反馈
	 */
	public String getPromotingFeedback(){
		return this.promotingFeedback ;
    }
	
	public String toString(){
		return ToStringBuilder.reflectionToString(this) ; 
	}
}