/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.jnl;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * 
 * <pre>
 * 交易业务要素
 * 模型文件 ： /Users/megapro/Develop/tis/tools/tools-core/model/JNL-oracle.erm
 * 业务域：jnl
 * 模型：JNL_TRANS_FEATURE 交易业务要素
 *
 * 直接记录交易中某个字段数据信息
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class JnlTransFeature implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：全局唯一标识符（GUID，Globally Unique Identifier） */
	private String guid ;
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：关联交易流水记录 */
	private String guidTrans ;
	
	/** 字段类型：varchar<br/>字段名：交易流水号<br/>描述： */
	private String transSno ;
	
	/** 字段类型：varchar<br/>字段名：交易要素<br/>描述：对应交易界面上的字段代码 */
	private String transField ;
	
	/** 字段类型：varchar<br/>字段名：交易数据<br/>描述：交易当时的数据信息，所有信息转换为String的形式存储 */
	private String transData ;
	
	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
 		this.guid = guid == null ? null : guid.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid(){
		return this.guid ;
    }
	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guidTrans
	 *            数据主键
	 */
	public void setGuidTrans(String guidTrans) {
 		this.guidTrans = guidTrans == null ? null : guidTrans.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuidTrans(){
		return this.guidTrans ;
    }
	
	/**
	 * Set the 交易流水号.
	 * 
	 * @param transSno
	 *            交易流水号
	 */
	public void setTransSno(String transSno) {
 		this.transSno = transSno == null ? null : transSno.trim() ;
    }
    
    /**
	 * Get the 交易流水号.
	 * 
	 * @return 交易流水号
	 */
	public String getTransSno(){
		return this.transSno ;
    }
	
	/**
	 * Set the 交易要素.
	 * 
	 * @param transField
	 *            交易要素
	 */
	public void setTransField(String transField) {
 		this.transField = transField == null ? null : transField.trim() ;
    }
    
    /**
	 * Get the 交易要素.
	 * 
	 * @return 交易要素
	 */
	public String getTransField(){
		return this.transField ;
    }
	
	/**
	 * Set the 交易数据.
	 * 
	 * @param transData
	 *            交易数据
	 */
	public void setTransData(String transData) {
 		this.transData = transData == null ? null : transData.trim() ;
    }
    
    /**
	 * Get the 交易数据.
	 * 
	 * @return 交易数据
	 */
	public String getTransData(){
		return this.transData ;
    }
	
	public String toString(){
		return ToStringBuilder.reflectionToString(this) ; 
	}
}