/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.ac;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtils;

/**
 * 
 * <pre>
 * 操作员特殊权限配置
 * 模型文件 ： /Users/megapro/Develop/tis/tools/tools-core/model/ABF-mysql.erm
 * 业务域：ac
 * 模型：AC_OPERATOR_FUNC 操作员特殊权限配置
 *
 * 针对人员配置的特殊权限，如特别开通的功能，或者特别禁止的功能
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class AcOperatorFunc implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/* AC_OPERATOR_FUNC table's columns definition */
	/** GUID_OPERATOR ：数据主键<br/><br/> */
	public static final String GUID_OPERATOR = "guid_operator" ; 
	/** GUID_FUNC ：数据主键<br/><br/> */
	public static final String GUID_FUNC = "guid_func" ; 
	/** AUTH_TYPE ：授权标志<br/><br/>取值来自业务菜单：DICT_AC_AUTHTYPE 如：特别禁止、特别允许 */
	public static final String AUTH_TYPE = "auth_type" ; 
	/** START_DATE ：有效开始日期<br/><br/> */
	public static final String START_DATE = "start_date" ; 
	/** END_DATE ：有效截至日期<br/><br/> */
	public static final String END_DATE = "end_date" ; 
	/** GUID_APP ：应用GUID<br/><br/>冗余字段 */
	public static final String GUID_APP = "guid_app" ; 
	/** GUID_FUNCGROUP ：功能组GUID<br/><br/>冗余字段 */
	public static final String GUID_FUNCGROUP = "guid_funcgroup" ; 
	
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述： */
	private String guidOperator ;
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述： */
	private String guidFunc ;
	
	/** 字段类型：varchar<br/>字段名：授权标志<br/>描述：取值来自业务菜单：DICT_AC_AUTHTYPE 如：特别禁止、特别允许 */
	private String authType ;
	
	/** 字段类型：date<br/>字段名：有效开始日期<br/>描述： */
	private Date startDate ;
	
	/** 字段类型：date<br/>字段名：有效截至日期<br/>描述： */
	private Date endDate ;
	
	/** 字段类型：varchar<br/>字段名：应用GUID<br/>描述：冗余字段 */
	private String guidApp ;
	
	/** 字段类型：varchar<br/>字段名：功能组GUID<br/>描述：冗余字段 */
	private String guidFuncgroup ;
	
	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guidOperator
	 *            数据主键
	 */
	public void setGuidOperator(String guidOperator) {
 		this.guidOperator = guidOperator == null ? null : guidOperator.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuidOperator(){
		return this.guidOperator ;
    }
	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guidFunc
	 *            数据主键
	 */
	public void setGuidFunc(String guidFunc) {
 		this.guidFunc = guidFunc == null ? null : guidFunc.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuidFunc(){
		return this.guidFunc ;
    }
	
	/**
	 * Set the 授权标志.
	 * 
	 * @param authType
	 *            授权标志
	 */
	public void setAuthType(String authType) {
 		this.authType = authType == null ? null : authType.trim() ;
    }
    
    /**
	 * Get the 授权标志.
	 * 
	 * @return 授权标志
	 */
	public String getAuthType(){
		return this.authType ;
    }
	
	/**
	 * Set the 有效开始日期.
	 * 
	 * @param startDate
	 *            有效开始日期
	 */
	public void setStartDate(Date startDate) {
 		this.startDate = startDate ;
    }
    
    /**
	 * Get the 有效开始日期.
	 * 
	 * @return 有效开始日期
	 */
	public Date getStartDate(){
		return this.startDate ;
    }
	
	/**
	 * Set the 有效截至日期.
	 * 
	 * @param endDate
	 *            有效截至日期
	 */
	public void setEndDate(Date endDate) {
 		this.endDate = endDate ;
    }
    
    /**
	 * Get the 有效截至日期.
	 * 
	 * @return 有效截至日期
	 */
	public Date getEndDate(){
		return this.endDate ;
    }
	
	/**
	 * Set the 应用GUID.
	 * 
	 * @param guidApp
	 *            应用GUID
	 */
	public void setGuidApp(String guidApp) {
 		this.guidApp = guidApp == null ? null : guidApp.trim() ;
    }
    
    /**
	 * Get the 应用GUID.
	 * 
	 * @return 应用GUID
	 */
	public String getGuidApp(){
		return this.guidApp ;
    }
	
	/**
	 * Set the 功能组GUID.
	 * 
	 * @param guidFuncgroup
	 *            功能组GUID
	 */
	public void setGuidFuncgroup(String guidFuncgroup) {
 		this.guidFuncgroup = guidFuncgroup == null ? null : guidFuncgroup.trim() ;
    }
    
    /**
	 * Get the 功能组GUID.
	 * 
	 * @return 功能组GUID
	 */
	public String getGuidFuncgroup(){
		return this.guidFuncgroup ;
    }
	
	public String toString(){
		return StringUtils.toString(this) ; 
	}
}