/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.ac;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtil;

/**
 * 
 * <pre>
 * 组织对象与角色对应关系
 * 模型文件 ： /Users/megapro/Develop/tis/tools/tools-core/model/ABF-mysql.erm
 * 业务域：ac
 * 模型：AC_PARTY_ROLE 组织对象与角色对应关系
 *
 * 设置机构、工作组、岗位、职务等组织对象与角色之间的对应关系
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class AcPartyRole implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/* AC_PARTY_ROLE table's columns definition */
	/** PARTY_TYPE ：组织对象类型<br/><br/>取值范围，见业务字典 DICT_OM_PARTYTYPE 如：机构、工作组、岗位、职务 */
	public static final String PARTY_TYPE = "party_type" ; 
	/** GUID_PARTY ：组织对象GUID<br/><br/>根据组织类型存储对应组织的GUID */
	public static final String GUID_PARTY = "guid_party" ; 
	/** GUID_ROLE ：拥有角色GUID<br/><br/> */
	public static final String GUID_ROLE = "guid_role" ; 
	
	
	/** 字段类型：varchar<br/>字段名：组织对象类型<br/>描述：取值范围，见业务字典 DICT_OM_PARTYTYPE 如：机构、工作组、岗位、职务 */
	private String partyType ;
	
	/** 字段类型：varchar<br/>字段名：组织对象GUID<br/>描述：根据组织类型存储对应组织的GUID */
	private String guidParty ;
	
	/** 字段类型：varchar<br/>字段名：拥有角色GUID<br/>描述： */
	private String guidRole ;
	
	
	/**
	 * Set the 组织对象类型.
	 * 
	 * @param partyType
	 *            组织对象类型
	 */
	public void setPartyType(String partyType) {
 		this.partyType = partyType == null ? null : partyType.trim() ;
    }
    
    /**
	 * Get the 组织对象类型.
	 * 
	 * @return 组织对象类型
	 */
	public String getPartyType(){
		return this.partyType ;
    }
	
	/**
	 * Set the 组织对象GUID.
	 * 
	 * @param guidParty
	 *            组织对象GUID
	 */
	public void setGuidParty(String guidParty) {
 		this.guidParty = guidParty == null ? null : guidParty.trim() ;
    }
    
    /**
	 * Get the 组织对象GUID.
	 * 
	 * @return 组织对象GUID
	 */
	public String getGuidParty(){
		return this.guidParty ;
    }
	
	/**
	 * Set the 拥有角色GUID.
	 * 
	 * @param guidRole
	 *            拥有角色GUID
	 */
	public void setGuidRole(String guidRole) {
 		this.guidRole = guidRole == null ? null : guidRole.trim() ;
    }
    
    /**
	 * Get the 拥有角色GUID.
	 * 
	 * @return 拥有角色GUID
	 */
	public String getGuidRole(){
		return this.guidRole ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ; 
	}
}