/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.jnl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.jnl.JnlCustServiceMapper;
import org.tis.tools.model.po.jnl.JnlCustService;


/**
 * 客户服务流水(JNL_CUST_SERVICE)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class JnlCustServiceService {

	@Autowired
	JnlCustServiceMapper jnlCustServiceMapper;
	
    public void insert(JnlCustService t){
    	jnlCustServiceMapper.insert(t);
    }
    
    public void update(JnlCustService t){
    	jnlCustServiceMapper.update(t); 
    }
   
    public void updateForce(JnlCustService t){
    	jnlCustServiceMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	jnlCustServiceMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	jnlCustServiceMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,JnlCustService t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	jnlCustServiceMapper.updateByCondition(map); 
    }

    public List<JnlCustService> query(WhereCondition wc){
    	return jnlCustServiceMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return jnlCustServiceMapper.count(wc);
    }
   
    public JnlCustService loadByGuid(String guid){
    	return jnlCustServiceMapper.loadByGuid(guid);
    }
}
