/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.jnl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.mapper.jnl.JnlEnqueueMapper;
import org.tis.tools.model.po.jnl.JnlEnqueue;


/**
 * 排队流水(JNL_ENQUEUE)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class JnlEnqueueService {

	@Autowired
	JnlEnqueueMapper jnlEnqueueMapper;
	
    public void insert(JnlEnqueue t){
    	jnlEnqueueMapper.insert(t);
    }
    
    public void update(JnlEnqueue t){
    	jnlEnqueueMapper.update(t); 
    }
   
    public void updateForce(JnlEnqueue t){
    	jnlEnqueueMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	jnlEnqueueMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	jnlEnqueueMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,JnlEnqueue t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	jnlEnqueueMapper.updateByCondition(map); 
    }

    public List<JnlEnqueue> query(WhereCondition wc){
    	return jnlEnqueueMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return jnlEnqueueMapper.count(wc);
    }
   
    public JnlEnqueue loadByGuid(String guid){
    	return jnlEnqueueMapper.loadByGuid(guid);
    }
}
