/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.jnl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.mapper.jnl.JnlPrefillMapper;
import org.tis.tools.model.po.jnl.JnlPrefill;


/**
 * 预填流水(JNL_PREFILL)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class JnlPrefillService {

	@Autowired
	JnlPrefillMapper jnlPrefillMapper;
	
    public void insert(JnlPrefill t){
    	jnlPrefillMapper.insert(t);
    }
    
    public void update(JnlPrefill t){
    	jnlPrefillMapper.update(t); 
    }
   
    public void updateForce(JnlPrefill t){
    	jnlPrefillMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	jnlPrefillMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	jnlPrefillMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,JnlPrefill t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	jnlPrefillMapper.updateByCondition(map); 
    }

    public List<JnlPrefill> query(WhereCondition wc){
    	return jnlPrefillMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return jnlPrefillMapper.count(wc);
    }
   
    public JnlPrefill loadByGuid(String guid){
    	return jnlPrefillMapper.loadByGuid(guid);
    }
}
