
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcRoleEntityfield;

 
/**
 * <pre>
 * 角色与实体属性关系(AC_ROLE_ENTITYFIELD)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IAcRoleEntityfieldRService {
	
	/**
	 * 新增角色与实体属性关系(AC_ROLE_ENTITYFIELD)
	 * @param t 新记录
	 */
	public void insert(AcRoleEntityfield t);

	/**
	 * 更新角色与实体属性关系(AC_ROLE_ENTITYFIELD),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(AcRoleEntityfield t);

	/**
	 * 强制更新角色与实体属性关系(AC_ROLE_ENTITYFIELD)
	 * @param t 新值
	 */
	public void updateForce(AcRoleEntityfield t);

	/**
	 * 删除角色与实体属性关系(AC_ROLE_ENTITYFIELD)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除角色与实体属性关系(AC_ROLE_ENTITYFIELD)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新角色与实体属性关系(AC_ROLE_ENTITYFIELD)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, AcRoleEntityfield t);

	/**
	 * 根据条件查询角色与实体属性关系(AC_ROLE_ENTITYFIELD)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<AcRoleEntityfield> query(WhereCondition wc);

	/**
	 * 根据条件统计角色与实体属性关系(AC_ROLE_ENTITYFIELD)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询角色与实体属性关系(AC_ROLE_ENTITYFIELD)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public AcRoleEntityfield loadByGuid(String guid);
}
