
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcRoleEntity;

 
/**
 * <pre>
 * 角色实体关系(AC_ROLE_ENTITY)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IAcRoleEntityRService {
	
	/**
	 * 新增角色实体关系(AC_ROLE_ENTITY)
	 * @param t 新记录
	 */
	public void insert(AcRoleEntity t);

	/**
	 * 更新角色实体关系(AC_ROLE_ENTITY),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(AcRoleEntity t);

	/**
	 * 强制更新角色实体关系(AC_ROLE_ENTITY)
	 * @param t 新值
	 */
	public void updateForce(AcRoleEntity t);

	/**
	 * 删除角色实体关系(AC_ROLE_ENTITY)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除角色实体关系(AC_ROLE_ENTITY)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新角色实体关系(AC_ROLE_ENTITY)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, AcRoleEntity t);

	/**
	 * 根据条件查询角色实体关系(AC_ROLE_ENTITY)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<AcRoleEntity> query(WhereCondition wc);

	/**
	 * 根据条件统计角色实体关系(AC_ROLE_ENTITY)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询角色实体关系(AC_ROLE_ENTITY)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public AcRoleEntity loadByGuid(String guid);
}
