
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.log.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.log.LogTxTrace;

 
/**
 * <pre>
 * 交易操作日志(LOG_TX_TRACE)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface ILogTxTraceRService {
	
	/**
	 * 新增交易操作日志(LOG_TX_TRACE)
	 * @param t 新记录
	 */
	public void insert(LogTxTrace t);

	/**
	 * 更新交易操作日志(LOG_TX_TRACE),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(LogTxTrace t);

	/**
	 * 强制更新交易操作日志(LOG_TX_TRACE)
	 * @param t 新值
	 */
	public void updateForce(LogTxTrace t);

	/**
	 * 删除交易操作日志(LOG_TX_TRACE)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除交易操作日志(LOG_TX_TRACE)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新交易操作日志(LOG_TX_TRACE)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, LogTxTrace t);

	/**
	 * 根据条件查询交易操作日志(LOG_TX_TRACE)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<LogTxTrace> query(WhereCondition wc);

	/**
	 * 根据条件统计交易操作日志(LOG_TX_TRACE)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询交易操作日志(LOG_TX_TRACE)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public LogTxTrace loadByGuid(String guid);
}
