
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.log.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.log.LogCustomerContact;

 
/**
 * <pre>
 * 客户接触日志(LOG_CUSTOMER_CONTACT)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface ILogCustomerContactRService {
	
	/**
	 * 新增客户接触日志(LOG_CUSTOMER_CONTACT)
	 * @param t 新记录
	 */
	public void insert(LogCustomerContact t);

	/**
	 * 更新客户接触日志(LOG_CUSTOMER_CONTACT),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(LogCustomerContact t);

	/**
	 * 强制更新客户接触日志(LOG_CUSTOMER_CONTACT)
	 * @param t 新值
	 */
	public void updateForce(LogCustomerContact t);

	/**
	 * 删除客户接触日志(LOG_CUSTOMER_CONTACT)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除客户接触日志(LOG_CUSTOMER_CONTACT)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新客户接触日志(LOG_CUSTOMER_CONTACT)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, LogCustomerContact t);

	/**
	 * 根据条件查询客户接触日志(LOG_CUSTOMER_CONTACT)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<LogCustomerContact> query(WhereCondition wc);

	/**
	 * 根据条件统计客户接触日志(LOG_CUSTOMER_CONTACT)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询客户接触日志(LOG_CUSTOMER_CONTACT)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public LogCustomerContact loadByGuid(String guid);
}
