
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.sys.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.sys.SysTest;

 
/**
 * <pre>
 * 测试(SYS_TEST)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface ISysTestRService {
	
	/**
	 * 新增测试(SYS_TEST)
	 * @param t 新记录
	 */
	public void insert(SysTest t);

	/**
	 * 更新测试(SYS_TEST),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(SysTest t);

	/**
	 * 强制更新测试(SYS_TEST)
	 * @param t 新值
	 */
	public void updateForce(SysTest t);

	/**
	 * 删除测试(SYS_TEST)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除测试(SYS_TEST)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新测试(SYS_TEST)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, SysTest t);

	/**
	 * 根据条件查询测试(SYS_TEST)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<SysTest> query(WhereCondition wc);

	/**
	 * 根据条件统计测试(SYS_TEST)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询测试(SYS_TEST)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public SysTest loadByGuid(String guid);
}
