
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.sys.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.sys.SysDict;

 
/**
 * <pre>
 * 业务字典(SYS_DICT)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface ISysDictRService {
	
	/**
	 * 新增业务字典(SYS_DICT)
	 * @param t 新记录
	 */
	public void insert(SysDict t);

	/**
	 * 更新业务字典(SYS_DICT),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(SysDict t);

	/**
	 * 强制更新业务字典(SYS_DICT)
	 * @param t 新值
	 */
	public void updateForce(SysDict t);

	/**
	 * 删除业务字典(SYS_DICT)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除业务字典(SYS_DICT)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新业务字典(SYS_DICT)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, SysDict t);

	/**
	 * 根据条件查询业务字典(SYS_DICT)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<SysDict> query(WhereCondition wc);

	/**
	 * 根据条件统计业务字典(SYS_DICT)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询业务字典(SYS_DICT)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public SysDict loadByGuid(String guid);
}
