
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.sys.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.sys.SysSeqno;

 
/**
 * <pre>
 * 序号资源表(SYS_SEQNO)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface ISysSeqnoRService {
	
	/**
	 * 新增序号资源表(SYS_SEQNO)
	 * @param t 新记录
	 */
	public void insert(SysSeqno t);

	/**
	 * 更新序号资源表(SYS_SEQNO),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(SysSeqno t);

	/**
	 * 强制更新序号资源表(SYS_SEQNO)
	 * @param t 新值
	 */
	public void updateForce(SysSeqno t);

	/**
	 * 删除序号资源表(SYS_SEQNO)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除序号资源表(SYS_SEQNO)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新序号资源表(SYS_SEQNO)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, SysSeqno t);

	/**
	 * 根据条件查询序号资源表(SYS_SEQNO)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<SysSeqno> query(WhereCondition wc);

	/**
	 * 根据条件统计序号资源表(SYS_SEQNO)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询序号资源表(SYS_SEQNO)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public SysSeqno loadByGuid(String guid);
}
