
/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.torg;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.torg.OmPosition;
import org.tis.tools.rservice.torg.IOmPositionRService;
import org.tis.tools.service.torg.OmPositionService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * <pre>
 * auto generated by mvn bronsp:gen-dao, don't change</br>
 * 岗位定义表(OM_POSITION) 基本远程服务实现(服务提供者)
 * 模型：岗位定义表 OM_POSITION
 * 描述：岗位定义表
 * 业务域：torg
 * 定义文件：D:\GitSpace\tistools\tools-core\model\model-user.xml
 * </pre>
 */
@Service(group = "torg", version = "1.0", interfaceClass = IOmPositionRService.class, timeout = 2000, document = "岗位定义表的基础远程服务")
public class OmPositionRServiceImpl implements IOmPositionRService {

	@Autowired
	OmPositionService omPositionService;

	@Override
	public void insert(OmPosition t) {
		omPositionService.insert(t);
	}

	@Override
	public void update(OmPosition t) {
		omPositionService.update(t);
	}

	@Override
	public void updateForce(OmPosition t) {
		omPositionService.updateForce(t);
	}

	@Override
	public void delete(String id) {
		omPositionService.delete(id);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omPositionService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmPosition t) {
		omPositionService.updateByCondition(wc,t);
	}

	@Override
	public List<OmPosition> query(WhereCondition wc) {
		return omPositionService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omPositionService.count(wc);
	}

	@Override
	public OmPosition loadById(String id) {
		return omPositionService.loadById(id);
	}

}
