/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.jnl;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.jnl.JnlContactLog;

/**
 * 
 * 客户接触日志(JNL_CONTACT_LOG)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface JnlContactLogMapper extends BaseMapper<JnlContactLog>{

}
