/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.jnl;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.jnl.JnlHosttrans;

/**
 * 
 * 主机交易流水(JNL_HOSTTRANS)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface JnlHosttransMapper extends BaseMapper<JnlHosttrans>{

}
