/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.jnl;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.jnl.JnlTrans;

/**
 * 
 * 交易流水(JNL_TRANS)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface JnlTransMapper extends BaseMapper<JnlTrans>{

}
