package org.tis.tools;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 数据范围权限.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AcDatascope implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 实体. */
	private AcEntity entityacEntity;

	/** 数据范围权限名称. */
	private String privName;

	/** 数据操作类型. */
	private String dataOpType;

	/** 实体名称. */
	private String entityName;

	/** 过滤SQL. */
	private String filterSqlString;

	/** The set of 角色数据范围权限对应. */
	private Set<AcRoleDatascope> acRoleDatascopeSet;

	/**
	 * Constructor.
	 */
	public AcDatascope() {
		this.acRoleDatascopeSet = new HashSet<AcRoleDatascope>();
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 实体.
	 * 
	 * @param entityacEntity
	 *            实体
	 */
	public void setentityacEntity(AcEntity entityacEntity) {
		this.entityacEntity = entityacEntity;
	}

	/**
	 * Get the 实体.
	 * 
	 * @return 实体
	 */
	public AcEntity getentityacEntity() {
		return this.entityacEntity;
	}

	/**
	 * Set the 数据范围权限名称.
	 * 
	 * @param privName
	 *            数据范围权限名称
	 */
	public void setPrivName(String privName) {
		this.privName = privName;
	}

	/**
	 * Get the 数据范围权限名称.
	 * 
	 * @return 数据范围权限名称
	 */
	public String getPrivName() {
		return this.privName;
	}

	/**
	 * Set the 数据操作类型.
	 * 
	 * @param dataOpType
	 *            数据操作类型
	 */
	public void setDataOpType(String dataOpType) {
		this.dataOpType = dataOpType;
	}

	/**
	 * Get the 数据操作类型.
	 * 
	 * @return 数据操作类型
	 */
	public String getDataOpType() {
		return this.dataOpType;
	}

	/**
	 * Set the 实体名称.
	 * 
	 * @param entityName
	 *            实体名称
	 */
	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	/**
	 * Get the 实体名称.
	 * 
	 * @return 实体名称
	 */
	public String getEntityName() {
		return this.entityName;
	}

	/**
	 * Set the 过滤SQL.
	 * 
	 * @param filterSqlString
	 *            过滤SQL
	 */
	public void setFilterSqlString(String filterSqlString) {
		this.filterSqlString = filterSqlString;
	}

	/**
	 * Get the 过滤SQL.
	 * 
	 * @return 过滤SQL
	 */
	public String getFilterSqlString() {
		return this.filterSqlString;
	}

	/**
	 * Set the set of the 角色数据范围权限对应.
	 * 
	 * @param acRoleDatascopeSet
	 *            The set of 角色数据范围权限对应
	 */
	public void setAcRoleDatascopeSet(Set<AcRoleDatascope> acRoleDatascopeSet) {
		this.acRoleDatascopeSet = acRoleDatascopeSet;
	}

	/**
	 * Add the 角色数据范围权限对应.
	 * 
	 * @param acRoleDatascope
	 *            角色数据范围权限对应
	 */
	public void addAcRoleDatascope(AcRoleDatascope acRoleDatascope) {
		this.acRoleDatascopeSet.add(acRoleDatascope);
	}

	/**
	 * Get the set of the 角色数据范围权限对应.
	 * 
	 * @return The set of 角色数据范围权限对应
	 */
	public Set<AcRoleDatascope> getAcRoleDatascopeSet() {
		return this.acRoleDatascopeSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AcDatascope other = (AcDatascope) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
