package org.tis.tools;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 功能组.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AcFuncgroup implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 应用系统. */
	private AcApp appacApp;

	/** 功能组名称. */
	private String funcgroupName;

	/** 功能组. */
	private AcFuncgroup parentsacFuncgroup;

	/** 节点层次. */
	private Integer groupLevel;

	/** 功能组路径序列. */
	private String funcgroupSeq;

	/** 是否叶子节点. */
	private String isleaf;

	/** 子节点数. */
	private Integer subCount;

	/** The set of 功能. */
	private Set<AcFunc> acFuncSet;

	/** The set of 功能组. */
	private Set<AcFuncgroup> acFuncgroupSet;

	/**
	 * Constructor.
	 */
	public AcFuncgroup() {
		this.acFuncSet = new HashSet<AcFunc>();
		this.acFuncgroupSet = new HashSet<AcFuncgroup>();
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 应用系统.
	 * 
	 * @param appacApp
	 *            应用系统
	 */
	public void setappacApp(AcApp appacApp) {
		this.appacApp = appacApp;
	}

	/**
	 * Get the 应用系统.
	 * 
	 * @return 应用系统
	 */
	public AcApp getappacApp() {
		return this.appacApp;
	}

	/**
	 * Set the 功能组名称.
	 * 
	 * @param funcgroupName
	 *            功能组名称
	 */
	public void setFuncgroupName(String funcgroupName) {
		this.funcgroupName = funcgroupName;
	}

	/**
	 * Get the 功能组名称.
	 * 
	 * @return 功能组名称
	 */
	public String getFuncgroupName() {
		return this.funcgroupName;
	}

	/**
	 * Set the 功能组.
	 * 
	 * @param parentsacFuncgroup
	 *            功能组
	 */
	public void setparentsacFuncgroup(AcFuncgroup parentsacFuncgroup) {
		this.parentsacFuncgroup = parentsacFuncgroup;
	}

	/**
	 * Get the 功能组.
	 * 
	 * @return 功能组
	 */
	public AcFuncgroup getparentsacFuncgroup() {
		return this.parentsacFuncgroup;
	}

	/**
	 * Set the 节点层次.
	 * 
	 * @param groupLevel
	 *            节点层次
	 */
	public void setGroupLevel(Integer groupLevel) {
		this.groupLevel = groupLevel;
	}

	/**
	 * Get the 节点层次.
	 * 
	 * @return 节点层次
	 */
	public Integer getGroupLevel() {
		return this.groupLevel;
	}

	/**
	 * Set the 功能组路径序列.
	 * 
	 * @param funcgroupSeq
	 *            功能组路径序列
	 */
	public void setFuncgroupSeq(String funcgroupSeq) {
		this.funcgroupSeq = funcgroupSeq;
	}

	/**
	 * Get the 功能组路径序列.
	 * 
	 * @return 功能组路径序列
	 */
	public String getFuncgroupSeq() {
		return this.funcgroupSeq;
	}

	/**
	 * Set the 是否叶子节点.
	 * 
	 * @param isleaf
	 *            是否叶子节点
	 */
	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	/**
	 * Get the 是否叶子节点.
	 * 
	 * @return 是否叶子节点
	 */
	public String getIsleaf() {
		return this.isleaf;
	}

	/**
	 * Set the 子节点数.
	 * 
	 * @param subCount
	 *            子节点数
	 */
	public void setSubCount(Integer subCount) {
		this.subCount = subCount;
	}

	/**
	 * Get the 子节点数.
	 * 
	 * @return 子节点数
	 */
	public Integer getSubCount() {
		return this.subCount;
	}

	/**
	 * Set the set of the 功能.
	 * 
	 * @param acFuncSet
	 *            The set of 功能
	 */
	public void setAcFuncSet(Set<AcFunc> acFuncSet) {
		this.acFuncSet = acFuncSet;
	}

	/**
	 * Add the 功能.
	 * 
	 * @param acFunc
	 *            功能
	 */
	public void addAcFunc(AcFunc acFunc) {
		this.acFuncSet.add(acFunc);
	}

	/**
	 * Get the set of the 功能.
	 * 
	 * @return The set of 功能
	 */
	public Set<AcFunc> getAcFuncSet() {
		return this.acFuncSet;
	}

	/**
	 * Set the set of the 功能组.
	 * 
	 * @param acFuncgroupSet
	 *            The set of 功能组
	 */
	public void setAcFuncgroupSet(Set<AcFuncgroup> acFuncgroupSet) {
		this.acFuncgroupSet = acFuncgroupSet;
	}

	/**
	 * Add the 功能组.
	 * 
	 * @param acFuncgroup
	 *            功能组
	 */
	public void addAcFuncgroup(AcFuncgroup acFuncgroup) {
		this.acFuncgroupSet.add(acFuncgroup);
	}

	/**
	 * Get the set of the 功能组.
	 * 
	 * @return The set of 功能组
	 */
	public Set<AcFuncgroup> getAcFuncgroupSet() {
		return this.acFuncgroupSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AcFuncgroup other = (AcFuncgroup) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
