package org.tis.tools;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 操作员特殊权限配置.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AcOperatorFunc implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 操作员. */
	private AcOperator operatoracOperator;

	/** 功能. */
	private AcFunc funcacFunc;

	/** 授权标志. */
	private String authType;

	/** 有效开始日期. */
	private Date startDate;

	/** 有效截至日期. */
	private Date endDate;

	/** 应用GUID. */
	private String guidApp;

	/** 功能组GUID. */
	private String guidFuncgroup;

	/**
	 * Constructor.
	 */
	public AcOperatorFunc() {
	}

	/**
	 * Set the 操作员.
	 * 
	 * @param operatoracOperator
	 *            操作员
	 */
	public void setoperatoracOperator(AcOperator operatoracOperator) {
		this.operatoracOperator = operatoracOperator;
	}

	/**
	 * Get the 操作员.
	 * 
	 * @return 操作员
	 */
	public AcOperator getoperatoracOperator() {
		return this.operatoracOperator;
	}

	/**
	 * Set the 功能.
	 * 
	 * @param funcacFunc
	 *            功能
	 */
	public void setfuncacFunc(AcFunc funcacFunc) {
		this.funcacFunc = funcacFunc;
	}

	/**
	 * Get the 功能.
	 * 
	 * @return 功能
	 */
	public AcFunc getfuncacFunc() {
		return this.funcacFunc;
	}

	/**
	 * Set the 授权标志.
	 * 
	 * @param authType
	 *            授权标志
	 */
	public void setAuthType(String authType) {
		this.authType = authType;
	}

	/**
	 * Get the 授权标志.
	 * 
	 * @return 授权标志
	 */
	public String getAuthType() {
		return this.authType;
	}

	/**
	 * Set the 有效开始日期.
	 * 
	 * @param startDate
	 *            有效开始日期
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * Get the 有效开始日期.
	 * 
	 * @return 有效开始日期
	 */
	public Date getStartDate() {
		return this.startDate;
	}

	/**
	 * Set the 有效截至日期.
	 * 
	 * @param endDate
	 *            有效截至日期
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * Get the 有效截至日期.
	 * 
	 * @return 有效截至日期
	 */
	public Date getEndDate() {
		return this.endDate;
	}

	/**
	 * Set the 应用GUID.
	 * 
	 * @param guidApp
	 *            应用GUID
	 */
	public void setGuidApp(String guidApp) {
		this.guidApp = guidApp;
	}

	/**
	 * Get the 应用GUID.
	 * 
	 * @return 应用GUID
	 */
	public String getGuidApp() {
		return this.guidApp;
	}

	/**
	 * Set the 功能组GUID.
	 * 
	 * @param guidFuncgroup
	 *            功能组GUID
	 */
	public void setGuidFuncgroup(String guidFuncgroup) {
		this.guidFuncgroup = guidFuncgroup;
	}

	/**
	 * Get the 功能组GUID.
	 * 
	 * @return 功能组GUID
	 */
	public String getGuidFuncgroup() {
		return this.guidFuncgroup;
	}


}
