package org.tis.tools;

import java.io.Serializable;

/**
 * Model class of 应用工作组列表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OmAppGroup implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 应用GUID. */
	private String guidApp;

	/** 工作组. */
	private OmGroup groupomGroup;

	/**
	 * Constructor.
	 */
	public OmAppGroup() {
	}

	/**
	 * Set the 应用GUID.
	 * 
	 * @param guidApp
	 *            应用GUID
	 */
	public void setGuidApp(String guidApp) {
		this.guidApp = guidApp;
	}

	/**
	 * Get the 应用GUID.
	 * 
	 * @return 应用GUID
	 */
	public String getGuidApp() {
		return this.guidApp;
	}

	/**
	 * Set the 工作组.
	 * 
	 * @param groupomGroup
	 *            工作组
	 */
	public void setgroupomGroup(OmGroup groupomGroup) {
		this.groupomGroup = groupomGroup;
	}

	/**
	 * Get the 工作组.
	 * 
	 * @return 工作组
	 */
	public OmGroup getgroupomGroup() {
		return this.groupomGroup;
	}


}
