package org.tis.tools;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 职务定义表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OmDuty implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 职务代码. */
	private String dutyCode;

	/** 职务名称. */
	private String dutyName;

	/** 职务套别. */
	private String dutyType;

	/** 职务定义表. */
	private OmDuty parentsomDuty;

	/** 是否叶子节点. */
	private String isleaf;

	/** 子节点数. */
	private Integer subCount;

	/** 职务层次. */
	private Integer dutyLevel;

	/** 职务序列. */
	private String dutySeq;

	/** 备注. */
	private String remark;

	/** The set of 职务定义表. */
	private Set<OmDuty> omDutySet;

	/** The set of 岗位. */
	private Set<OmPosition> omPositionSet;

	/**
	 * Constructor.
	 */
	public OmDuty() {
		this.omDutySet = new HashSet<OmDuty>();
		this.omPositionSet = new HashSet<OmPosition>();
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 职务代码.
	 * 
	 * @param dutyCode
	 *            职务代码
	 */
	public void setDutyCode(String dutyCode) {
		this.dutyCode = dutyCode;
	}

	/**
	 * Get the 职务代码.
	 * 
	 * @return 职务代码
	 */
	public String getDutyCode() {
		return this.dutyCode;
	}

	/**
	 * Set the 职务名称.
	 * 
	 * @param dutyName
	 *            职务名称
	 */
	public void setDutyName(String dutyName) {
		this.dutyName = dutyName;
	}

	/**
	 * Get the 职务名称.
	 * 
	 * @return 职务名称
	 */
	public String getDutyName() {
		return this.dutyName;
	}

	/**
	 * Set the 职务套别.
	 * 
	 * @param dutyType
	 *            职务套别
	 */
	public void setDutyType(String dutyType) {
		this.dutyType = dutyType;
	}

	/**
	 * Get the 职务套别.
	 * 
	 * @return 职务套别
	 */
	public String getDutyType() {
		return this.dutyType;
	}

	/**
	 * Set the 职务定义表.
	 * 
	 * @param parentsomDuty
	 *            职务定义表
	 */
	public void setparentsomDuty(OmDuty parentsomDuty) {
		this.parentsomDuty = parentsomDuty;
	}

	/**
	 * Get the 职务定义表.
	 * 
	 * @return 职务定义表
	 */
	public OmDuty getparentsomDuty() {
		return this.parentsomDuty;
	}

	/**
	 * Set the 是否叶子节点.
	 * 
	 * @param isleaf
	 *            是否叶子节点
	 */
	public void setIsleaf(String isleaf) {
		this.isleaf = isleaf;
	}

	/**
	 * Get the 是否叶子节点.
	 * 
	 * @return 是否叶子节点
	 */
	public String getIsleaf() {
		return this.isleaf;
	}

	/**
	 * Set the 子节点数.
	 * 
	 * @param subCount
	 *            子节点数
	 */
	public void setSubCount(Integer subCount) {
		this.subCount = subCount;
	}

	/**
	 * Get the 子节点数.
	 * 
	 * @return 子节点数
	 */
	public Integer getSubCount() {
		return this.subCount;
	}

	/**
	 * Set the 职务层次.
	 * 
	 * @param dutyLevel
	 *            职务层次
	 */
	public void setDutyLevel(Integer dutyLevel) {
		this.dutyLevel = dutyLevel;
	}

	/**
	 * Get the 职务层次.
	 * 
	 * @return 职务层次
	 */
	public Integer getDutyLevel() {
		return this.dutyLevel;
	}

	/**
	 * Set the 职务序列.
	 * 
	 * @param dutySeq
	 *            职务序列
	 */
	public void setDutySeq(String dutySeq) {
		this.dutySeq = dutySeq;
	}

	/**
	 * Get the 职务序列.
	 * 
	 * @return 职务序列
	 */
	public String getDutySeq() {
		return this.dutySeq;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param remark
	 *            备注
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * Set the set of the 职务定义表.
	 * 
	 * @param omDutySet
	 *            The set of 职务定义表
	 */
	public void setOmDutySet(Set<OmDuty> omDutySet) {
		this.omDutySet = omDutySet;
	}

	/**
	 * Add the 职务定义表.
	 * 
	 * @param omDuty
	 *            职务定义表
	 */
	public void addOmDuty(OmDuty omDuty) {
		this.omDutySet.add(omDuty);
	}

	/**
	 * Get the set of the 职务定义表.
	 * 
	 * @return The set of 职务定义表
	 */
	public Set<OmDuty> getOmDutySet() {
		return this.omDutySet;
	}

	/**
	 * Set the set of the 岗位.
	 * 
	 * @param omPositionSet
	 *            The set of 岗位
	 */
	public void setOmPositionSet(Set<OmPosition> omPositionSet) {
		this.omPositionSet = omPositionSet;
	}

	/**
	 * Add the 岗位.
	 * 
	 * @param omPosition
	 *            岗位
	 */
	public void addOmPosition(OmPosition omPosition) {
		this.omPositionSet.add(omPosition);
	}

	/**
	 * Get the set of the 岗位.
	 * 
	 * @return The set of 岗位
	 */
	public Set<OmPosition> getOmPositionSet() {
		return this.omPositionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		OmDuty other = (OmDuty) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
