package org.tis.tools;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 员工.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OmEmployee implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 员工代码. */
	private String empCode;

	/** 员工姓名. */
	private String empName;

	/** 员工全名. */
	private String empRealname;

	/** 性别. */
	private String gender;

	/** 员工状态. */
	private String empstatus;

	/** 员工职级. */
	private String empDegree;

	/** 主机构编号. */
	private String guidOrg;

	/** 基本岗位. */
	private String guidPosition;

	/** 直接主管. */
	private String guidEmpMajor;

	/** 入职日期. */
	private Date indate;

	/** 离职日期. */
	private Date outdate;

	/** 办公电话. */
	private String otel;

	/** 办公地址. */
	private String oaddress;

	/** 办公邮编. */
	private String ozipcode;

	/** 办公邮件. */
	private String oemail;

	/** 传真号码. */
	private String faxno;

	/** 手机号码. */
	private String mobileno;

	/** MSN号码. */
	private String msn;

	/** 证件类型. */
	private String paperType;

	/** 证件号码. */
	private String paperNo;

	/** 出生日期. */
	private Date birthdate;

	/** 家庭电话. */
	private String htel;

	/** 家庭地址. */
	private String haddress;

	/** 家庭邮编. */
	private String hzipcode;

	/** 政治面貌. */
	private String party;

	/** 私人电子邮箱. */
	private String pemail;

	/** 操作员编号. */
	private String guidOperator;

	/** 操作员. */
	private String userId;

	/** 可授权角色. */
	private String specialty;

	/** 可管理机构. */
	private String orgList;

	/** 工作描述. */
	private String workexp;

	/** 备注. */
	private String remark;

	/** 注册日期. */
	private Date regdate;

	/** 创建时间. */
	private Date createtime;

	/** 最新更新时间. */
	private Date lastmodytime;

	/** The set of 人员工作组对应关系. */
	private Set<OmEmpGroup> omEmpGroupSet;

	/** The set of 员工隶属机构关系表. */
	private Set<OmEmpOrg> omEmpOrgSet;

	/** The set of 员工岗位对应关系. */
	private Set<OmEmpPosition> omEmpPositionSet;

	/**
	 * Constructor.
	 */
	public OmEmployee() {
		this.omEmpGroupSet = new HashSet<OmEmpGroup>();
		this.omEmpOrgSet = new HashSet<OmEmpOrg>();
		this.omEmpPositionSet = new HashSet<OmEmpPosition>();
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 员工代码.
	 * 
	 * @param empCode
	 *            员工代码
	 */
	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	/**
	 * Get the 员工代码.
	 * 
	 * @return 员工代码
	 */
	public String getEmpCode() {
		return this.empCode;
	}

	/**
	 * Set the 员工姓名.
	 * 
	 * @param empName
	 *            员工姓名
	 */
	public void setEmpName(String empName) {
		this.empName = empName;
	}

	/**
	 * Get the 员工姓名.
	 * 
	 * @return 员工姓名
	 */
	public String getEmpName() {
		return this.empName;
	}

	/**
	 * Set the 员工全名.
	 * 
	 * @param empRealname
	 *            员工全名
	 */
	public void setEmpRealname(String empRealname) {
		this.empRealname = empRealname;
	}

	/**
	 * Get the 员工全名.
	 * 
	 * @return 员工全名
	 */
	public String getEmpRealname() {
		return this.empRealname;
	}

	/**
	 * Set the 性别.
	 * 
	 * @param gender
	 *            性别
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * Get the 性别.
	 * 
	 * @return 性别
	 */
	public String getGender() {
		return this.gender;
	}

	/**
	 * Set the 员工状态.
	 * 
	 * @param empstatus
	 *            员工状态
	 */
	public void setEmpstatus(String empstatus) {
		this.empstatus = empstatus;
	}

	/**
	 * Get the 员工状态.
	 * 
	 * @return 员工状态
	 */
	public String getEmpstatus() {
		return this.empstatus;
	}

	/**
	 * Set the 员工职级.
	 * 
	 * @param empDegree
	 *            员工职级
	 */
	public void setEmpDegree(String empDegree) {
		this.empDegree = empDegree;
	}

	/**
	 * Get the 员工职级.
	 * 
	 * @return 员工职级
	 */
	public String getEmpDegree() {
		return this.empDegree;
	}

	/**
	 * Set the 主机构编号.
	 * 
	 * @param guidOrg
	 *            主机构编号
	 */
	public void setGuidOrg(String guidOrg) {
		this.guidOrg = guidOrg;
	}

	/**
	 * Get the 主机构编号.
	 * 
	 * @return 主机构编号
	 */
	public String getGuidOrg() {
		return this.guidOrg;
	}

	/**
	 * Set the 基本岗位.
	 * 
	 * @param guidPosition
	 *            基本岗位
	 */
	public void setGuidPosition(String guidPosition) {
		this.guidPosition = guidPosition;
	}

	/**
	 * Get the 基本岗位.
	 * 
	 * @return 基本岗位
	 */
	public String getGuidPosition() {
		return this.guidPosition;
	}

	/**
	 * Set the 直接主管.
	 * 
	 * @param guidEmpMajor
	 *            直接主管
	 */
	public void setGuidEmpMajor(String guidEmpMajor) {
		this.guidEmpMajor = guidEmpMajor;
	}

	/**
	 * Get the 直接主管.
	 * 
	 * @return 直接主管
	 */
	public String getGuidEmpMajor() {
		return this.guidEmpMajor;
	}

	/**
	 * Set the 入职日期.
	 * 
	 * @param indate
	 *            入职日期
	 */
	public void setIndate(Date indate) {
		this.indate = indate;
	}

	/**
	 * Get the 入职日期.
	 * 
	 * @return 入职日期
	 */
	public Date getIndate() {
		return this.indate;
	}

	/**
	 * Set the 离职日期.
	 * 
	 * @param outdate
	 *            离职日期
	 */
	public void setOutdate(Date outdate) {
		this.outdate = outdate;
	}

	/**
	 * Get the 离职日期.
	 * 
	 * @return 离职日期
	 */
	public Date getOutdate() {
		return this.outdate;
	}

	/**
	 * Set the 办公电话.
	 * 
	 * @param otel
	 *            办公电话
	 */
	public void setOtel(String otel) {
		this.otel = otel;
	}

	/**
	 * Get the 办公电话.
	 * 
	 * @return 办公电话
	 */
	public String getOtel() {
		return this.otel;
	}

	/**
	 * Set the 办公地址.
	 * 
	 * @param oaddress
	 *            办公地址
	 */
	public void setOaddress(String oaddress) {
		this.oaddress = oaddress;
	}

	/**
	 * Get the 办公地址.
	 * 
	 * @return 办公地址
	 */
	public String getOaddress() {
		return this.oaddress;
	}

	/**
	 * Set the 办公邮编.
	 * 
	 * @param ozipcode
	 *            办公邮编
	 */
	public void setOzipcode(String ozipcode) {
		this.ozipcode = ozipcode;
	}

	/**
	 * Get the 办公邮编.
	 * 
	 * @return 办公邮编
	 */
	public String getOzipcode() {
		return this.ozipcode;
	}

	/**
	 * Set the 办公邮件.
	 * 
	 * @param oemail
	 *            办公邮件
	 */
	public void setOemail(String oemail) {
		this.oemail = oemail;
	}

	/**
	 * Get the 办公邮件.
	 * 
	 * @return 办公邮件
	 */
	public String getOemail() {
		return this.oemail;
	}

	/**
	 * Set the 传真号码.
	 * 
	 * @param faxno
	 *            传真号码
	 */
	public void setFaxno(String faxno) {
		this.faxno = faxno;
	}

	/**
	 * Get the 传真号码.
	 * 
	 * @return 传真号码
	 */
	public String getFaxno() {
		return this.faxno;
	}

	/**
	 * Set the 手机号码.
	 * 
	 * @param mobileno
	 *            手机号码
	 */
	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	/**
	 * Get the 手机号码.
	 * 
	 * @return 手机号码
	 */
	public String getMobileno() {
		return this.mobileno;
	}

	/**
	 * Set the MSN号码.
	 * 
	 * @param msn
	 *            MSN号码
	 */
	public void setMsn(String msn) {
		this.msn = msn;
	}

	/**
	 * Get the MSN号码.
	 * 
	 * @return MSN号码
	 */
	public String getMsn() {
		return this.msn;
	}

	/**
	 * Set the 证件类型.
	 * 
	 * @param paperType
	 *            证件类型
	 */
	public void setPaperType(String paperType) {
		this.paperType = paperType;
	}

	/**
	 * Get the 证件类型.
	 * 
	 * @return 证件类型
	 */
	public String getPaperType() {
		return this.paperType;
	}

	/**
	 * Set the 证件号码.
	 * 
	 * @param paperNo
	 *            证件号码
	 */
	public void setPaperNo(String paperNo) {
		this.paperNo = paperNo;
	}

	/**
	 * Get the 证件号码.
	 * 
	 * @return 证件号码
	 */
	public String getPaperNo() {
		return this.paperNo;
	}

	/**
	 * Set the 出生日期.
	 * 
	 * @param birthdate
	 *            出生日期
	 */
	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	/**
	 * Get the 出生日期.
	 * 
	 * @return 出生日期
	 */
	public Date getBirthdate() {
		return this.birthdate;
	}

	/**
	 * Set the 家庭电话.
	 * 
	 * @param htel
	 *            家庭电话
	 */
	public void setHtel(String htel) {
		this.htel = htel;
	}

	/**
	 * Get the 家庭电话.
	 * 
	 * @return 家庭电话
	 */
	public String getHtel() {
		return this.htel;
	}

	/**
	 * Set the 家庭地址.
	 * 
	 * @param haddress
	 *            家庭地址
	 */
	public void setHaddress(String haddress) {
		this.haddress = haddress;
	}

	/**
	 * Get the 家庭地址.
	 * 
	 * @return 家庭地址
	 */
	public String getHaddress() {
		return this.haddress;
	}

	/**
	 * Set the 家庭邮编.
	 * 
	 * @param hzipcode
	 *            家庭邮编
	 */
	public void setHzipcode(String hzipcode) {
		this.hzipcode = hzipcode;
	}

	/**
	 * Get the 家庭邮编.
	 * 
	 * @return 家庭邮编
	 */
	public String getHzipcode() {
		return this.hzipcode;
	}

	/**
	 * Set the 政治面貌.
	 * 
	 * @param party
	 *            政治面貌
	 */
	public void setParty(String party) {
		this.party = party;
	}

	/**
	 * Get the 政治面貌.
	 * 
	 * @return 政治面貌
	 */
	public String getParty() {
		return this.party;
	}

	/**
	 * Set the 私人电子邮箱.
	 * 
	 * @param pemail
	 *            私人电子邮箱
	 */
	public void setPemail(String pemail) {
		this.pemail = pemail;
	}

	/**
	 * Get the 私人电子邮箱.
	 * 
	 * @return 私人电子邮箱
	 */
	public String getPemail() {
		return this.pemail;
	}

	/**
	 * Set the 操作员编号.
	 * 
	 * @param guidOperator
	 *            操作员编号
	 */
	public void setGuidOperator(String guidOperator) {
		this.guidOperator = guidOperator;
	}

	/**
	 * Get the 操作员编号.
	 * 
	 * @return 操作员编号
	 */
	public String getGuidOperator() {
		return this.guidOperator;
	}

	/**
	 * Set the 操作员.
	 * 
	 * @param userId
	 *            操作员
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the 操作员.
	 * 
	 * @return 操作员
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * Set the 可授权角色.
	 * 
	 * @param specialty
	 *            可授权角色
	 */
	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	/**
	 * Get the 可授权角色.
	 * 
	 * @return 可授权角色
	 */
	public String getSpecialty() {
		return this.specialty;
	}

	/**
	 * Set the 可管理机构.
	 * 
	 * @param orgList
	 *            可管理机构
	 */
	public void setOrgList(String orgList) {
		this.orgList = orgList;
	}

	/**
	 * Get the 可管理机构.
	 * 
	 * @return 可管理机构
	 */
	public String getOrgList() {
		return this.orgList;
	}

	/**
	 * Set the 工作描述.
	 * 
	 * @param workexp
	 *            工作描述
	 */
	public void setWorkexp(String workexp) {
		this.workexp = workexp;
	}

	/**
	 * Get the 工作描述.
	 * 
	 * @return 工作描述
	 */
	public String getWorkexp() {
		return this.workexp;
	}

	/**
	 * Set the 备注.
	 * 
	 * @param remark
	 *            备注
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getRemark() {
		return this.remark;
	}

	/**
	 * Set the 注册日期.
	 * 
	 * @param regdate
	 *            注册日期
	 */
	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	/**
	 * Get the 注册日期.
	 * 
	 * @return 注册日期
	 */
	public Date getRegdate() {
		return this.regdate;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createtime
	 *            创建时间
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreatetime() {
		return this.createtime;
	}

	/**
	 * Set the 最新更新时间.
	 * 
	 * @param lastmodytime
	 *            最新更新时间
	 */
	public void setLastmodytime(Date lastmodytime) {
		this.lastmodytime = lastmodytime;
	}

	/**
	 * Get the 最新更新时间.
	 * 
	 * @return 最新更新时间
	 */
	public Date getLastmodytime() {
		return this.lastmodytime;
	}

	/**
	 * Set the set of the 人员工作组对应关系.
	 * 
	 * @param omEmpGroupSet
	 *            The set of 人员工作组对应关系
	 */
	public void setOmEmpGroupSet(Set<OmEmpGroup> omEmpGroupSet) {
		this.omEmpGroupSet = omEmpGroupSet;
	}

	/**
	 * Add the 人员工作组对应关系.
	 * 
	 * @param omEmpGroup
	 *            人员工作组对应关系
	 */
	public void addOmEmpGroup(OmEmpGroup omEmpGroup) {
		this.omEmpGroupSet.add(omEmpGroup);
	}

	/**
	 * Get the set of the 人员工作组对应关系.
	 * 
	 * @return The set of 人员工作组对应关系
	 */
	public Set<OmEmpGroup> getOmEmpGroupSet() {
		return this.omEmpGroupSet;
	}

	/**
	 * Set the set of the 员工隶属机构关系表.
	 * 
	 * @param omEmpOrgSet
	 *            The set of 员工隶属机构关系表
	 */
	public void setOmEmpOrgSet(Set<OmEmpOrg> omEmpOrgSet) {
		this.omEmpOrgSet = omEmpOrgSet;
	}

	/**
	 * Add the 员工隶属机构关系表.
	 * 
	 * @param omEmpOrg
	 *            员工隶属机构关系表
	 */
	public void addOmEmpOrg(OmEmpOrg omEmpOrg) {
		this.omEmpOrgSet.add(omEmpOrg);
	}

	/**
	 * Get the set of the 员工隶属机构关系表.
	 * 
	 * @return The set of 员工隶属机构关系表
	 */
	public Set<OmEmpOrg> getOmEmpOrgSet() {
		return this.omEmpOrgSet;
	}

	/**
	 * Set the set of the 员工岗位对应关系.
	 * 
	 * @param omEmpPositionSet
	 *            The set of 员工岗位对应关系
	 */
	public void setOmEmpPositionSet(Set<OmEmpPosition> omEmpPositionSet) {
		this.omEmpPositionSet = omEmpPositionSet;
	}

	/**
	 * Add the 员工岗位对应关系.
	 * 
	 * @param omEmpPosition
	 *            员工岗位对应关系
	 */
	public void addOmEmpPosition(OmEmpPosition omEmpPosition) {
		this.omEmpPositionSet.add(omEmpPosition);
	}

	/**
	 * Get the set of the 员工岗位对应关系.
	 * 
	 * @return The set of 员工岗位对应关系
	 */
	public Set<OmEmpPosition> getOmEmpPositionSet() {
		return this.omEmpPositionSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		OmEmployee other = (OmEmployee) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
