package org.tis.tools;

import java.io.Serializable;

/**
 * Model class of 错误码表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SysErrCode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 数据主键. */
	private String guid;

	/** 错误代码分类. */
	private String errcodeKind;

	/** 错误代码. */
	private String errCode;

	/** 错误信息. */
	private String errMsg;

	/**
	 * Constructor.
	 */
	public SysErrCode() {
	}

	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid() {
		return this.guid;
	}

	/**
	 * Set the 错误代码分类.
	 * 
	 * @param errcodeKind
	 *            错误代码分类
	 */
	public void setErrcodeKind(String errcodeKind) {
		this.errcodeKind = errcodeKind;
	}

	/**
	 * Get the 错误代码分类.
	 * 
	 * @return 错误代码分类
	 */
	public String getErrcodeKind() {
		return this.errcodeKind;
	}

	/**
	 * Set the 错误代码.
	 * 
	 * @param errCode
	 *            错误代码
	 */
	public void setErrCode(String errCode) {
		this.errCode = errCode;
	}

	/**
	 * Get the 错误代码.
	 * 
	 * @return 错误代码
	 */
	public String getErrCode() {
		return this.errCode;
	}

	/**
	 * Set the 错误信息.
	 * 
	 * @param errMsg
	 *            错误信息
	 */
	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	/**
	 * Get the 错误信息.
	 * 
	 * @return 错误信息
	 */
	public String getErrMsg() {
		return this.errMsg;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guid == null) ? 0 : guid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SysErrCode other = (SysErrCode) obj;
		if (guid == null) {
			if (other.guid != null) {
				return false;
			}
		} else if (!guid.equals(other.guid)) {
			return false;
		}
		return true;
	}

}
