
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmDuty;
import org.tis.tools.rservice.om.basic.IOmDutyRService;
import org.tis.tools.service.om.OmDutyService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 职务定义表(OM_DUTY) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "om", version = "1.0", interfaceClass = IOmDutyRService.class, timeout = 2000, document = "职务定义表的基础远程服务")
public class OmDutyRServiceImpl implements IOmDutyRService {

	@Autowired
	OmDutyService omDutyService;

	@Override
	public void insert(OmDuty t) {
		omDutyService.insert(t);
	}

	@Override
	public void update(OmDuty t) {
		omDutyService.update(t);
	}

	@Override
	public void updateForce(OmDuty t) {
		omDutyService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		omDutyService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omDutyService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmDuty t) {
		omDutyService.updateByCondition(wc,t);
	}

	@Override
	public List<OmDuty> query(WhereCondition wc) {
		return omDutyService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omDutyService.count(wc);
	}

	@Override
	public OmDuty loadByGuid(String guid) {
		return omDutyService.loadByGuid(guid);
	}

}
