
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmGroupPosition;
import org.tis.tools.rservice.om.IOmGroupPositionRService;
import org.tis.tools.service.om.OmGroupPositionService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 工作组岗位列表(OM_GROUP_POSITION) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "om", version = "1.0", interfaceClass = IOmGroupPositionRService.class, timeout = 2000, document = "工作组岗位列表的基础远程服务")
public class OmGroupPositionRServiceImpl implements IOmGroupPositionRService {

	@Autowired
	OmGroupPositionService omGroupPositionService;

	@Override
	public void insert(OmGroupPosition t) {
		omGroupPositionService.insert(t);
	}

	@Override
	public void update(OmGroupPosition t) {
		omGroupPositionService.update(t);
	}

	@Override
	public void updateForce(OmGroupPosition t) {
		omGroupPositionService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		omGroupPositionService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omGroupPositionService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmGroupPosition t) {
		omGroupPositionService.updateByCondition(wc,t);
	}

	@Override
	public List<OmGroupPosition> query(WhereCondition wc) {
		return omGroupPositionService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omGroupPositionService.count(wc);
	}

	@Override
	public OmGroupPosition loadByGuid(String guid) {
		return omGroupPositionService.loadByGuid(guid);
	}

}
