
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmPosition;
import org.tis.tools.rservice.om.basic.IOmPositionRService;
import org.tis.tools.service.om.OmPositionService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 岗位(OM_POSITION) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "om", version = "1.0", interfaceClass = IOmPositionRService.class, timeout = 2000, document = "岗位的基础远程服务")
public class OmPositionRServiceImpl implements IOmPositionRService {

	@Autowired
	OmPositionService omPositionService;

	@Override
	public void insert(OmPosition t) {
		omPositionService.insert(t);
	}

	@Override
	public void update(OmPosition t) {
		omPositionService.update(t);
	}

	@Override
	public void updateForce(OmPosition t) {
		omPositionService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		omPositionService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omPositionService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmPosition t) {
		omPositionService.updateByCondition(wc,t);
	}

	@Override
	public List<OmPosition> query(WhereCondition wc) {
		return omPositionService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omPositionService.count(wc);
	}

	@Override
	public OmPosition loadByGuid(String guid) {
		return omPositionService.loadByGuid(guid);
	}

}
