/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.ac;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.ac.AcDatascope;

/**
 * 
 * 数据范围权限(AC_DATASCOPE)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface AcDatascopeMapper extends BaseMapper<AcDatascope>{

}
