/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.ac;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtil;

/**
 * 
 * <pre>
 * 行为类型定义
 * 模型文件 ： D:\tistools\tools-core-basic\model\ABF-mysql.erm
 * 业务域：ac
 * 模型：AC_BHVTYPE_DEF 行为类型定义
 *
 * 功能行为的分类定义，以便很好的归类和配置功能的行为（AC_FUNC_BHV）
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class AcBhvtypeDef implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "AC_BHVTYPE_DEF" ; 
	/* AC_BHVTYPE_DEF table's columns definition */
	/** GUID ：数据主键<br/><br/>全局唯一标识符（GUID，Globally Unique Identifier），系统自动生成； */
	public static final String COLUMN_GUID = "guid" ; 
	/** BHVTYPE_CODE ：行为类型代码<br/><br/>应用中定义，定义了某种功能特有的操作行为 */
	public static final String COLUMN_BHVTYPE_CODE = "bhvtype_code" ; 
	/** BHVTYPE_NAME ：行为类型名称<br/><br/> */
	public static final String COLUMN_BHVTYPE_NAME = "bhvtype_name" ; 
	/** 对应的类名 */
	public static final String CLASS_NAME = "org.tis.tools.model.po.ac.AcBhvtypeDef";
    /** GUID字段名<br/> */
    public static final String NAME_GUID = "数据主键" ;
    /** BHVTYPE_CODE字段名<br/> */
    public static final String NAME_BHVTYPE_CODE = "行为类型代码" ;
    /** BHVTYPE_NAME字段名<br/> */
    public static final String NAME_BHVTYPE_NAME = "行为类型名称" ;
	
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：全局唯一标识符（GUID，Globally Unique Identifier），系统自动生成； */
	private String guid ;
	
	/** 字段类型：varchar<br/>字段名：行为类型代码<br/>描述：应用中定义，定义了某种功能特有的操作行为 */
	private String bhvtypeCode ;
	
	/** 字段类型：varchar<br/>字段名：行为类型名称<br/>描述： */
	private String bhvtypeName ;

	/**
	* Default Constructor
	*/
	public AcBhvtypeDef() {
	}

	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
 		this.guid = guid == null ? null : guid.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid(){
		return this.guid ;
    }
	
	/**
	 * Set the 行为类型代码.
	 * 
	 * @param bhvtypeCode
	 *            行为类型代码
	 */
	public void setBhvtypeCode(String bhvtypeCode) {
 		this.bhvtypeCode = bhvtypeCode == null ? null : bhvtypeCode.trim() ;
    }
    
    /**
	 * Get the 行为类型代码.
	 * 
	 * @return 行为类型代码
	 */
	public String getBhvtypeCode(){
		return this.bhvtypeCode ;
    }
	
	/**
	 * Set the 行为类型名称.
	 * 
	 * @param bhvtypeName
	 *            行为类型名称
	 */
	public void setBhvtypeName(String bhvtypeName) {
 		this.bhvtypeName = bhvtypeName == null ? null : bhvtypeName.trim() ;
    }
    
    /**
	 * Get the 行为类型名称.
	 * 
	 * @return 行为类型名称
	 */
	public String getBhvtypeName(){
		return this.bhvtypeName ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ; 
	}
}