/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.ac;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtil;

/**
 * 
 * <pre>
 * 个性化配置
 * 模型文件 ： E:\tools\tistools\tools-core-basic\model\ABF-mysql.erm
 * 业务域：ac
 * 模型：AC_CONFIG 个性化配置
 *
 * 个性化配置
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class AcConfig implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "AC_CONFIG" ; 
	/* AC_CONFIG table's columns definition */
	/** GUID ：数据主键<br/><br/> */
	public static final String COLUMN_GUID = "guid" ; 
	/** GUID_APP ：应用GUID<br/><br/> */
	public static final String COLUMN_GUID_APP = "guid_app" ; 
	/** CONFIG_TYPE ：配置类型<br/><br/> */
	public static final String COLUMN_CONFIG_TYPE = "config_type" ; 
	/** CONFIG_NAME ：配置名<br/><br/> */
	public static final String COLUMN_CONFIG_NAME = "config_name" ; 
	/** CONFIG_DICT ：配置值字典<br/><br/> */
	public static final String COLUMN_CONFIG_DICT = "config_dict" ; 
	/** CONFIG_VALUE ：默认配置值<br/><br/> */
	public static final String COLUMN_CONFIG_VALUE = "config_value" ; 
	/** ENABLED ：是否启用<br/><br/> */
	public static final String COLUMN_ENABLED = "enabled" ; 
	/** CONFIG_DESC ：配置描述说明<br/><br/> */
	public static final String COLUMN_CONFIG_DESC = "config_desc" ; 
	
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述： */
	private String guid ;
	
	/** 字段类型：varchar<br/>字段名：应用GUID<br/>描述： */
	private String guidApp ;
	
	/** 字段类型：varchar<br/>字段名：配置类型<br/>描述： */
	private String configType ;
	
	/** 字段类型：varchar<br/>字段名：配置名<br/>描述： */
	private String configName ;
	
	/** 字段类型：varchar<br/>字段名：配置值字典<br/>描述： */
	private String configDict ;
	
	/** 字段类型：varchar<br/>字段名：默认配置值<br/>描述： */
	private String configValue ;
	
	/** 字段类型：varchar<br/>字段名：是否启用<br/>描述： */
	private String enabled ;
	
	/** 字段类型：varchar<br/>字段名：配置描述说明<br/>描述： */
	private String configDesc ;

	/**
	* Default Constructor
	*/
	public AcConfig() {
	}

	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
 		this.guid = guid == null ? null : guid.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid(){
		return this.guid ;
    }
	
	/**
	 * Set the 应用GUID.
	 * 
	 * @param guidApp
	 *            应用GUID
	 */
	public void setGuidApp(String guidApp) {
 		this.guidApp = guidApp == null ? null : guidApp.trim() ;
    }
    
    /**
	 * Get the 应用GUID.
	 * 
	 * @return 应用GUID
	 */
	public String getGuidApp(){
		return this.guidApp ;
    }
	
	/**
	 * Set the 配置类型.
	 * 
	 * @param configType
	 *            配置类型
	 */
	public void setConfigType(String configType) {
 		this.configType = configType == null ? null : configType.trim() ;
    }
    
    /**
	 * Get the 配置类型.
	 * 
	 * @return 配置类型
	 */
	public String getConfigType(){
		return this.configType ;
    }
	
	/**
	 * Set the 配置名.
	 * 
	 * @param configName
	 *            配置名
	 */
	public void setConfigName(String configName) {
 		this.configName = configName == null ? null : configName.trim() ;
    }
    
    /**
	 * Get the 配置名.
	 * 
	 * @return 配置名
	 */
	public String getConfigName(){
		return this.configName ;
    }
	
	/**
	 * Set the 配置值字典.
	 * 
	 * @param configDict
	 *            配置值字典
	 */
	public void setConfigDict(String configDict) {
 		this.configDict = configDict == null ? null : configDict.trim() ;
    }
    
    /**
	 * Get the 配置值字典.
	 * 
	 * @return 配置值字典
	 */
	public String getConfigDict(){
		return this.configDict ;
    }
	
	/**
	 * Set the 默认配置值.
	 * 
	 * @param configValue
	 *            默认配置值
	 */
	public void setConfigValue(String configValue) {
 		this.configValue = configValue == null ? null : configValue.trim() ;
    }
    
    /**
	 * Get the 默认配置值.
	 * 
	 * @return 默认配置值
	 */
	public String getConfigValue(){
		return this.configValue ;
    }
	
	/**
	 * Set the 是否启用.
	 * 
	 * @param enabled
	 *            是否启用
	 */
	public void setEnabled(String enabled) {
 		this.enabled = enabled == null ? null : enabled.trim() ;
    }
    
    /**
	 * Get the 是否启用.
	 * 
	 * @return 是否启用
	 */
	public String getEnabled(){
		return this.enabled ;
    }
	
	/**
	 * Set the 配置描述说明.
	 * 
	 * @param configDesc
	 *            配置描述说明
	 */
	public void setConfigDesc(String configDesc) {
 		this.configDesc = configDesc == null ? null : configDesc.trim() ;
    }
    
    /**
	 * Get the 配置描述说明.
	 * 
	 * @return 配置描述说明
	 */
	public String getConfigDesc(){
		return this.configDesc ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ; 
	}
}