/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.ac;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtil;

/**
 * 
 * <pre>
 * 功能资源对应
 * 模型文件 ： D:\tistools\tools-core-basic\model\ABF-mysql.erm
 * 业务域：ac
 * 模型：AC_FUNC_RESOURCE 功能资源对应
 *
 * 功能点包含的系统资源内容，如jsp、页面流、逻辑流等资源。
功能点对应实际的代码资源。
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class AcFuncResource implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "AC_FUNC_RESOURCE" ; 
	/* AC_FUNC_RESOURCE table's columns definition */
	/** GUID_FUNC ：对应功能GUID<br/><br/> */
	public static final String COLUMN_GUID_FUNC = "guid_func" ; 
	/** ATTR_TYPE ：属性类型<br/><br/> */
	public static final String COLUMN_ATTR_TYPE = "attr_type" ; 
	/** ATTR_KEY ：属性名<br/><br/> */
	public static final String COLUMN_ATTR_KEY = "attr_key" ; 
	/** ATTR_VALUE ：属性值<br/><br/> */
	public static final String COLUMN_ATTR_VALUE = "attr_value" ; 
	/** MEMO ：备注<br/><br/> */
	public static final String COLUMN_MEMO = "memo" ; 
	/** 对应的类名 */
	public static final String CLASS_NAME = "org.tis.tools.model.po.ac.AcFuncResource";
    /** GUID_FUNC字段名<br/> */
    public static final String NAME_GUID_FUNC = "对应功能GUID" ;
    /** ATTR_TYPE字段名<br/> */
    public static final String NAME_ATTR_TYPE = "属性类型" ;
    /** ATTR_KEY字段名<br/> */
    public static final String NAME_ATTR_KEY = "属性名" ;
    /** ATTR_VALUE字段名<br/> */
    public static final String NAME_ATTR_VALUE = "属性值" ;
    /** MEMO字段名<br/> */
    public static final String NAME_MEMO = "备注" ;
	
	
	/** 字段类型：varchar<br/>字段名：对应功能GUID<br/>描述： */
	private String guidFunc ;
	
	/** 字段类型：varchar<br/>字段名：属性类型<br/>描述： */
	private String attrType ;
	
	/** 字段类型：varchar<br/>字段名：属性名<br/>描述： */
	private String attrKey ;
	
	/** 字段类型：varchar<br/>字段名：属性值<br/>描述： */
	private String attrValue ;
	
	/** 字段类型：varchar<br/>字段名：备注<br/>描述： */
	private String memo ;

	/**
	* Default Constructor
	*/
	public AcFuncResource() {
	}

	
	/**
	 * Set the 对应功能GUID.
	 * 
	 * @param guidFunc
	 *            对应功能GUID
	 */
	public void setGuidFunc(String guidFunc) {
 		this.guidFunc = guidFunc == null ? null : guidFunc.trim() ;
    }
    
    /**
	 * Get the 对应功能GUID.
	 * 
	 * @return 对应功能GUID
	 */
	public String getGuidFunc(){
		return this.guidFunc ;
    }
	
	/**
	 * Set the 属性类型.
	 * 
	 * @param attrType
	 *            属性类型
	 */
	public void setAttrType(String attrType) {
 		this.attrType = attrType == null ? null : attrType.trim() ;
    }
    
    /**
	 * Get the 属性类型.
	 * 
	 * @return 属性类型
	 */
	public String getAttrType(){
		return this.attrType ;
    }
	
	/**
	 * Set the 属性名.
	 * 
	 * @param attrKey
	 *            属性名
	 */
	public void setAttrKey(String attrKey) {
 		this.attrKey = attrKey == null ? null : attrKey.trim() ;
    }
    
    /**
	 * Get the 属性名.
	 * 
	 * @return 属性名
	 */
	public String getAttrKey(){
		return this.attrKey ;
    }
	
	/**
	 * Set the 属性值.
	 * 
	 * @param attrValue
	 *            属性值
	 */
	public void setAttrValue(String attrValue) {
 		this.attrValue = attrValue == null ? null : attrValue.trim() ;
    }
    
    /**
	 * Get the 属性值.
	 * 
	 * @return 属性值
	 */
	public String getAttrValue(){
		return this.attrValue ;
    }
	
	/**
	 * Set the 备注.
	 * 
	 * @param memo
	 *            备注
	 */
	public void setMemo(String memo) {
 		this.memo = memo == null ? null : memo.trim() ;
    }
    
    /**
	 * Get the 备注.
	 * 
	 * @return 备注
	 */
	public String getMemo(){
		return this.memo ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ; 
	}
}