/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.ac;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtil;

/**
 * 
 * <pre>
 * 操作员个性配置
 * 模型文件 ： E:\tools\tistools\tools-core-basic\model\ABF-mysql.erm
 * 业务域：ac
 * 模型：AC_OPERATOR_CONFIG 操作员个性配置
 *
 * 操作员个性化配置
如颜色配置
    登录风格
    是否使用重组菜单
    默认身份
    等

“操作员＋应用系统”，将配置按应用系统进行区分。
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class AcOperatorConfig implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "AC_OPERATOR_CONFIG" ; 
	/* AC_OPERATOR_CONFIG table's columns definition */
	/** GUID_OPERATOR ：操作员GUID<br/><br/> */
	public static final String COLUMN_GUID_OPERATOR = "guid_operator" ; 
	/** GUID_CONFIG ：配置GUID<br/><br/> */
	public static final String COLUMN_GUID_CONFIG = "guid_config" ; 
	/** CONFIG_VALUE ：配置值<br/><br/> */
	public static final String COLUMN_CONFIG_VALUE = "config_value" ; 
	
	
	/** 字段类型：varchar<br/>字段名：操作员GUID<br/>描述： */
	private String guidOperator ;
	
	/** 字段类型：varchar<br/>字段名：配置GUID<br/>描述： */
	private String guidConfig ;
	
	/** 字段类型：varchar<br/>字段名：配置值<br/>描述： */
	private String configValue ;

	/**
	* Default Constructor
	*/
	public AcOperatorConfig() {
	}

	
	/**
	 * Set the 操作员GUID.
	 * 
	 * @param guidOperator
	 *            操作员GUID
	 */
	public void setGuidOperator(String guidOperator) {
 		this.guidOperator = guidOperator == null ? null : guidOperator.trim() ;
    }
    
    /**
	 * Get the 操作员GUID.
	 * 
	 * @return 操作员GUID
	 */
	public String getGuidOperator(){
		return this.guidOperator ;
    }
	
	/**
	 * Set the 配置GUID.
	 * 
	 * @param guidConfig
	 *            配置GUID
	 */
	public void setGuidConfig(String guidConfig) {
 		this.guidConfig = guidConfig == null ? null : guidConfig.trim() ;
    }
    
    /**
	 * Get the 配置GUID.
	 * 
	 * @return 配置GUID
	 */
	public String getGuidConfig(){
		return this.guidConfig ;
    }
	
	/**
	 * Set the 配置值.
	 * 
	 * @param configValue
	 *            配置值
	 */
	public void setConfigValue(String configValue) {
 		this.configValue = configValue == null ? null : configValue.trim() ;
    }
    
    /**
	 * Get the 配置值.
	 * 
	 * @return 配置值
	 */
	public String getConfigValue(){
		return this.configValue ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ; 
	}
}