/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.ac;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtil;

/**
 * 
 * <pre>
 * 角色数据范围权限对应
 * 模型文件 ： E:\tools\tistools\tools-core-basic\model\abf-mysql.erm
 * 业务域：ac
 * 模型：AC_ROLE_DATASCOPE 角色数据范围权限对应
 *
 * 配置角色具有的数据权限。
说明角色拥有某个实体数据中哪些范围的操作权。
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class AcRoleDatascope implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "AC_ROLE_DATASCOPE" ; 
	/* AC_ROLE_DATASCOPE table's columns definition */
	/** GUID_ROLE ：角色GUID<br/><br/> */
	public static final String COLUMN_GUID_ROLE = "guid_role" ; 
	/** GUID_DATASCOPE ：拥有数据范围GUID<br/><br/> */
	public static final String COLUMN_GUID_DATASCOPE = "guid_datascope" ; 
	
	
	/** 字段类型：varchar<br/>字段名：角色GUID<br/>描述： */
	private String guidRole ;
	
	/** 字段类型：varchar<br/>字段名：拥有数据范围GUID<br/>描述： */
	private String guidDatascope ;
	
	
	/**
	 * Set the 角色GUID.
	 * 
	 * @param guidRole
	 *            角色GUID
	 */
	public void setGuidRole(String guidRole) {
 		this.guidRole = guidRole == null ? null : guidRole.trim() ;
    }
    
    /**
	 * Get the 角色GUID.
	 * 
	 * @return 角色GUID
	 */
	public String getGuidRole(){
		return this.guidRole ;
    }
	
	/**
	 * Set the 拥有数据范围GUID.
	 * 
	 * @param guidDatascope
	 *            拥有数据范围GUID
	 */
	public void setGuidDatascope(String guidDatascope) {
 		this.guidDatascope = guidDatascope == null ? null : guidDatascope.trim() ;
    }
    
    /**
	 * Get the 拥有数据范围GUID.
	 * 
	 * @return 拥有数据范围GUID
	 */
	public String getGuidDatascope(){
		return this.guidDatascope ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ; 
	}
}