/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.sys;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.sys.SysDictMapper;
import org.tis.tools.model.po.sys.SysDict;


/**
 * 业务字典(SYS_DICT)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class SysDictService {

	@Autowired
	SysDictMapper sysDictMapper;
	
    public void insert(SysDict t){
    	sysDictMapper.insert(t);
    }
    
    public void update(SysDict t){
    	sysDictMapper.update(t); 
    }
   
    public void updateForce(SysDict t){
    	sysDictMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	sysDictMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	sysDictMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,SysDict t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	sysDictMapper.updateByCondition(map); 
    }

    public List<SysDict> query(WhereCondition wc){
    	return sysDictMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return sysDictMapper.count(wc);
    }
   
    public SysDict loadByGuid(String guid){
    	return sysDictMapper.loadByGuid(guid);
    }
}
