/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.sys;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.sys.SysErrCodeMapper;
import org.tis.tools.model.po.sys.SysErrCode;


/**
 * 错误码表(SYS_ERR_CODE)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class SysErrCodeService {

	@Autowired
	SysErrCodeMapper sysErrCodeMapper;
	
    public void insert(SysErrCode t){
    	sysErrCodeMapper.insert(t);
    }
    
    public void update(SysErrCode t){
    	sysErrCodeMapper.update(t); 
    }
   
    public void updateForce(SysErrCode t){
    	sysErrCodeMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	sysErrCodeMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	sysErrCodeMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,SysErrCode t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	sysErrCodeMapper.updateByCondition(map); 
    }

    public List<SysErrCode> query(WhereCondition wc){
    	return sysErrCodeMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return sysErrCodeMapper.count(wc);
    }
   
    public SysErrCode loadByGuid(String guid){
    	return sysErrCodeMapper.loadByGuid(guid);
    }
}
