/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.ac;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.ac.AcBehavior;

/**
 * 
 * 功能操作行为(AC_BEHAVIOR)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface AcBehaviorMapper extends BaseMapper<AcBehavior>{

}
