/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.ac;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.ac.AcBhvDef;

/**
 * 
 * 功能操作行为定义(AC_BHV_DEF)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface AcBhvDefMapper extends BaseMapper<AcBhvDef>{

}
