/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.ac;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.ac.AcFunc;

/**
 * 
 * 功能(AC_FUNC)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface AcFuncMapper extends BaseMapper<AcFunc>{

}
