/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.ac;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.ac.AcOperator;

/**
 * 
 * 操作员(AC_OPERATOR)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface AcOperatorMapper extends BaseMapper<AcOperator>{

}
