/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.ac;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.ac.AcOperatorShortcut;

/**
 * 
 * 操作员快捷菜单(AC_OPERATOR_SHORTCUT)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface AcOperatorShortcutMapper extends BaseMapper<AcOperatorShortcut>{

}
