/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.ac;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.ac.AcOperatorBhv;

/**
 * 
 * 操作员特殊功能行为配置(AC_OPERATOR_BHV)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface AcOperatorBhvMapper extends BaseMapper<AcOperatorBhv>{

}
