
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlContactLog;
import org.tis.tools.rservice.jnl.IJnlContactLogRService;
import org.tis.tools.service.jnl.JnlContactLogService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 客户接触日志(JNL_CONTACT_LOG) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "jnl", version = "1.0", interfaceClass = IJnlContactLogRService.class, timeout = 2000, document = "客户接触日志的基础远程服务")
public class JnlContactLogRServiceImpl implements IJnlContactLogRService {

	@Autowired
	JnlContactLogService jnlContactLogService;

	@Override
	public void insert(JnlContactLog t) {
		jnlContactLogService.insert(t);
	}

	@Override
	public void update(JnlContactLog t) {
		jnlContactLogService.update(t);
	}

	@Override
	public void updateForce(JnlContactLog t) {
		jnlContactLogService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		jnlContactLogService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		jnlContactLogService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, JnlContactLog t) {
		jnlContactLogService.updateByCondition(wc,t);
	}

	@Override
	public List<JnlContactLog> query(WhereCondition wc) {
		return jnlContactLogService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return jnlContactLogService.count(wc);
	}

	@Override
	public JnlContactLog loadByGuid(String guid) {
		return jnlContactLogService.loadByGuid(guid);
	}

}
