
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlEnqueue;
import org.tis.tools.rservice.jnl.IJnlEnqueueRService;
import org.tis.tools.service.jnl.JnlEnqueueService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 排队流水(JNL_ENQUEUE) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "jnl", version = "1.0", interfaceClass = IJnlEnqueueRService.class, timeout = 2000, document = "排队流水的基础远程服务")
public class JnlEnqueueRServiceImpl implements IJnlEnqueueRService {

	@Autowired
	JnlEnqueueService jnlEnqueueService;

	@Override
	public void insert(JnlEnqueue t) {
		jnlEnqueueService.insert(t);
	}

	@Override
	public void update(JnlEnqueue t) {
		jnlEnqueueService.update(t);
	}

	@Override
	public void updateForce(JnlEnqueue t) {
		jnlEnqueueService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		jnlEnqueueService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		jnlEnqueueService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, JnlEnqueue t) {
		jnlEnqueueService.updateByCondition(wc,t);
	}

	@Override
	public List<JnlEnqueue> query(WhereCondition wc) {
		return jnlEnqueueService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return jnlEnqueueService.count(wc);
	}

	@Override
	public JnlEnqueue loadByGuid(String guid) {
		return jnlEnqueueService.loadByGuid(guid);
	}

}
