
/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.TbJnlReservation;
import org.tis.tools.rservice.jnl.ITbJnlReservationRService;
import org.tis.tools.service.jnl.TbJnlReservationService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * <pre>
 * auto generated by mvn bronsp:gen-dao, don't change</br>
 * 预约流水(tb_jnl_reservation) 基本远程服务实现(服务提供者)
 * 模型：预约流水 tb_jnl_reservation
 * 描述：预约流水表
 * 业务域：jnl
 * 定义文件：/Users/megapro/Develop/tis/tools/tools-core/model/model-jnl.xml
 * </pre>
 */
@Service(group = "jnl", version = "1.0", interfaceClass = ITbJnlReservationRService.class, timeout = 2000, document = "预约流水的基础远程服务")
public class TbJnlReservationRServiceImpl implements ITbJnlReservationRService {

	@Autowired
	TbJnlReservationService tbJnlReservationService;

	@Override
	public void insert(TbJnlReservation t) {
		tbJnlReservationService.insert(t);
	}

	@Override
	public void update(TbJnlReservation t) {
		tbJnlReservationService.update(t);
	}

	@Override
	public void updateForce(TbJnlReservation t) {
		tbJnlReservationService.updateForce(t);
	}

	@Override
	public void delete(String id) {
		tbJnlReservationService.delete(id);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		tbJnlReservationService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, TbJnlReservation t) {
		tbJnlReservationService.updateByCondition(wc,t);
	}

	@Override
	public List<TbJnlReservation> query(WhereCondition wc) {
		return tbJnlReservationService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return tbJnlReservationService.count(wc);
	}

	@Override
	public TbJnlReservation loadById(String id) {
		return tbJnlReservationService.loadById(id);
	}

}
