
/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.TbJnlPrefilled;
import org.tis.tools.rservice.jnl.ITbJnlPrefilledRService;
import org.tis.tools.service.jnl.TbJnlPrefilledService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * <pre>
 * auto generated by mvn bronsp:gen-dao, don't change</br>
 * 预填流水(tb_jnl_prefilled) 基本远程服务实现(服务提供者)
 * 模型：预填流水 tb_jnl_prefilled
 * 描述：预填流水表
 * 业务域：jnl
 * 定义文件：/Users/megapro/Develop/tis/tools/tools-core/model/model-jnl.xml
 * </pre>
 */
@Service(group = "jnl", version = "1.0", interfaceClass = ITbJnlPrefilledRService.class, timeout = 2000, document = "预填流水的基础远程服务")
public class TbJnlPrefilledRServiceImpl implements ITbJnlPrefilledRService {

	@Autowired
	TbJnlPrefilledService tbJnlPrefilledService;

	@Override
	public void insert(TbJnlPrefilled t) {
		tbJnlPrefilledService.insert(t);
	}

	@Override
	public void update(TbJnlPrefilled t) {
		tbJnlPrefilledService.update(t);
	}

	@Override
	public void updateForce(TbJnlPrefilled t) {
		tbJnlPrefilledService.updateForce(t);
	}

	@Override
	public void delete(String id) {
		tbJnlPrefilledService.delete(id);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		tbJnlPrefilledService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, TbJnlPrefilled t) {
		tbJnlPrefilledService.updateByCondition(wc,t);
	}

	@Override
	public List<TbJnlPrefilled> query(WhereCondition wc) {
		return tbJnlPrefilledService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return tbJnlPrefilledService.count(wc);
	}

	@Override
	public TbJnlPrefilled loadById(String id) {
		return tbJnlPrefilledService.loadById(id);
	}

}
