/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.log;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.log.LogAbfOperator;

/**
 * 
 * 操作日志(LOG_ABF_OPERATOR)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface LogAbfOperatorMapper extends BaseMapper<LogAbfOperator>{

}
