/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.log;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.log.LogAbfKeyword;

/**
 * 
 * 记录关键值(LOG_ABF_KEYWORD)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface LogAbfKeywordMapper extends BaseMapper<LogAbfKeyword>{

}
