
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcDatascope;

 
/**
 * <pre>
 * 数据范围权限(AC_DATASCOPE)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IAcDatascopeRService {
	
	/**
	 * 新增数据范围权限(AC_DATASCOPE)
	 * @param t 新记录
	 */
	public void insert(AcDatascope t);

	/**
	 * 更新数据范围权限(AC_DATASCOPE),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(AcDatascope t);

	/**
	 * 强制更新数据范围权限(AC_DATASCOPE)
	 * @param t 新值
	 */
	public void updateForce(AcDatascope t);

	/**
	 * 删除数据范围权限(AC_DATASCOPE)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除数据范围权限(AC_DATASCOPE)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新数据范围权限(AC_DATASCOPE)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, AcDatascope t);

	/**
	 * 根据条件查询数据范围权限(AC_DATASCOPE)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<AcDatascope> query(WhereCondition wc);

	/**
	 * 根据条件统计数据范围权限(AC_DATASCOPE)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询数据范围权限(AC_DATASCOPE)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public AcDatascope loadByGuid(String guid);
}
