
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcFuncBhvtype;

 
/**
 * <pre>
 * 功能行为类型表(AC_FUNC_BHVTYPE)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IAcFuncBhvtypeRService {
	
	/**
	 * 新增功能行为类型表(AC_FUNC_BHVTYPE)
	 * @param t 新记录
	 */
	public void insert(AcFuncBhvtype t);

	/**
	 * 更新功能行为类型表(AC_FUNC_BHVTYPE),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(AcFuncBhvtype t);

	/**
	 * 强制更新功能行为类型表(AC_FUNC_BHVTYPE)
	 * @param t 新值
	 */
	public void updateForce(AcFuncBhvtype t);

	/**
	 * 删除功能行为类型表(AC_FUNC_BHVTYPE)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除功能行为类型表(AC_FUNC_BHVTYPE)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新功能行为类型表(AC_FUNC_BHVTYPE)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, AcFuncBhvtype t);

	/**
	 * 根据条件查询功能行为类型表(AC_FUNC_BHVTYPE)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<AcFuncBhvtype> query(WhereCondition wc);

	/**
	 * 根据条件统计功能行为类型表(AC_FUNC_BHVTYPE)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询功能行为类型表(AC_FUNC_BHVTYPE)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public AcFuncBhvtype loadByGuid(String guid);
}
