
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcFunc;

 
/**
 * <pre>
 * 功能(AC_FUNC)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IAcFuncRService {
	
	/**
	 * 新增功能(AC_FUNC)
	 * @param t 新记录
	 */
	public void insert(AcFunc t);

	/**
	 * 更新功能(AC_FUNC),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(AcFunc t);

	/**
	 * 强制更新功能(AC_FUNC)
	 * @param t 新值
	 */
	public void updateForce(AcFunc t);

	/**
	 * 删除功能(AC_FUNC)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除功能(AC_FUNC)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新功能(AC_FUNC)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, AcFunc t);

	/**
	 * 根据条件查询功能(AC_FUNC)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<AcFunc> query(WhereCondition wc);

	/**
	 * 根据条件统计功能(AC_FUNC)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询功能(AC_FUNC)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public AcFunc loadByGuid(String guid);
}
