/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.om;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.om.OmBusiorg;

/**
 * 
 * 业务机构(OM_BUSIORG)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface OmBusiorgMapper extends BaseMapper<OmBusiorg>{

}
