/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.om;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.om.OmEmpPosition;

/**
 * 
 * 员工岗位对应关系(OM_EMP_POSITION)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface OmEmpPositionMapper extends BaseMapper<OmEmpPosition>{

}
