/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.dao.om;

import org.tis.tools.base.BaseMapper;
import org.tis.tools.model.po.om.OmEmpOrg;

/**
 * 
 * 员工隶属机构关系表(OM_EMP_ORG)的DAO
 * 
 * @author generated by tools:gen-dao
 *
 */
public interface OmEmpOrgMapper extends BaseMapper<OmEmpOrg>{

}
