
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcDatascope;
import org.tis.tools.rservice.ac.basic.IAcDatascopeRService;
import org.tis.tools.service.ac.AcDatascopeService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 数据范围权限(AC_DATASCOPE) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcDatascopeRService.class, timeout = 2000, document = "数据范围权限的基础远程服务")
public class AcDatascopeRServiceImpl implements IAcDatascopeRService {

	@Autowired
	AcDatascopeService acDatascopeService;

	@Override
	public void insert(AcDatascope t) {
		acDatascopeService.insert(t);
	}

	@Override
	public void update(AcDatascope t) {
		acDatascopeService.update(t);
	}

	@Override
	public void updateForce(AcDatascope t) {
		acDatascopeService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acDatascopeService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acDatascopeService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcDatascope t) {
		acDatascopeService.updateByCondition(wc,t);
	}

	@Override
	public List<AcDatascope> query(WhereCondition wc) {
		return acDatascopeService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acDatascopeService.count(wc);
	}

	@Override
	public AcDatascope loadByGuid(String guid) {
		return acDatascopeService.loadByGuid(guid);
	}

}
