
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcOperatorMenu;
import org.tis.tools.rservice.ac.basic.IAcOperatorMenuRService;
import org.tis.tools.service.ac.AcOperatorMenuService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 操作员重组菜单(AC_OPERATOR_MENU) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcOperatorMenuRService.class, timeout = 2000, document = "操作员重组菜单的基础远程服务")
public class AcOperatorMenuRServiceImpl implements IAcOperatorMenuRService {

	@Autowired
	AcOperatorMenuService acOperatorMenuService;

	@Override
	public void insert(AcOperatorMenu t) {
		acOperatorMenuService.insert(t);
	}

	@Override
	public void update(AcOperatorMenu t) {
		acOperatorMenuService.update(t);
	}

	@Override
	public void updateForce(AcOperatorMenu t) {
		acOperatorMenuService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acOperatorMenuService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acOperatorMenuService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcOperatorMenu t) {
		acOperatorMenuService.updateByCondition(wc,t);
	}

	@Override
	public List<AcOperatorMenu> query(WhereCondition wc) {
		return acOperatorMenuService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acOperatorMenuService.count(wc);
	}

	@Override
	public AcOperatorMenu loadByGuid(String guid) {
		return acOperatorMenuService.loadByGuid(guid);
	}

}
