
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcRoleFunc;
import org.tis.tools.rservice.ac.basic.IAcRoleFuncRService;
import org.tis.tools.service.ac.AcRoleFuncService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 权限集(角色)功能对应关系(AC_ROLE_FUNC) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcRoleFuncRService.class, timeout = 2000, document = "权限集(角色)功能对应关系的基础远程服务")
public class AcRoleFuncRServiceImpl implements IAcRoleFuncRService {

	@Autowired
	AcRoleFuncService acRoleFuncService;

	@Override
	public void insert(AcRoleFunc t) {
		acRoleFuncService.insert(t);
	}

	@Override
	public void update(AcRoleFunc t) {
		acRoleFuncService.update(t);
	}

	@Override
	public void updateForce(AcRoleFunc t) {
		acRoleFuncService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acRoleFuncService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acRoleFuncService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcRoleFunc t) {
		acRoleFuncService.updateByCondition(wc,t);
	}

	@Override
	public List<AcRoleFunc> query(WhereCondition wc) {
		return acRoleFuncService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acRoleFuncService.count(wc);
	}

	@Override
	public AcRoleFunc loadByGuid(String guid) {
		return acRoleFuncService.loadByGuid(guid);
	}

}
