/**
 * auto generated
 * Copyright (C) 2017 bronsp.com, All rights reserved.
 */
package org.tis.tools.model.po.sys;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Time;
import java.util.Date;

import org.tis.tools.common.utils.StringUtil;

/**
 * 
 * <pre>
 * 系统运行参数表
 * 模型文件 ： D:\tistools\tools-core-basic\model\ABF-mysql.erm
 * 业务域：sys
 * 模型：SYS_RUN_CONFIG 系统运行参数表
 *
 * 运行期系统参数表，以三段式结构进行参数存储
 *
 * </pre>
 * @author generated by tools:gen-dao
 *
 */
public class SysRunConfig implements Serializable {

 	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	/** 对应的数据库表名称 */
	public static final String TABLE_NAME = "SYS_RUN_CONFIG" ; 
	/* SYS_RUN_CONFIG table's columns definition */
	/** GUID ：数据主键<br/><br/>全局唯一标识符（GUID，Globally Unique Identifier），系统自动生成； */
	public static final String COLUMN_GUID = "guid" ; 
	/** GUID_APP ：应用系统GUID<br/><br/>用于表识一组参数属于某个应用系统 。下拉AC_APP表记录 */
	public static final String COLUMN_GUID_APP = "guid_app" ; 
	/** GROUP_NAME ：参数组别<br/><br/>参数组别，手工输入 */
	public static final String COLUMN_GROUP_NAME = "group_name" ; 
	/** KEY_NAME ：参数键<br/><br/>参数键名称，手工输入 */
	public static final String COLUMN_KEY_NAME = "key_name" ; 
	/** VALUE_FROM ：值来源类型<br/><br/>H：手工指定 或者选择业务字典的GUID（此时存储业务字典名称 SYS_DICT.DICT_KEY) */
	public static final String COLUMN_VALUE_FROM = "value_from" ; 
	/** VALUE ：参数值<br/><br/>当value_from为H时，手工输入任意有效字符串； 当value_from为业务字典时，下拉选择； */
	public static final String COLUMN_VALUE = "value" ; 
	/** DESCRIPTION ：参数描述<br/><br/>参数功能描述 */
	public static final String COLUMN_DESCRIPTION = "description" ; 
	/** 对应的类名 */
	public static final String CLASS_NAME = "org.tis.tools.model.po.sys.SysRunConfig";
    /** GUID字段名<br/> */
    public static final String NAME_GUID = "数据主键" ;
    /** GUID_APP字段名<br/> */
    public static final String NAME_GUID_APP = "应用系统GUID" ;
    /** GROUP_NAME字段名<br/> */
    public static final String NAME_GROUP_NAME = "参数组别" ;
    /** KEY_NAME字段名<br/> */
    public static final String NAME_KEY_NAME = "参数键" ;
    /** VALUE_FROM字段名<br/> */
    public static final String NAME_VALUE_FROM = "值来源类型" ;
    /** VALUE字段名<br/> */
    public static final String NAME_VALUE = "参数值" ;
    /** DESCRIPTION字段名<br/> */
    public static final String NAME_DESCRIPTION = "参数描述" ;
	
	
	/** 字段类型：varchar<br/>字段名：数据主键<br/>描述：全局唯一标识符（GUID，Globally Unique Identifier），系统自动生成； */
	private String guid ;
	
	/** 字段类型：varchar<br/>字段名：应用系统GUID<br/>描述：用于表识一组参数属于某个应用系统 。下拉AC_APP表记录 */
	private String guidApp ;
	
	/** 字段类型：varchar<br/>字段名：参数组别<br/>描述：参数组别，手工输入 */
	private String groupName ;
	
	/** 字段类型：varchar<br/>字段名：参数键<br/>描述：参数键名称，手工输入 */
	private String keyName ;
	
	/** 字段类型：varchar<br/>字段名：值来源类型<br/>描述：H：手工指定 或者选择业务字典的GUID（此时存储业务字典名称 SYS_DICT.DICT_KEY) */
	private String valueFrom ;
	
	/** 字段类型：varchar<br/>字段名：参数值<br/>描述：当value_from为H时，手工输入任意有效字符串； 当value_from为业务字典时，下拉选择； */
	private String value ;
	
	/** 字段类型：varchar<br/>字段名：参数描述<br/>描述：参数功能描述 */
	private String description ;

	/**
	* Default Constructor
	*/
	public SysRunConfig() {
	}

	
	/**
	 * Set the 数据主键.
	 * 
	 * @param guid
	 *            数据主键
	 */
	public void setGuid(String guid) {
 		this.guid = guid == null ? null : guid.trim() ;
    }
    
    /**
	 * Get the 数据主键.
	 * 
	 * @return 数据主键
	 */
	public String getGuid(){
		return this.guid ;
    }
	
	/**
	 * Set the 应用系统GUID.
	 * 
	 * @param guidApp
	 *            应用系统GUID
	 */
	public void setGuidApp(String guidApp) {
 		this.guidApp = guidApp == null ? null : guidApp.trim() ;
    }
    
    /**
	 * Get the 应用系统GUID.
	 * 
	 * @return 应用系统GUID
	 */
	public String getGuidApp(){
		return this.guidApp ;
    }
	
	/**
	 * Set the 参数组别.
	 * 
	 * @param groupName
	 *            参数组别
	 */
	public void setGroupName(String groupName) {
 		this.groupName = groupName == null ? null : groupName.trim() ;
    }
    
    /**
	 * Get the 参数组别.
	 * 
	 * @return 参数组别
	 */
	public String getGroupName(){
		return this.groupName ;
    }
	
	/**
	 * Set the 参数键.
	 * 
	 * @param keyName
	 *            参数键
	 */
	public void setKeyName(String keyName) {
 		this.keyName = keyName == null ? null : keyName.trim() ;
    }
    
    /**
	 * Get the 参数键.
	 * 
	 * @return 参数键
	 */
	public String getKeyName(){
		return this.keyName ;
    }
	
	/**
	 * Set the 值来源类型.
	 * 
	 * @param valueFrom
	 *            值来源类型
	 */
	public void setValueFrom(String valueFrom) {
 		this.valueFrom = valueFrom == null ? null : valueFrom.trim() ;
    }
    
    /**
	 * Get the 值来源类型.
	 * 
	 * @return 值来源类型
	 */
	public String getValueFrom(){
		return this.valueFrom ;
    }
	
	/**
	 * Set the 参数值.
	 * 
	 * @param value
	 *            参数值
	 */
	public void setValue(String value) {
 		this.value = value == null ? null : value.trim() ;
    }
    
    /**
	 * Get the 参数值.
	 * 
	 * @return 参数值
	 */
	public String getValue(){
		return this.value ;
    }
	
	/**
	 * Set the 参数描述.
	 * 
	 * @param description
	 *            参数描述
	 */
	public void setDescription(String description) {
 		this.description = description == null ? null : description.trim() ;
    }
    
    /**
	 * Get the 参数描述.
	 * 
	 * @return 参数描述
	 */
	public String getDescription(){
		return this.description ;
    }
	
	public String toString(){
		return StringUtil.toString(this) ; 
	}
}