
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.sys.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.sys.SysChannelCtl;
import org.tis.tools.rservice.sys.basic.ISysChannelCtlRService;
import org.tis.tools.service.sys.SysChannelCtlService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 渠道参数控制表(SYS_CHANNEL_CTL) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "sys", version = "1.0", interfaceClass = ISysChannelCtlRService.class, timeout = 2000, document = "渠道参数控制表的基础远程服务")
public class SysChannelCtlRServiceImpl implements ISysChannelCtlRService {

	@Autowired
	SysChannelCtlService sysChannelCtlService;

	@Override
	public void insert(SysChannelCtl t) {
		sysChannelCtlService.insert(t);
	}

	@Override
	public void update(SysChannelCtl t) {
		sysChannelCtlService.update(t);
	}

	@Override
	public void updateForce(SysChannelCtl t) {
		sysChannelCtlService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		sysChannelCtlService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		sysChannelCtlService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, SysChannelCtl t) {
		sysChannelCtlService.updateByCondition(wc,t);
	}

	@Override
	public List<SysChannelCtl> query(WhereCondition wc) {
		return sysChannelCtlService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return sysChannelCtlService.count(wc);
	}

	@Override
	public SysChannelCtl loadByGuid(String guid) {
		return sysChannelCtlService.loadByGuid(guid);
	}

}
