
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.sys.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.sys.SysDictItem;
import org.tis.tools.rservice.sys.basic.ISysDictItemRService;
import org.tis.tools.service.sys.SysDictItemService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 业务字典项(SYS_DICT_ITEM) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "sys", version = "1.0", interfaceClass = ISysDictItemRService.class, timeout = 2000, document = "业务字典项的基础远程服务")
public class SysDictItemRServiceImpl implements ISysDictItemRService {

	@Autowired
	SysDictItemService sysDictItemService;

	@Override
	public void insert(SysDictItem t) {
		sysDictItemService.insert(t);
	}

	@Override
	public void update(SysDictItem t) {
		sysDictItemService.update(t);
	}

	@Override
	public void updateForce(SysDictItem t) {
		sysDictItemService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		sysDictItemService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		sysDictItemService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, SysDictItem t) {
		sysDictItemService.updateByCondition(wc,t);
	}

	@Override
	public List<SysDictItem> query(WhereCondition wc) {
		return sysDictItemService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return sysDictItemService.count(wc);
	}

	@Override
	public SysDictItem loadByGuid(String guid) {
		return sysDictItemService.loadByGuid(guid);
	}

}
