
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.sys.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.sys.SysDict;
import org.tis.tools.rservice.sys.basic.ISysDictRService;
import org.tis.tools.service.sys.SysDictService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 业务字典(SYS_DICT) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "sys", version = "1.0", interfaceClass = ISysDictRService.class, timeout = 2000, document = "业务字典的基础远程服务")
public class SysDictRServiceImpl implements ISysDictRService {

	@Autowired
	SysDictService sysDictService;

	@Override
	public void insert(SysDict t) {
		sysDictService.insert(t);
	}

	@Override
	public void update(SysDict t) {
		sysDictService.update(t);
	}

	@Override
	public void updateForce(SysDict t) {
		sysDictService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		sysDictService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		sysDictService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, SysDict t) {
		sysDictService.updateByCondition(wc,t);
	}

	@Override
	public List<SysDict> query(WhereCondition wc) {
		return sysDictService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return sysDictService.count(wc);
	}

	@Override
	public SysDict loadByGuid(String guid) {
		return sysDictService.loadByGuid(guid);
	}

}
