
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.sys.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.sys.SysErrCode;
import org.tis.tools.rservice.sys.basic.ISysErrCodeRService;
import org.tis.tools.service.sys.SysErrCodeService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 错误码表(SYS_ERR_CODE) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "sys", version = "1.0", interfaceClass = ISysErrCodeRService.class, timeout = 2000, document = "错误码表的基础远程服务")
public class SysErrCodeRServiceImpl implements ISysErrCodeRService {

	@Autowired
	SysErrCodeService sysErrCodeService;

	@Override
	public void insert(SysErrCode t) {
		sysErrCodeService.insert(t);
	}

	@Override
	public void update(SysErrCode t) {
		sysErrCodeService.update(t);
	}

	@Override
	public void updateForce(SysErrCode t) {
		sysErrCodeService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		sysErrCodeService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		sysErrCodeService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, SysErrCode t) {
		sysErrCodeService.updateByCondition(wc,t);
	}

	@Override
	public List<SysErrCode> query(WhereCondition wc) {
		return sysErrCodeService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return sysErrCodeService.count(wc);
	}

	@Override
	public SysErrCode loadByGuid(String guid) {
		return sysErrCodeService.loadByGuid(guid);
	}

}
