
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.sys.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.sys.SysTest;
import org.tis.tools.rservice.sys.basic.ISysTestRService;
import org.tis.tools.service.sys.SysTestService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 测试(SYS_TEST) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "sys", version = "1.0", interfaceClass = ISysTestRService.class, timeout = 2000, document = "测试的基础远程服务")
public class SysTestRServiceImpl implements ISysTestRService {

	@Autowired
	SysTestService sysTestService;

	@Override
	public void insert(SysTest t) {
		sysTestService.insert(t);
	}

	@Override
	public void update(SysTest t) {
		sysTestService.update(t);
	}

	@Override
	public void updateForce(SysTest t) {
		sysTestService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		sysTestService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		sysTestService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, SysTest t) {
		sysTestService.updateByCondition(wc,t);
	}

	@Override
	public List<SysTest> query(WhereCondition wc) {
		return sysTestService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return sysTestService.count(wc);
	}

	@Override
	public SysTest loadByGuid(String guid) {
		return sysTestService.loadByGuid(guid);
	}

}
