
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl.basic;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlPromoting;

 
/**
 * <pre>
 * 营销流水(JNL_PROMOTING)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IJnlPromotingRService {
	
	/**
	 * 新增营销流水(JNL_PROMOTING)
	 * @param t 新记录
	 */
	public void insert(JnlPromoting t);

	/**
	 * 更新营销流水(JNL_PROMOTING),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(JnlPromoting t);

	/**
	 * 强制更新营销流水(JNL_PROMOTING)
	 * @param t 新值
	 */
	public void updateForce(JnlPromoting t);

	/**
	 * 删除营销流水(JNL_PROMOTING)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除营销流水(JNL_PROMOTING)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新营销流水(JNL_PROMOTING)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, JnlPromoting t);

	/**
	 * 根据条件查询营销流水(JNL_PROMOTING)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<JnlPromoting> query(WhereCondition wc);

	/**
	 * 根据条件统计营销流水(JNL_PROMOTING)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询营销流水(JNL_PROMOTING)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public JnlPromoting loadByGuid(String guid);
}
