
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.om;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.om.OmEmpGroup;
import org.tis.tools.rservice.om.IOmEmpGroupRService;
import org.tis.tools.service.om.OmEmpGroupService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 人员工作组对应关系(OM_EMP_GROUP) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "om", version = "1.0", interfaceClass = IOmEmpGroupRService.class, timeout = 2000, document = "人员工作组对应关系的基础远程服务")
public class OmEmpGroupRServiceImpl implements IOmEmpGroupRService {

	@Autowired
	OmEmpGroupService omEmpGroupService;

	@Override
	public void insert(OmEmpGroup t) {
		omEmpGroupService.insert(t);
	}

	@Override
	public void update(OmEmpGroup t) {
		omEmpGroupService.update(t);
	}

	@Override
	public void updateForce(OmEmpGroup t) {
		omEmpGroupService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		omEmpGroupService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		omEmpGroupService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, OmEmpGroup t) {
		omEmpGroupService.updateByCondition(wc,t);
	}

	@Override
	public List<OmEmpGroup> query(WhereCondition wc) {
		return omEmpGroupService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return omEmpGroupService.count(wc);
	}

	@Override
	public OmEmpGroup loadByGuid(String guid) {
		return omEmpGroupService.loadByGuid(guid);
	}

}
