
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlHosttransMsg;
import org.tis.tools.rservice.jnl.basic.IJnlHosttransMsgRService;
import org.tis.tools.service.jnl.JnlHosttransMsgService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 主机交易报文(JNL_HOSTTRANS_MSG) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "jnl", version = "1.0", interfaceClass = IJnlHosttransMsgRService.class, timeout = 2000, document = "主机交易报文的基础远程服务")
public class JnlHosttransMsgRServiceImpl implements IJnlHosttransMsgRService {

	@Autowired
	JnlHosttransMsgService jnlHosttransMsgService;

	@Override
	public void insert(JnlHosttransMsg t) {
		jnlHosttransMsgService.insert(t);
	}

	@Override
	public void update(JnlHosttransMsg t) {
		jnlHosttransMsgService.update(t);
	}

	@Override
	public void updateForce(JnlHosttransMsg t) {
		jnlHosttransMsgService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		jnlHosttransMsgService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		jnlHosttransMsgService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, JnlHosttransMsg t) {
		jnlHosttransMsgService.updateByCondition(wc,t);
	}

	@Override
	public List<JnlHosttransMsg> query(WhereCondition wc) {
		return jnlHosttransMsgService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return jnlHosttransMsgService.count(wc);
	}

	@Override
	public JnlHosttransMsg loadByGuid(String guid) {
		return jnlHosttransMsgService.loadByGuid(guid);
	}

}
