
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlTransFeature;
import org.tis.tools.rservice.jnl.basic.IJnlTransFeatureRService;
import org.tis.tools.service.jnl.JnlTransFeatureService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 交易业务要素(JNL_TRANS_FEATURE) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "jnl", version = "1.0", interfaceClass = IJnlTransFeatureRService.class, timeout = 2000, document = "交易业务要素的基础远程服务")
public class JnlTransFeatureRServiceImpl implements IJnlTransFeatureRService {

	@Autowired
	JnlTransFeatureService jnlTransFeatureService;

	@Override
	public void insert(JnlTransFeature t) {
		jnlTransFeatureService.insert(t);
	}

	@Override
	public void update(JnlTransFeature t) {
		jnlTransFeatureService.update(t);
	}

	@Override
	public void updateForce(JnlTransFeature t) {
		jnlTransFeatureService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		jnlTransFeatureService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		jnlTransFeatureService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, JnlTransFeature t) {
		jnlTransFeatureService.updateByCondition(wc,t);
	}

	@Override
	public List<JnlTransFeature> query(WhereCondition wc) {
		return jnlTransFeatureService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return jnlTransFeatureService.count(wc);
	}

	@Override
	public JnlTransFeature loadByGuid(String guid) {
		return jnlTransFeatureService.loadByGuid(guid);
	}

}
