
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlTransPrinted;
import org.tis.tools.rservice.jnl.basic.IJnlTransPrintedRService;
import org.tis.tools.service.jnl.JnlTransPrintedService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 交易输出凭证流水(JNL_TRANS_PRINTED) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "jnl", version = "1.0", interfaceClass = IJnlTransPrintedRService.class, timeout = 2000, document = "交易输出凭证流水的基础远程服务")
public class JnlTransPrintedRServiceImpl implements IJnlTransPrintedRService {

	@Autowired
	JnlTransPrintedService jnlTransPrintedService;

	@Override
	public void insert(JnlTransPrinted t) {
		jnlTransPrintedService.insert(t);
	}

	@Override
	public void update(JnlTransPrinted t) {
		jnlTransPrintedService.update(t);
	}

	@Override
	public void updateForce(JnlTransPrinted t) {
		jnlTransPrintedService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		jnlTransPrintedService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		jnlTransPrintedService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, JnlTransPrinted t) {
		jnlTransPrintedService.updateByCondition(wc,t);
	}

	@Override
	public List<JnlTransPrinted> query(WhereCondition wc) {
		return jnlTransPrintedService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return jnlTransPrintedService.count(wc);
	}

	@Override
	public JnlTransPrinted loadByGuid(String guid) {
		return jnlTransPrintedService.loadByGuid(guid);
	}

}
