
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlTransCtx;
import org.tis.tools.rservice.jnl.basic.IJnlTransCtxRService;
import org.tis.tools.service.jnl.JnlTransCtxService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 交易上下文(JNL_TRANS_CTX) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "jnl", version = "1.0", interfaceClass = IJnlTransCtxRService.class, timeout = 2000, document = "交易上下文的基础远程服务")
public class JnlTransCtxRServiceImpl implements IJnlTransCtxRService {

	@Autowired
	JnlTransCtxService jnlTransCtxService;

	@Override
	public void insert(JnlTransCtx t) {
		jnlTransCtxService.insert(t);
	}

	@Override
	public void update(JnlTransCtx t) {
		jnlTransCtxService.update(t);
	}

	@Override
	public void updateForce(JnlTransCtx t) {
		jnlTransCtxService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		jnlTransCtxService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		jnlTransCtxService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, JnlTransCtx t) {
		jnlTransCtxService.updateByCondition(wc,t);
	}

	@Override
	public List<JnlTransCtx> query(WhereCondition wc) {
		return jnlTransCtxService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return jnlTransCtxService.count(wc);
	}

	@Override
	public JnlTransCtx loadByGuid(String guid) {
		return jnlTransCtxService.loadByGuid(guid);
	}

}
