/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.ac;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.ac.AcConfigMapper;
import org.tis.tools.model.po.ac.AcConfig;


/**
 * 个性化配置(AC_CONFIG)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class AcConfigService {

	@Autowired
	AcConfigMapper acConfigMapper;
	
    public void insert(AcConfig t){
    	acConfigMapper.insert(t);
    }
    
    public void update(AcConfig t){
    	acConfigMapper.update(t); 
    }
   
    public void updateForce(AcConfig t){
    	acConfigMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	acConfigMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	acConfigMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,AcConfig t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	acConfigMapper.updateByCondition(map); 
    }

    public List<AcConfig> query(WhereCondition wc){
    	return acConfigMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return acConfigMapper.count(wc);
    }
   
    public AcConfig loadByGuid(String guid){
    	return acConfigMapper.loadByGuid(guid);
    }
}
