/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.ac;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.ac.AcFuncBehaviorMapper;
import org.tis.tools.model.po.ac.AcFuncBehavior;


/**
 * 功能操作行为(AC_FUNC_BEHAVIOR)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class AcFuncBehaviorService {

	@Autowired
	AcFuncBehaviorMapper acFuncBehaviorMapper;
	
    public void insert(AcFuncBehavior t){
    	acFuncBehaviorMapper.insert(t);
    }
    
    public void update(AcFuncBehavior t){
    	acFuncBehaviorMapper.update(t); 
    }
   
    public void updateForce(AcFuncBehavior t){
    	acFuncBehaviorMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	acFuncBehaviorMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	acFuncBehaviorMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,AcFuncBehavior t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	acFuncBehaviorMapper.updateByCondition(map); 
    }

    public List<AcFuncBehavior> query(WhereCondition wc){
    	return acFuncBehaviorMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return acFuncBehaviorMapper.count(wc);
    }
   
    public AcFuncBehavior loadByGuid(String guid){
    	return acFuncBehaviorMapper.loadByGuid(guid);
    }
}
