/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.ac;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.ac.AcFuncBhvMapper;
import org.tis.tools.model.po.ac.AcFuncBhv;


/**
 * 功能操作行为(AC_FUNC_BHV)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class AcFuncBhvService {

	@Autowired
	AcFuncBhvMapper acFuncBhvMapper;
	
    public void insert(AcFuncBhv t){
    	acFuncBhvMapper.insert(t);
    }
    
    public void update(AcFuncBhv t){
    	acFuncBhvMapper.update(t); 
    }
   
    public void updateForce(AcFuncBhv t){
    	acFuncBhvMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	acFuncBhvMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	acFuncBhvMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,AcFuncBhv t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	acFuncBhvMapper.updateByCondition(map); 
    }

    public List<AcFuncBhv> query(WhereCondition wc){
    	return acFuncBhvMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return acFuncBhvMapper.count(wc);
    }
   
    public AcFuncBhv loadByGuid(String guid){
    	return acFuncBhvMapper.loadByGuid(guid);
    }
}
