/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.ac;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.tis.tools.base.WhereCondition;

import org.tis.tools.dao.ac.AcRoleDatascopeMapper;
import org.tis.tools.model.po.ac.AcRoleDatascope;


/**
 * 角色数据范围权限对应(AC_ROLE_DATASCOPE)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class AcRoleDatascopeService {

	@Autowired
	AcRoleDatascopeMapper acRoleDatascopeMapper;
	
    public void insert(AcRoleDatascope t){
    	acRoleDatascopeMapper.insert(t);
    }
    
    public void update(AcRoleDatascope t){
    	acRoleDatascopeMapper.update(t); 
    }
   
    public void updateForce(AcRoleDatascope t){
    	acRoleDatascopeMapper.updateForce(t); 
    }
   
    public void delete(String guid){
    	acRoleDatascopeMapper.delete(guid);
    }
   
    public void deleteByCondition(WhereCondition wc){
    	acRoleDatascopeMapper.deleteByCondition(wc); 
    }
	
	public void updateByCondition(WhereCondition wc,AcRoleDatascope t){
    	Map map  = new HashMap();
    	map.put("domain", t);
    	map.put("wc", wc);
    	acRoleDatascopeMapper.updateByCondition(map); 
    }

    public List<AcRoleDatascope> query(WhereCondition wc){
    	return acRoleDatascopeMapper.query(wc); 
    }
    
    public int count(WhereCondition wc){
    	return acRoleDatascopeMapper.count(wc);
    }
   
    public AcRoleDatascope loadByGuid(String guid){
    	return acRoleDatascopeMapper.loadByGuid(guid);
    }
}
