/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.ac;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.dao.ac.AcAppMapper;
import org.tis.tools.dao.ac.ApplicationMapper;
import org.tis.tools.model.po.ac.AcApp;
import org.tis.tools.model.vo.ac.AcAppVo;


/**
 * 应用系统(AC_APP)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class ApplicationService {

	@Autowired
	ApplicationMapper applitionMapper;
	
   

    public List<AcAppVo> query(WhereCondition wc){
    	return applitionMapper.query(wc); 
    }
    
}
