/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.service.ac;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.dao.ac.AcAppMapper;
import org.tis.tools.dao.ac.ApplicationMapper;
import org.tis.tools.model.po.ac.AcApp;
import org.tis.tools.model.vo.ac.AcAppVo;
import org.tis.tools.model.vo.ac.AcFuncVo;


/**
 * 应用系统(AC_APP)数据的基础业务逻辑
 * @author by generated by tools:gen-dao
 *
 */
@Service
public class ApplicationService {

	@Autowired
	ApplicationMapper applitionMapper;
	
   

    public List<AcAppVo> queryAcAppVo(WhereCondition wc){
    	return applitionMapper.queryAcAppVo(wc); 
    }
    /**
	 * 根据条件查询功能(AC_FUNC)
	 * @param guid 条件
	 * @return 满足条件的记录
	 */
	public List<AcFuncVo> queryAcFuncVo(WhereCondition wc){
		return applitionMapper.queryAcFuncVo(wc);
	};
    
}
