
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcFunc;
import org.tis.tools.rservice.ac.IAcFuncRService;
import org.tis.tools.service.ac.AcFuncService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 功能(AC_FUNC) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcFuncRService.class, timeout = 2000, document = "功能的基础远程服务")
public class AcFuncRServiceImpl implements IAcFuncRService {

	@Autowired
	AcFuncService acFuncService;

	@Override
	public void insert(AcFunc t) {
		acFuncService.insert(t);
	}

	@Override
	public void update(AcFunc t) {
		acFuncService.update(t);
	}

	@Override
	public void updateForce(AcFunc t) {
		acFuncService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acFuncService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acFuncService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcFunc t) {
		acFuncService.updateByCondition(wc,t);
	}

	@Override
	public List<AcFunc> query(WhereCondition wc) {
		return acFuncService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acFuncService.count(wc);
	}

	@Override
	public AcFunc loadByGuid(String guid) {
		return acFuncService.loadByGuid(guid);
	}

}
