
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcPartyRole;
import org.tis.tools.rservice.ac.IAcPartyRoleRService;
import org.tis.tools.service.ac.AcPartyRoleService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 组织对象与角色对应关系(AC_PARTY_ROLE) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcPartyRoleRService.class, timeout = 2000, document = "组织对象与角色对应关系的基础远程服务")
public class AcPartyRoleRServiceImpl implements IAcPartyRoleRService {

	@Autowired
	AcPartyRoleService acPartyRoleService;

	@Override
	public void insert(AcPartyRole t) {
		acPartyRoleService.insert(t);
	}

	@Override
	public void update(AcPartyRole t) {
		acPartyRoleService.update(t);
	}

	@Override
	public void updateForce(AcPartyRole t) {
		acPartyRoleService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acPartyRoleService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acPartyRoleService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcPartyRole t) {
		acPartyRoleService.updateByCondition(wc,t);
	}

	@Override
	public List<AcPartyRole> query(WhereCondition wc) {
		return acPartyRoleService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acPartyRoleService.count(wc);
	}

	@Override
	public AcPartyRole loadByGuid(String guid) {
		return acPartyRoleService.loadByGuid(guid);
	}

}
