
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcRoleEntity;
import org.tis.tools.rservice.ac.IAcRoleEntityRService;
import org.tis.tools.service.ac.AcRoleEntityService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 角色实体关系(AC_ROLE_ENTITY) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcRoleEntityRService.class, timeout = 2000, document = "角色实体关系的基础远程服务")
public class AcRoleEntityRServiceImpl implements IAcRoleEntityRService {

	@Autowired
	AcRoleEntityService acRoleEntityService;

	@Override
	public void insert(AcRoleEntity t) {
		acRoleEntityService.insert(t);
	}

	@Override
	public void update(AcRoleEntity t) {
		acRoleEntityService.update(t);
	}

	@Override
	public void updateForce(AcRoleEntity t) {
		acRoleEntityService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acRoleEntityService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acRoleEntityService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcRoleEntity t) {
		acRoleEntityService.updateByCondition(wc,t);
	}

	@Override
	public List<AcRoleEntity> query(WhereCondition wc) {
		return acRoleEntityService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acRoleEntityService.count(wc);
	}

	@Override
	public AcRoleEntity loadByGuid(String guid) {
		return acRoleEntityService.loadByGuid(guid);
	}

}
