
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.ac;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.ac.AcRoleEntityfield;
import org.tis.tools.rservice.ac.IAcRoleEntityfieldRService;
import org.tis.tools.service.ac.AcRoleEntityfieldService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 角色与实体属性关系(AC_ROLE_ENTITYFIELD) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "ac", version = "1.0", interfaceClass = IAcRoleEntityfieldRService.class, timeout = 2000, document = "角色与实体属性关系的基础远程服务")
public class AcRoleEntityfieldRServiceImpl implements IAcRoleEntityfieldRService {

	@Autowired
	AcRoleEntityfieldService acRoleEntityfieldService;

	@Override
	public void insert(AcRoleEntityfield t) {
		acRoleEntityfieldService.insert(t);
	}

	@Override
	public void update(AcRoleEntityfield t) {
		acRoleEntityfieldService.update(t);
	}

	@Override
	public void updateForce(AcRoleEntityfield t) {
		acRoleEntityfieldService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		acRoleEntityfieldService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		acRoleEntityfieldService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, AcRoleEntityfield t) {
		acRoleEntityfieldService.updateByCondition(wc,t);
	}

	@Override
	public List<AcRoleEntityfield> query(WhereCondition wc) {
		return acRoleEntityfieldService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return acRoleEntityfieldService.count(wc);
	}

	@Override
	public AcRoleEntityfield loadByGuid(String guid) {
		return acRoleEntityfieldService.loadByGuid(guid);
	}

}
