
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlContactLog;

 
/**
 * <pre>
 * 客户接触日志(JNL_CONTACT_LOG)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IJnlContactLogRService {
	
	/**
	 * 新增客户接触日志(JNL_CONTACT_LOG)
	 * @param t 新记录
	 */
	public void insert(JnlContactLog t);

	/**
	 * 更新客户接触日志(JNL_CONTACT_LOG),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(JnlContactLog t);

	/**
	 * 强制更新客户接触日志(JNL_CONTACT_LOG)
	 * @param t 新值
	 */
	public void updateForce(JnlContactLog t);

	/**
	 * 删除客户接触日志(JNL_CONTACT_LOG)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除客户接触日志(JNL_CONTACT_LOG)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新客户接触日志(JNL_CONTACT_LOG)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, JnlContactLog t);

	/**
	 * 根据条件查询客户接触日志(JNL_CONTACT_LOG)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<JnlContactLog> query(WhereCondition wc);

	/**
	 * 根据条件统计客户接触日志(JNL_CONTACT_LOG)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询客户接触日志(JNL_CONTACT_LOG)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public JnlContactLog loadByGuid(String guid);
}
