
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.JnlTellerTrace;

 
/**
 * <pre>
 * 柜员操作日志(JNL_TELLER_TRACE)的基础远程服务接口定义
 * </pre>
 *
 * @autor generated by tools:gen-dao
 *
 */
public interface IJnlTellerTraceRService {
	
	/**
	 * 新增柜员操作日志(JNL_TELLER_TRACE)
	 * @param t 新记录
	 */
	public void insert(JnlTellerTrace t);

	/**
	 * 更新柜员操作日志(JNL_TELLER_TRACE),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(JnlTellerTrace t);

	/**
	 * 强制更新柜员操作日志(JNL_TELLER_TRACE)
	 * @param t 新值
	 */
	public void updateForce(JnlTellerTrace t);

	/**
	 * 删除柜员操作日志(JNL_TELLER_TRACE)
	 * @param guid 记录guid
	 */
	public void delete(String guid);

	/**
	 * 根据条件删除柜员操作日志(JNL_TELLER_TRACE)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新柜员操作日志(JNL_TELLER_TRACE)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, JnlTellerTrace t);

	/**
	 * 根据条件查询柜员操作日志(JNL_TELLER_TRACE)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<JnlTellerTrace> query(WhereCondition wc);

	/**
	 * 根据条件统计柜员操作日志(JNL_TELLER_TRACE)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询柜员操作日志(JNL_TELLER_TRACE)记录
	 * @param guid 记录guid
	 * @return 匹配的记录
	 */
	public JnlTellerTrace loadByGuid(String guid);
}
