
/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.TbJnlTrans;

 
/**
 * <pre>
 * auto generated by mvn bronsp:gen-dao , don't change</br>
 * 交易流水(tb_jnl_trans)的基础远程服务接口定义
 * 模型：交易流水 tb_jnl_trans
 * 描述：交易流水表
 * 业务域：jnl
 * 定义文件：/Users/megapro/Develop/tis/tools/tools-core/model/model-jnl.xml
 * </pre>
 */
public interface ITbJnlTransRService {
	
	/**
	 * 新增交易流水(tb_jnl_trans)
	 * @param t 新记录
	 */
	public void insert(TbJnlTrans t);

	/**
	 * 更新交易流水(tb_jnl_trans),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(TbJnlTrans t);

	/**
	 * 强制更新交易流水(tb_jnl_trans)
	 * @param t 新值
	 */
	public void updateForce(TbJnlTrans t);

	/**
	 * 删除交易流水(tb_jnl_trans)
	 * @param id 记录id
	 */
	public void delete(String id);

	/**
	 * 根据条件删除交易流水(tb_jnl_trans)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新交易流水(tb_jnl_trans)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, TbJnlTrans t);

	/**
	 * 根据条件查询交易流水(tb_jnl_trans)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<TbJnlTrans> query(WhereCondition wc);

	/**
	 * 根据条件统计交易流水(tb_jnl_trans)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询交易流水(tb_jnl_trans)记录
	 * @param id 记录id
	 * @return 匹配的记录
	 */
	public TbJnlTrans loadById(String id);
}
