
/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.TbJnlQueue;

 
/**
 * <pre>
 * auto generated by mvn bronsp:gen-dao , don't change</br>
 * 排队流水(tb_jnl_queue)的基础远程服务接口定义
 * 模型：排队流水 tb_jnl_queue
 * 描述：排队流水表
 * 业务域：jnl
 * 定义文件：/Users/megapro/Develop/tis/tools/tools-core/model/model-jnl.xml
 * </pre>
 */
public interface ITbJnlQueueRService {
	
	/**
	 * 新增排队流水(tb_jnl_queue)
	 * @param t 新记录
	 */
	public void insert(TbJnlQueue t);

	/**
	 * 更新排队流水(tb_jnl_queue),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(TbJnlQueue t);

	/**
	 * 强制更新排队流水(tb_jnl_queue)
	 * @param t 新值
	 */
	public void updateForce(TbJnlQueue t);

	/**
	 * 删除排队流水(tb_jnl_queue)
	 * @param id 记录id
	 */
	public void delete(String id);

	/**
	 * 根据条件删除排队流水(tb_jnl_queue)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新排队流水(tb_jnl_queue)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, TbJnlQueue t);

	/**
	 * 根据条件查询排队流水(tb_jnl_queue)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<TbJnlQueue> query(WhereCondition wc);

	/**
	 * 根据条件统计排队流水(tb_jnl_queue)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询排队流水(tb_jnl_queue)记录
	 * @param id 记录id
	 * @return 匹配的记录
	 */
	public TbJnlQueue loadById(String id);
}
