
/**
 * auto generated
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.jnl;

import java.util.List;

import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.jnl.TbUnique;

 
/**
 * <pre>
 * auto generated by mvn bronsp:gen-dao , don't change</br>
 * 序号表(tb_unique)的基础远程服务接口定义
 * 模型：序号表 tb_unique
 * 描述：标记某种序号使用数
 * 业务域：jnl
 * 定义文件：/Users/megapro/Develop/tis/tools/tools-core/model/model-jnl.xml
 * </pre>
 */
public interface ITbUniqueRService {
	
	/**
	 * 新增序号表(tb_unique)
	 * @param t 新记录
	 */
	public void insert(TbUnique t);

	/**
	 * 更新序号表(tb_unique),只修改t对象有值的字段
	 * @param t 新值
	 */
	public void update(TbUnique t);

	/**
	 * 强制更新序号表(tb_unique)
	 * @param t 新值
	 */
	public void updateForce(TbUnique t);

	/**
	 * 删除序号表(tb_unique)
	 * @param id 记录id
	 */
	public void delete(String id);

	/**
	 * 根据条件删除序号表(tb_unique)
	 * @param wc 条件
	 */
	public void deleteByCondition(WhereCondition wc);

	/**
	 * 根据条件更新序号表(tb_unique)
	 * @param wc 条件
	 * @param t 新值
	 */
	public void updateByCondition(WhereCondition wc, TbUnique t);

	/**
	 * 根据条件查询序号表(tb_unique)
	 * @param wc 条件
	 * @return 满足条件的记录list
	 */
	public List<TbUnique> query(WhereCondition wc);

	/**
	 * 根据条件统计序号表(tb_unique)记录数
	 * @param wc 条件
	 * @return 记录数
	 */
	public int count(WhereCondition wc);

	/**
	 * 根据id查询序号表(tb_unique)记录
	 * @param id 记录id
	 * @return 匹配的记录
	 */
	public TbUnique loadById(String id);
}
