
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.log.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.log.LogAbfOperator;
import org.tis.tools.rservice.log.basic.ILogAbfOperatorRService;
import org.tis.tools.service.log.LogAbfOperatorService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 操作日志(LOG_ABF_OPERATOR) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "log", version = "1.0", interfaceClass = ILogAbfOperatorRService.class, timeout = 2000, document = "操作日志的基础远程服务")
public class LogAbfOperatorRServiceImpl implements ILogAbfOperatorRService {

	@Autowired
	LogAbfOperatorService logAbfOperatorService;

	@Override
	public void insert(LogAbfOperator t) {
		logAbfOperatorService.insert(t);
	}

	@Override
	public void update(LogAbfOperator t) {
		logAbfOperatorService.update(t);
	}

	@Override
	public void updateForce(LogAbfOperator t) {
		logAbfOperatorService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		logAbfOperatorService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		logAbfOperatorService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, LogAbfOperator t) {
		logAbfOperatorService.updateByCondition(wc,t);
	}

	@Override
	public List<LogAbfOperator> query(WhereCondition wc) {
		return logAbfOperatorService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return logAbfOperatorService.count(wc);
	}

	@Override
	public LogAbfOperator loadByGuid(String guid) {
		return logAbfOperatorService.loadByGuid(guid);
	}

}
