
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.log.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.log.LogAbfOperate;
import org.tis.tools.rservice.log.basic.ILogAbfOperateRService;
import org.tis.tools.service.log.LogAbfOperateService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 操作日志(LOG_ABF_OPERATE) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "log", version = "1.0", interfaceClass = ILogAbfOperateRService.class, timeout = 2000, document = "操作日志的基础远程服务")
public class LogAbfOperateRServiceImpl implements ILogAbfOperateRService {

	@Autowired
	LogAbfOperateService logAbfOperateService;

	@Override
	public void insert(LogAbfOperate t) {
		logAbfOperateService.insert(t);
	}

	@Override
	public void update(LogAbfOperate t) {
		logAbfOperateService.update(t);
	}

	@Override
	public void updateForce(LogAbfOperate t) {
		logAbfOperateService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		logAbfOperateService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		logAbfOperateService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, LogAbfOperate t) {
		logAbfOperateService.updateByCondition(wc,t);
	}

	@Override
	public List<LogAbfOperate> query(WhereCondition wc) {
		return logAbfOperateService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return logAbfOperateService.count(wc);
	}

	@Override
	public LogAbfOperate loadByGuid(String guid) {
		return logAbfOperateService.loadByGuid(guid);
	}

}
