
/**
 * Copyright (C) 2016 bronsp.com, All rights reserved.
 */
package org.tis.tools.rservice.log.basic;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.tis.tools.base.WhereCondition;
import org.tis.tools.model.po.log.LogAbfHistory;
import org.tis.tools.rservice.log.basic.ILogAbfHistoryRService;
import org.tis.tools.service.log.LogAbfHistoryService;

import com.alibaba.dubbo.config.annotation.Service;

/**
 * 操作对象历史记录(LOG_ABF_HISTORY) 基本远程服务实现(服务提供者)
 * 
 * @author by generated by tools:gen-dao
 *
 */
//TEMPLATES
@Service(group = "log", version = "1.0", interfaceClass = ILogAbfHistoryRService.class, timeout = 2000, document = "操作对象历史记录的基础远程服务")
public class LogAbfHistoryRServiceImpl implements ILogAbfHistoryRService {

	@Autowired
	LogAbfHistoryService logAbfHistoryService;

	@Override
	public void insert(LogAbfHistory t) {
		logAbfHistoryService.insert(t);
	}

	@Override
	public void update(LogAbfHistory t) {
		logAbfHistoryService.update(t);
	}

	@Override
	public void updateForce(LogAbfHistory t) {
		logAbfHistoryService.updateForce(t);
	}

	@Override
	public void delete(String guid) {
		logAbfHistoryService.delete(guid);
	}

	@Override
	public void deleteByCondition(WhereCondition wc) {
		logAbfHistoryService.deleteByCondition(wc);
	}

	@Override
	public void updateByCondition(WhereCondition wc, LogAbfHistory t) {
		logAbfHistoryService.updateByCondition(wc,t);
	}

	@Override
	public List<LogAbfHistory> query(WhereCondition wc) {
		return logAbfHistoryService.query(wc);
	}

	@Override
	public int count(WhereCondition wc) {
		return logAbfHistoryService.count(wc);
	}

	@Override
	public LogAbfHistory loadByGuid(String guid) {
		return logAbfHistoryService.loadByGuid(guid);
	}

}
